### ISSUE TITLE
Define default language for code execution

### ISSUE THREAD

**Issue by w3adventures** [formulahendry/vscode-code-runner#1]
Is it possible to define default language for code execution?

For example I open new plain text file (Ctrl+N) and do some javascript in it and want to run it but it says 'Code language not supported or defined'.

Can I set to run code as javascript if code language is not defined?

For fast code testing without saving new file it would be even better to have commands like 'run code js', 'run code php' and so on.

**Comment by formulahendry** [comment]
Hi @w3adventures , thanks a lot for your feedback. That's a very nice idea. :smiley:  I have updated the extension to support: 1.set default language to run 2.select language to run. Please follow the instruction and have a try. Let me know whether it works well for you.

**Comment by w3adventures** [comment]
It works great :smiley:
Thanks for superfast implementation!
