### ISSUE TITLE
option to save the file before running

### ISSUE THREAD

**Issue by rickmed** [formulahendry/vscode-code-runner#10]
So if you have autosave on (on "onFocusChange") it does not consider changing the focus when running the script with this extension (which I believe is the expected behavior since every time I'd like to run a script I would need to change the focus back to the file to keep working on it).

But if you have autosave on, you would expect the file to be saved before running it. So could the extension have an option to save the file before running it? :)

**Comment by formulahendry** [comment]
Valid requirement. :)  Will implement it.

**Comment by formulahendry** [comment]
@rickmed , please try the latest version 0.2.1

**Comment by rickmed** [comment]
@formulahendry works :100:
