### ISSUE TITLE
知乎——曼殊沙华：code runner 运行只显示这些

### ISSUE THREAD

**Issue by object123** [formulahendry/vscode-code-runner#101]
这是我使用vscode问题界面截屏
![j3i001ep lv wbg1 sjsk1m](https://cloud.githubusercontent.com/assets/26652956/24891102/3f79f990-1ea6-11e7-9398-5c22a80c382a.png)

**Comment by formulahendry** [comment]
Please try:
1. Not have selection of  any code
2. Run just a simple 'Hello World' code

**Comment by object123** [comment]
还是那样/(ㄒoㄒ)/~~
![Uploading SAFZN]Q%`BQ3}$}2M3X4V@5.png…]()

**Comment by formulahendry** [comment]
把[Running]之后的command放到cmd跑呢

**Comment by object123** [comment]
不报错，但是也不显示其他内容

**Comment by formulahendry** [comment]
建议你学习一下gcc的基本知识，这样比较好trouble shooting

**Comment by object123** [comment]
嗯嗯，谢谢你的建议
