### ISSUE TITLE
Add option to disable running selected code

### ISSUE THREAD

**Issue by bumbu** [formulahendry/vscode-code-runner#102]
It would be great if it would be possible to disable running selected code. 
Say `code-runner.ignoreSelection` or `code-runner.alwaysRunEntireFile`.

With that option enabled, even if there is a selected piece of code, it would run the entire file at all times.

**Comment by formulahendry** [comment]
Valid requirement. Thanks for your feedback! I will plan to implement that.

**Comment by formulahendry** [comment]
@bumbu , `code-runner.ignoreSelection` hase been added. Please install the latest version and have a try.

**Comment by bumbu** [comment]
Amazing! 
@formulahendry - thank you a lot
