### ISSUE TITLE
Cannot type '}' on Hungarian keyboard

### ISSUE THREAD

**Issue by jabbalaci** [formulahendry/vscode-code-runner#103]
I have a Hungarian keyboard and I need to press Alt Gr + n to get the '}' character. When Code Runner is installed, Alt Gr + n triggers code runner, so it's equivalent to pressing Ctrl + Alt + n. As a result, I cannot type '}'. I tried it on Windows with the latest VS Code and latest Code Runner. Any idea how to solve this problem? Thanks.

(Alt Gr is not the same as Alt, [see here](https://farm3.static.flickr.com/2495/4085543721_f061a93857_o.jpg) for instance).

**Comment by formulahendry** [comment]
You could refer to [this](https://code.visualstudio.com/docs/customization/keybindings#_customizing-shortcuts) to customize keyboard shortcut for "code-runner.run" (Run Code) to avoid keyboard conflicts.

**Comment by jabbalaci** [comment]
Thanks, I could solve the problem like that.
