### ISSUE TITLE
Bug: Segmentation Fault when Setting Terminal Root to "/" in Code Runner on Windows

### ISSUE THREAD

**Issue by darshnagdeve35** [formulahendry/vscode-code-runner#1051]
- VS Code Version:1.80.1
- OS Version:21H2
- Code Runner Version:0.12.0

**Describe the bug**
When setting the terminal root is set to "/" in Code Runner so that code runner code can use the unix based command line BASH in order to not use the "\\" which is default terminal root and is considered as a delimiter in unix based command lines , the C++ program encounters a segmentation even though there are no apparent bugs in the code

**To Reproduce**

1. Open Code Runner in the specified project directory
2. allow Code Runner to use Terminal to execute the built project
3. Set the terminal root to "/"
4. Compile and run the C++ program with the provided code.

**Actual behavior**
The program compiles without errors, but when executed, it encounters a segmentation fault . As a result, the program crashes, and no output is displayed.

**Expected behavior**
The program should execute without any errors or segmentation faults and terminate successfully.

**Comment by Quatreble** [comment]
Did you find a solution? im facing the same problem right now.
