### ISSUE TITLE
Support for C++ 20

### ISSUE THREAD

**Issue by serdarmutlu** [formulahendry/vscode-code-runner#1052]
**Is your feature request related to a problem? Please describe.**
I can't run C++ codes based on C++20 features.

**Describe the solution you'd like**
A configuration to set specific C++ version.

**Comment by lbnv** [comment]
> **Is your feature request related to a problem? Please describe.** I can't run C++ codes based on C++20 features.
> 
> **Describe the solution you'd like** A configuration to set specific C++ version.

1. Open Extensions in the right tab, click a gearwheel on Code Runner bar, choose "Extension Settings" from pop-up menu to open "Settings" tab.
2. On "Settings" tab find "Code-runner: Executor Map" and ckick "Edit in settings.json".
3. In json file find "cpp" command.
4. Paste "-std=c++20" (without quotation marks) after "g++".
Before:
"cpp": "cd $dir && g++ $fileName -o $fileNameWithoutExt && $dir$fileNameWithoutExt",
After:
"cpp": "cd $dir && g++ -std=c++20 $fileName -o $fileNameWithoutExt && $dir$fileNameWithoutExt",
5. Done!

I got warnings about features avialable with '-std=c++20' or '-fconcepts' only, now the've gone.

**Comment by yusuf601** [comment]
don't work bro,cpp+20 intellisense not working on vs code
@lbnv
