### ISSUE TITLE
Bash on Windows10 issue

### ISSUE THREAD

**Issue by VincentCream** [formulahendry/vscode-code-runner#106]
I'm working on a python project using **bash on Windows10** as terminal
` "terminal.integrated.shell.windows": "C:\\Windows\\sysnative\\bash.exe",`

I use the integrated terminal with code-runner
`"code-runner.runInTerminal": true,`

When I run the code, the following command is launch :
`python3.6 "d:\HES\Semestre_6\Projet_linux\TelePyDuino_Monitoring\Python\bot3.py"`
Python can't open file because there is no such file or directory
This is a windows path..

The command with the right path for bash has to be :
`python3.6 /mnt/d/HES/Semestre_6/Projet_linux/TelePyDuino_Monitoring/Python/bot3.py`

Is there sometting in the settings ?
Could you fix it

thanks,
Vincent

**Comment by kongroo** [comment]
The same issue. The $filename variable returns a windows style path, it shouldn't be hard to detect if bash on windows is used and map a windows path to a shell path.

**Comment by formulahendry** [comment]
@kongroo PR is welcome! 😃

**Comment by formulahendry** [comment]
This issue has been fixed, please try the latest version.

**Comment by pottiepie** [comment]
Because Windows filesystem is not case sensitive, my setting was `"terminal.integrated.shell.windows": "C:\\WINDOWS\\sysnative\\bash.exe",`, which caused the new fix to not work.

**Comment by pottiepie** [comment]
The default executor for C/C++ is `cd $dir && gcc $fileName -o $fileNameWithoutExt && $dir$fileNameWithoutExt"`. Only the first `$dir` is being replaced. The second `$dir` still expands to the Windows style path.

**Comment by formulahendry** [comment]
Thanks @pottiepie ! Those two issues has been fixed. Please try the latest version.

**Comment by pottiepie** [comment]
Thanks @formulahendry. It works great now. Though I felt it might be better to do the path replacement in `getCodeFileDir` instead since this (I think) would replace the entire exec string.

**Comment by formulahendry** [comment]
Thanks @pottiepie for your suggestion. I will consider improving this.

**Comment by djtorel** [comment]
Hello, would it be possible to make this fix work for other types of bash shells being used in Windows, like Cmder, Git Bash/Mintty, Cygwin? Perhaps it could use the "terminal.integrated.shell.windows" setting as reference for where the variables should be run from? I have the same issue and was using: "terminal.integrated.shell.windows": "C:\\Program Files\\Git\\bin\\bash.exe" for example.

**Comment by formulahendry** [comment]
@djtorel , https://github.com/formulahendry/vscode-code-runner/issues/149 is opened to track it.
The most tricky part is the Windows Drive path in each bash is different. 
- Bash on Windows: it is `/mnt/c/...`
- Git Bash: it its`/c/..`
- And for other bash, it seems also different.

Do you know the Windows Drive path format for Cmder, Git Bash/Mintty, Cygwin, MinGW or others?

**Comment by djtorel** [comment]
Thanks for responding! Cmder uses git bash and Mintty as bash options by default and of course cmd and powershell. I apologize for bringing that up specifically, because I don't think it can integrate with VSCode's terminal (it's basically a configuration ConEmu).

Both Git Bash and Mintty have /c/
Cygwin is /cygdrive/c/

**Comment by pottiepie** [comment]
Maybe a proper fix would be to allow a customized root path.

**Comment by formulahendry** [comment]
@djtorel , I have tried running code in Git Bash without issue:
![image](https://user-images.githubusercontent.com/1050213/29001244-7c266c0e-7ab6-11e7-99a6-0ca5d75d20c4.png)
It seems that it could handle Windows file path well. Could you please let me know what issue you meet with?

**Comment by pottiepie** [comment]
I've submitted a pull request to basically allow user to customize whichever terminal root they want. Problem with Cygwin is that user could have installed it in another directory with "Windows" in the path and it also runs `bash.exe`, which currently the code takes to be Bash on Ubuntu.

**Comment by JUD210** [comment]
> @djtorel , I have tried running code in Git Bash without issue:
> ![image](https://user-images.githubusercontent.com/1050213/29001244-7c266c0e-7ab6-11e7-99a6-0ca5d75d20c4.png)
> It seems that it could handle Windows file path well. Could you please let me know what issue you meet with?

In C++/Java/... using $dir result is not a format of Git Bash.

**Comment by JamesQian1999** [comment]
I also setup WSL Ubuntu but I can't run with WSL in right the path.
How to I run code with WSL in the right path?

This is my settings.json
`{ "code-runner.runInTerminal": true, "terminal.integrated.shell.windows": "C:\\WINDOWS\\System32\\wsl.exe", "code-runner.executorMap": { "c": "cd $(wslpath $dir) & gcc $fileName -o $fileNameWithoutExt & ./$fileNameWithoutExt", "cpp": "g++ $fileName -o $fileNameWithoutExt -std=c++11 & ./$fileNameWithoutExt"}, "python": "python3 -u ./$fileName", }`

When I run my code with "ctrl+alt+N"
The output became:
`jamesqian@J:/mnt/c/Users/Jamesqian/Desktop/tmp$ cd $(wslpath "c:\Users\Jamesqian\Desktop\tmp\") & gcc test.c -o test & ./test`

wslpath is [https://github.com/laurent22/wslpath](url)

**Comment by wuyudi** [comment]
Solution: https://github.com/formulahendry/vscode-code-runner/issues/468#issuecomment-763017668
