### ISSUE TITLE
how can I run JAVA code with CodeRunner?

### ISSUE THREAD

**Issue by seiferthan** [formulahendry/vscode-code-runner#108]
Dear all:

I have installed JDK, VSC, and CodeRunner(btw, I have already set the path for JAVA correctly). However, when I try to use CodeRunner, there is always a same error message express: **"error: class learn1 is public, should be declared in a file named learn1.java**", and please see the picture below. 

I am very sure that I named the class which is same as the file name.

[http://imgur.com/m52uJua](url)

the whole message is:

> [Running] cd "d:\Dropbox\coding\practices\JAVA\src\" && javac temp-msvqqxjdsd.java && java temp-msvqqxjdsd
temp-msvqqxjdsd.java:1: error: class learn1 is public, should be declared in a file named learn1.java
public class learn1 {
       ^
1 error
[Done] exited with code=1 in 5.295 seconds

I can use the Eclipse Neon for JAVA EE to compile can run the same file correctly. Do I need to setup anything before I use the feature in VSC? VSC is very cool and light, and I really want to use it to learn developing JAVA application. Please help me to figure out this problem. Thank you so much!

**Comment by formulahendry** [comment]
Hi @seiferthan , I see you have selected the code. Please do not select the code snippet and try again.

**Comment by formulahendry** [comment]
Or, you could use below setting (`File`->`Preference`->`Settings`) to avoid the impact of selection:
```json
{
    "code-runner.ignoreSelection": true
}
```

**Comment by seiferthan** [comment]
@formulahendry  
Thank you!!! Your are awesome! I tried to fined the solution for two days, and it seems few of people had faced this problem before. 
It's very wonderful to know the tip! Thank you again! :+1:

**Comment by formulahendry** [comment]
You are welcome.
