### ISSUE TITLE
Debuging, error linking to file and row by lines number from output

### ISSUE THREAD

**Issue by ManPython** [formulahendry/vscode-code-runner#111]
I want sugest solution with linking to file and row lines number from output to place where is error for debuging this place (line). Something like hyberlink.

1. python
` File "e:\PYTHON\test.py", line 10, in TestFunction self.test= SuperTest(self)`
- **line 10** can be as hiperlink to row 10 in test.py file

**Comment by formulahendry** [comment]
Hi @ManPython , thanks for your feedback, but this feature request is out of the scope of Code Runner. So closing this issue.
