### ISSUE TITLE
Format table in output

### ISSUE THREAD

**Issue by Danieleeee** [formulahendry/vscode-code-runner#114]
Hi,
great extension.
I'm using it with sqlplus commands and works good.

The problem is that when I execute query, the output isn't formatted:
![1](https://cloud.githubusercontent.com/assets/22749175/26287236/8c685652-3e77-11e7-973d-12d6e5ce6d84.png)

It is possbile format output like Excel Viewer
![csv-preview-qt](https://cloud.githubusercontent.com/assets/22749175/26287245/dc219d20-3e77-11e7-9769-e9e8826d01ee.gif)

Or mssql extension?
![mssql-demo](https://cloud.githubusercontent.com/assets/22749175/26287262/1636aca8-3e78-11e7-874d-b372504e92f3.gif)

Thanks.

**Comment by formulahendry** [comment]
Hi @Danieleeee , thanks for your suggestion. However, Code Runner just print the output the same as the stdout from the code. It will not and could not add extra format to the stdout. So closing this issue as `Could Not Fix`.

May be you could try running sqlplus commands in Integrated Terminal to see whether the format would be better. Use below setting (`File`->`Preference`->`Settings`) to run code in Integrated Terminal:
```json
{
    "code-runner.runInTerminal": true
}
```
