### ISSUE TITLE
Aftert I set code-runner.executorMap ，it can't run 

### ISSUE THREAD

**Issue by 9526xu** [formulahendry/vscode-code-runner#115]
when I set this
![image](https://cloud.githubusercontent.com/assets/15943801/26290452/34aa4ca0-3eda-11e7-8121-47dad88b21f9.png)
It is running and will not end
![image](https://cloud.githubusercontent.com/assets/15943801/26290471/4fa833c8-3eda-11e7-99c9-3d58f8e3642c.png)
It does’t take the file's path。
But，when I set  code-runner.executorMap like this：
![image](https://cloud.githubusercontent.com/assets/15943801/26290543/e8f8739e-3eda-11e7-8586-e2637c1d0617.png)
It can work and it has the file's path .
My $workrootSpace is this /Users/xurujian/workspace/python/huxiu
I don't know where the problem is？

**Comment by formulahendry** [comment]
You need to explicitly append `$fullFileName` if you have used `$workspaceRoot` or other customized parameters. The code logic behind is that if no customized parameters are used, the `$fullFileName` will be added, otherwise it will not be added.
