### ISSUE TITLE
[Bug]Code runner not saving changes to code file before running it  

### ISSUE THREAD

**Issue by Proggramosaur** [formulahendry/vscode-code-runner#1158]
- VS Code Version:1.91.1
- OS Version: windows 22H2
- Code Runner Version: 0.12.2 (2024-04-05) 

**Describe the bug**
I can't confirm if thats really a bug or not, but the extension isn't saving the changes to the file like it normally does and directly running the proggrame

**To Reproduce**

1. Open an already saved file and make random changes to it .
2. Use the extension's Keyboard shortcut ctrl+alt+n or click on the icon at the top-right to run the file

**Actual behavior**
So I was creating a python file that takes input from user and stores it in list . I runned for first and it worked fine giving an error. I fixed it and ran again but the same error repeated . I scratched my head and tried running with other possible changes asked Chat GPT, in case some problem, even that didn't knew why was it giving error despite correct code . Then I noticed that the dot in VS Code had not disappeared which meant changes file wasn't saved in the first place

**Expected behavior**
The file should have runned correctly after the changes
**Screenshots**

**Comment by zhuoqun-chen** [comment]
@Proggramosaur You can see more info in https://github.com/formulahendry/vscode-code-runner/issues/378, you just need to:

```shell
"code-runner.saveFileBeforeRun": true
```

in your `settings.json`.

**Comment by Proggramosaur** [comment]
Yeah that was some stupidity I accidentaly turned it off sometime before and didn't know about it . Now it works thanks man. I am not much active on github so didn't got this notification earlier 😅
