### ISSUE TITLE
Exited with code=-2 in Output window

### ISSUE THREAD

**Issue by bhavinkamani** [formulahendry/vscode-code-runner#116]
While running a javascript code, I keep getting following message in the output window.

```
[Running] node "<absolute path to file>"

[Done] exited with code=-2 in 0.005 seconds
```

However, when `code-runner.runInTerminal` is set to `true`, the run command works fine in terminal window.

The command run in the output window used to run fine till a day before.

I am running on the VSCode `1.12.2`, node `7.10.0` on osx Sierra `10.12.4`

**Comment by formulahendry** [comment]
Have you tried running a simple `console.log()` code?

**Comment by bhavinkamani** [comment]
Yes. Content of my file is `console.log("Hello World")`. Still gives me the same issue.

**Comment by formulahendry** [comment]
About running other files? e.g. bash, python

**Comment by bhavinkamani** [comment]
Tried with bash - `echo "Hello"`. Same issue

**Comment by formulahendry** [comment]
Could you restart VS Code and clean all VS Code process , then try again? Or better, restart your computer.

**Comment by bhavinkamani** [comment]
I restarted the computer. It didn't help. I removed the vscode cache. That seems to have helped. I am not seeing this issue any more.. Still not sure what was the root cause.

Thanks for all your help.

**Comment by bhavinkamani** [comment]
I found the culprit. It was `"code-runner.cwd": "$workspaceRoot"`. I had kept it while trying to troubleshoot some other issue. Started receiving the expected result in output window once I removed this settings.

Putting this down for those who may face similar issue.
