### ISSUE TITLE
Code runner output shows "Running" and then exits with no actual output

### ISSUE THREAD

**Issue by NuggetDev41** [formulahendry/vscode-code-runner#1179]
![لقطة الشاشة 2024-09-29 182608](https://github.com/user-attachments/assets/6075d0ff-946f-4ab9-9b8c-dd9eaf59cf7d)and I even tried to check the "Run in terminal" option, doesn't work aswell
all when I was writing some ruby code

**Comment by THEFIRSTONE-1** [comment]
How did your issue get resolved....cause i also have the same issue
