### ISSUE TITLE
Unable to input after using code-runner

### ISSUE THREAD

**Issue by S1xe** [formulahendry/vscode-code-runner#121]
Hey dear developer,
    I find the problem when I use the code-runner,that I can't input even a number after I did "Run Code";
Here is the code that I used.
```c++
#include<iostream>

int main(){
  int n;
  std::cout<<"Please input:";
  std::cin>>n;
  std::cout<<"Get n,that 's:"<<n<<std::endl;
  return 0;
}
```
But unfortunately, it just show
```bash
[Running] cd "d:\Update\" && g++ temp-vlmviqzxqp.cpp -std=c++14 -o temp-vlmviqzxqp && "d:\Update\"temp-vlmviqzxqp
Please input:
```
However,I can't type any number or character.

**Comment by formulahendry** [comment]
Hi @S1xe , for input support, please refer to #91

**Comment by S1xe** [comment]
After I changed "code-runner.runInTerminal"
```json
{
    "code-runner.runInTerminal": true
}
```
I still can't input like before.

**Comment by S1xe** [comment]
Here is my vsc's setting
```json
{
    "editor.fontFamily": "'Source Code Pro',Consolas, 'Courier New', monospace",
    "editor.fontSize": 16,
    "window.zoomLevel": 0,
    "code-runner.runInTerminal": true
}
```
I use the old code.But I still can't type any character in the **OUTPUT**.Where should I type number or charact ?

**Comment by formulahendry** [comment]
Are you selecting all the code of file? That will prevent code to be run in terminal.
Or, you need to add below setting as well:
```json
{
    "code-runner.ignoreSelection": true
}
````

**Comment by S1xe** [comment]
Thanks a lot!Now I can type number in my terimal after I use ```"code-runner.ignoreSelection": true```. @formulahendry
