### ISSUE TITLE
Can't differentiate between an output of a number, and a string that contains numeric characters 

### ISSUE THREAD

**Issue by usernameisvince** [formulahendry/vscode-code-runner#124]
I'm new to programming but something I noticed is when you run an output or console.log of a string of number, there's no differentiation from just a number. This can be problematic, i.e.

var string = "1990";
console.log(string);

var num = 1991;
console.log(num);

**expected output:**
"1990"
1991

**actual output:**
1990
1991

**Comment by formulahendry** [comment]
To output `"1990"`:
```javascript
var string = "\"1990\"";
console.log(string);
```
