### ISSUE TITLE
Cannot run Kotlin

### ISSUE THREAD

**Issue by reyou** [formulahendry/vscode-code-runner#125]
Hello,

I am having hard time to run Kotlin. Can you please help?

Here is my setup;

![image](https://user-images.githubusercontent.com/6571483/27018059-6b59d474-4efb-11e7-9466-357d33c7a147.png)

![image](https://user-images.githubusercontent.com/6571483/27018066-7ce22570-4efb-11e7-84d8-3ccab550ab94.png)

![image](https://user-images.githubusercontent.com/6571483/27018121-e17afbce-4efb-11e7-8571-9232f41051b1.png)

Error I am getting:

![image](https://user-images.githubusercontent.com/6571483/27018095-b6fe6e80-4efb-11e7-9157-c4e742a1fc20.png)

Am I missing something here?

**Comment by formulahendry** [comment]
You need to update kotlin in 'code-runner.executorMap'  of https://github.com/formulahendry/vscode-code-runner/blob/master/package.json#L128. 
```json
"kotlin": "cd $dir && C:\\Programs2\\***\\kotlinc.bat $fileName -include-runtime -d $fileNameWithoutExt.jar && java -jar $fileNameWithoutExt.jar"
```
