### ISSUE TITLE
Document toolbar "Run Code" button

### ISSUE THREAD

**Issue by SailorMax** [formulahendry/vscode-code-runner#128]
Can you add to document toolbar, where we have "Split Editor" button, to start of the list, button `►` for "Run Document Code" (not selection)?
You can use icon from debug "Start Debugging".

thank you.

**Comment by formulahendry** [comment]
Released in latest version
![image](https://user-images.githubusercontent.com/1050213/27335614-b5646218-55ff-11e7-8828-e47a6d3306cd.png)

**Comment by Mohanson** [comment]
Can you give a configuration item to let the user decide whether to display this button? It's useless for many people, and the BIG GREEN ICON destroys the color theme.  It's a little ugly on 'Solarized Dark' and 'Solarized Light'.

**Comment by SailorMax** [comment]
@formulahendry 
And, if it possible, can you change it to red square with "Stop" function to kill executed process. Some broken scripts can work very long :)

thank you.

**Comment by Chillee** [comment]
I agree with @Mohanson. I don't want this.

**Comment by formulahendry** [comment]
Added option to hide 'Run Code' button:
```json
"code-runner.showRunIconInEditorTitleMenu": false
```
Also, I make the green icon smaller then before, and #132 to track the refinement of 'Run Code' button
![image](https://user-images.githubusercontent.com/1050213/27368255-f7e0891c-5683-11e7-95da-beddb1dc79b2.png)

**Comment by formulahendry** [comment]
@Mohanson   Currently, VS Code does not provide a way to dynamically to show/hide or change the button.

You could use `Ctrl+Alt+M`, or stop code running in Output Channel

![image](https://user-images.githubusercontent.com/1050213/27368414-f87c0c1a-5684-11e7-8e1d-20ea601f912c.png)
