### ISSUE TITLE
Option to hide run code button

### ISSUE THREAD

**Issue by jbw91** [formulahendry/vscode-code-runner#131]
There should be a user setting whether or not to show the green Run Code button in the editor. That should definitely be something the user decides, particularly since it's usually not an extension that most of us use frequently, but rather on occasion to test something. In addition, it clashes with many themes in the marketplace due to its look and feel being quite different from that of VS Code.

**Comment by Chillee** [comment]
Strongly agree.

**Comment by formulahendry** [comment]
Added option to hide 'Run Code' button:
```json
"code-runner.showRunIconInEditorTitleMenu": false
```

**Comment by chrs897** [comment]
> Added option to hide 'Run Code' button:
> 
> ```json
> "code-runner.showRunIconInEditorTitleMenu": false
> HOW TO ACTIVATE RUN CODE BUTTON IN VS CODE. IT'S NOT AT ALL VISIBLE. I hid it by mistake

**Comment by jeffchen006** [comment]
I have to say, I meet the same problem as @chrs897 .   

I accidentally hid "Run Code" button and cannot find a way to bring it back.

**Comment by jeffchen006** [comment]
All right. Sorry I think I figured it out. 

We need to right click the "More Actions" button to bring it back.

**Comment by SonamB11** [comment]
> 

Can you elaborate how to bring the run button back.

**Comment by rrgulati** [comment]
> > 
> 
> Can you elaborate how to bring the run button back.

Right click on the more actions button and select the reset option, it will automatically come back.

**Comment by ozanba** [comment]
I've been looking for this for about 20 minutes thank you

**Comment by rrgulati** [comment]
> I've been looking for this for about 20 minutes thank you

You're welcome ;)

**Comment by sharjeelmazhar** [comment]
Where is more action button? I can't seem to find it. Kindly help me, i also accidentally hid my run button

**Comment by ruturaj-gh** [comment]
![image](https://user-images.githubusercontent.com/83021083/214773924-8563a9d9-e338-42d3-bb79-319c4dc65556.png)
 there is no any 'more action button available here ' @rrgulati @ozanba @jeffchen006

**Comment by ozanba** [comment]
the button you click is the more action button. just right click the button

**Comment by ruturaj-gh** [comment]
demn thank you @ozanba  why didn't they made it in simple way.

**Comment by ozanba** [comment]
you're welcome

**Comment by rrgulati** [comment]
> > ![image](https://user-images.githubusercontent.com/83021083/214773924-8563a9d9-e338-42d3-bb79-319c4dc65556.png) there is no any 'more action ' button available here @rrgulati @ozanba @jeffchen006
> 
> the button you click is the more action button. just right click the button

That's the more action button 😂

**Comment by jabedkhanjb** [comment]
to get back your run button, please install or reinstall your code runner extension. that's the solution. if you fix it, no need to thank me instead gimme a follow on my github profile. haha, thank u

![Screenshot_121](https://user-images.githubusercontent.com/86038917/215068217-0b035f50-3a09-4577-ac4e-21a9c78df2e1.png)

**Comment by rrgulati** [comment]
> to get back your run button, please install or reinstall your code runner extension. that's the solution. if you fix it, no need to thank me instead gimme a follow on my github profile. haha, thank u
> 
> ![Screenshot_121](https://user-images.githubusercontent.com/86038917/215068217-0b035f50-3a09-4577-ac4e-21a9c78df2e1.png)

It won't help if you have turned Sync on :(

**Comment by jabedkhanjb** [comment]
> 

it works, i got the same issues and reached here, after that i found my solution and have shared. did u try ?

**Comment by rrgulati** [comment]
> > 
> 
> it works, i got the same issues and reached here, after that i found my solution and have shared. did u try ?

Yes I tired, that's why I said it won't work if you've turned on Sync :(

**Comment by Inferno955** [comment]
![Screenshot (296)](https://user-images.githubusercontent.com/125037240/220134226-5e540744-111b-4cf8-8d5a-d56e1231a87b.png)
Guys does the highlighted section on the terminal being displayed to everybody or is it just me?
Can we make it disappear and make it display only the code?

**Comment by rrgulati** [comment]
> ![Screenshot (296)](https://user-images.githubusercontent.com/125037240/220134226-5e540744-111b-4cf8-8d5a-d56e1231a87b.png) Guys does the highlighted section on the terminal being displayed to everybody or is it just me? Can we make it disappear and make it display only the code?

It defaults for everyone. It is the syntax used in command prompt to execute your program
