### ISSUE TITLE
[UI] Refine 'Run Code' button

### ISSUE THREAD

**Issue by formulahendry** [formulahendry/vscode-code-runner#132]
Make the look and feel of 'Run Code' button aligned with most dark and light theme.

![image](https://user-images.githubusercontent.com/1050213/27368255-f7e0891c-5683-11e7-95da-beddb1dc79b2.png)

We may want to have two icons: one for dark theme, one for light theme.

**Comment by JeffreyCA** [comment]
Hello, I attempted to address this in #151.
