### ISSUE TITLE
似乎识别路径出现了问题以及乱码

### ISSUE THREAD

**Issue by aqnaruto** [formulahendry/vscode-code-runner#136]
![image](https://user-images.githubusercontent.com/9067159/27688606-bc2e678c-5d0d-11e7-926f-35064ce2744f.png)

如图所示，我本机应该是gbk编码，文件是utf-8编码。 我看到乱码后 用命令行在路径下执行是对的 并且生成了文件。说明环境变量什么都没有问题。

**Comment by formulahendry** [comment]
Please refer to #79 and #91
