### ISSUE TITLE
输出窗口右键执行一次"清除输出",至少一次以上Code Runner运行失效

### ISSUE THREAD

**Issue by Refactoring** [formulahendry/vscode-code-runner#137]
多点击几次运行又正常运行。  执行"清除输出"后，使用快捷键(Ctrl+Alt+N)方式启动执行命令,会一直提示这个错误，必须手工点击右上的绿色运行按钮。
如下图，提示信息"Code language not supported or defined."。
![20170704121222](https://user-images.githubusercontent.com/451129/27815025-a1cb4942-60b3-11e7-840c-53def30c925c.png)

**Comment by formulahendry** [comment]
You need to keep focus (cursor) on Code Editor area instead of Output Channel.
