### ISSUE TITLE
Support relative paths to commands

### ISSUE THREAD

**Issue by rickmed** [formulahendry/vscode-code-runner#14]
Currently, the extension looks for the command in the OS path. But having global installs is a horrible dev experience. The alternative is to create a npm script (which calls the local install of the npm module) and 
create andexecmap in vscode-runner that goes through that npm script. It gets messy. 

It would be super nice for the extension to support this:

```
 "code-runner.executorMap": {
      "mon": "./node_modules/.bin/nodemon",
}
```

So if you have installed x module (with a runnable) locally, it runs it. This is super helpful when cloning repos and working with modules like babel, nodemon, gulp, etc, etc...Which is the dev's day to day life.

**Comment by rickmed** [comment]
Or better yet, for the extension to look for local installs first (which are all located in that relative dir) and then look in the path -maybe with an option to turn on/off this behaviour.

**Comment by formulahendry** [comment]
Relative path to cwd or the current file?

**Comment by rickmed** [comment]
relative path to the program (executable) to run

**Comment by formulahendry** [comment]
Will cwd make more sense?
For example:
cwd: D:\project1
program: D:\project1\folder1\test.js
It would be like below:
**D:\project1>.\node_modules\.bin\nodemon folder1\test.js**
It is relative to cwd not program.

For looking first at the executable at node_modules/.bin/, I think it is too hard coded. This extension is not just for node. I want to provide a more general usage.

**Comment by rickmed** [comment]
@formulahendry I'm not sure I follow, how would I set it in settings.json?

**Comment by formulahendry** [comment]
You could refer to my setting (on Windows):
![image](https://cloud.githubusercontent.com/assets/1050213/17837636/864eb284-67ea-11e6-8447-8d7c71e0528b.png)

**Comment by rickmed** [comment]
Yes. That is it! 
BTW, your output coloring looks neat, is that a new extension version or a vscode theme?

**Comment by formulahendry** [comment]
I use default dark theme and in v0.2.1 the output coloring is already there. So what does your output coloring look like?

**Comment by rickmed** [comment]
![image](https://cloud.githubusercontent.com/assets/7104786/17838407/0c2d0f90-679b-11e6-98ea-dcf1bc4ff0b2.png)

**Comment by rickmed** [comment]
I checked. Colors changes based on the theme.

**Comment by formulahendry** [comment]
I'd prefer the colors to be aligned with the theme. :smiley:   Hard code coloring may break the overall style.
