### ISSUE TITLE
Support for Nim

### ISSUE THREAD

**Issue by ncme** [formulahendry/vscode-code-runner#140]
Hi,
I love this extension - especially the feature to run selected lines of code!

I just started tinkering with [Nim](https://nim-lang.org) and, after finding it was not already supported, tried my hand at adding support for it, which was really easy and works great, at least for the limited use I have given it so far.

I would be willing to provide a Pull Request but I feel there are some things worth discussing beforehand:

By default the [Nim compiler](https://nim-lang.org/docs/nimc.html) is quite verbose and outputs so called Hints that provide information about what is going on.

The following output is created by implementing Nim to execute with `nim compile --run` and choosing *Run Code* on the code snippet `echo "Hello World!"`:

```
[Running] nim compile --run "/path/to/tempjqivpxccac.nim"
Hint: used config file '/etc/nim.cfg' [Conf]
Hint: system [Processing]
Hint: tempjqivpxccac [Processing]
CC: tempjqivpxccac
Hint:  [Link]
Hint: operation successful (10840 lines compiled; 0.211 sec total; 17.938MiB peakmem; Debug Build) [SuccessX]
Hint: /path/to/tempjqivpxccac.nim  [Exec]
Hello World!

[Done] exited with code=0 in 0.227 seconds
```
In my opinion this output is unnecessarily verbose, especially since the output from the Nim compiler is not colored, even when using the `--colors:on` flag.

Because running selected lines of code and observing their output is currently my main use of this extension I would thus choose the Nim compiler options `--verbosity:0 --hints:off` to remove all compiler noise from successful executions:

```
[Running] nim compile --verbosity:0 --hints:off --run "/path/to/tempjqivpxccac.nim"
Hello World!

[Done] exited with code=0 in 0.216 seconds
```

However, I have no experience with more complex Nim programs and thus no idea if there are use cases where using `--verbosity:0 --hints:off` would cause a problem or be an inconvenience to the user.

Obviously it would be a good idea to expose some possibility of configuration to the user, but the question about what would be the most sensible default still remains.

Cheers,
Niko (ncme)

**Comment by formulahendry** [comment]
Hi @ncme , thanks for sharing your opinion! I think it is good to make `--verbosity:0 --hints:off` as default. I believe most users would like that. If some user would like to change that, they could easily config it in the settings.json. So feel free to send your PR to add support for Nim. 😃 You could refer to this PR: https://github.com/formulahendry/vscode-code-runner/pull/82/files
