### ISSUE TITLE
When prints some Unicode strings, its behavior is different from running in the command

### ISSUE THREAD

**Issue by tan-wei** [formulahendry/vscode-code-runner#143]
For example, the Python codes will result in different behavior:
`# coding=utf-8

s = "中文"
u = s.decode('utf-8')
print u`

Run this code in cmd (Windows 7), it will print "中文". However, run this code in Code Runner, it will report a UnicodeEncodeError in the output. How does it happen? Please tell me the reason. Thanks very much. :-P

**Comment by formulahendry** [comment]
You could refer to https://github.com/formulahendry/vscode-code-runner/issues/25#issuecomment-263170907

**Comment by tan-wei** [comment]
It works.Thanks for your kindly reply.
