### ISSUE TITLE
fileDirectoryAsCwd have no effect on terminal

### ISSUE THREAD

**Issue by michaelHL** [formulahendry/vscode-code-runner#146]
> - OS: Windows 10 x64 (1607)
> - vscode: 1.14.2
> - code runner: 0.6.27

config:

```json
{
    "code-runner.executorMap": {
        "c": "gcc -std=c99 -Wall $fileName -o $fileNameWithoutExt && $fileNameWithoutExt",
        "cpp": "g++ -std=c++11 $fileName -o $fileNameWithoutExt && $fileNameWithoutExt",
    },
    "code-runner.saveFileBeforeRun": true,
    "code-runner.fileDirectoryAsCwd": true,
    "code-runner.runInTerminal": false,
    "code-runner.preserveFocus": true,
    "code-runner.showExecutionMessage": true,
    "code-runner.clearPreviousOutput": true,
    "code-runner.showRunIconInEditorTitleMenu": false,

    "terminal.integrated.shell.windows": "C:\\Windows\\Sysnative\\cmd.exe"
}
```

I find it fails to change `CWD` when I switch `"code-runner.runInTerminal"` to `true` (I type `C:` in terminal window in advance):

works well in `Output` | fails in `Terminal`
-------- | --------
![](http://i.imgur.com/90icJK2.png) | ![](http://i.imgur.com/5ukQeiK.png)

And I do not prefer to do some tricks in `"code-runner.executorMap"` (e.g. `cd /d $dir && ...`) 'cause it seems a bit messy, can you make some changes in terminal such as `cd /path/to/file` before running the code while `"code-runner.fileDirectoryAsCwd"` is set to be "true"? Thanks a lot ! :stuck_out_tongue:

**Comment by formulahendry** [comment]
@michaelHL Please try the latest version.

**Comment by michaelHL** [comment]
@formulahendry Nice Shot! Thx!
