### ISSUE TITLE
"Code language not supported or defined" Message after terminal clear

### ISSUE THREAD

**Issue by 1d82fdaaf812** [formulahendry/vscode-code-runner#147]
Context: 

Kotlin snipped with:
````
#main.kt
fun main(args: Array<String>) {
  println("kotlin run")
}
````

Steps to reproduce

1. Clear the terminal
2. Press the play button quickly
3. The message appears

![image](https://user-images.githubusercontent.com/15732201/28534286-d47ed6ee-7065-11e7-8823-089d0cdc9fc6.png)

Idea of the error:
`````
#codeManager.ts

....
       if (executor == null) {
            vscode.window.showInformationMessage('Code language not supported or defined.');
            return;
        }
`````
Is there something async waiting for initialization on clear?

**Comment by formulahendry** [comment]
The extension would detect the active text editor for the code to run. In your scenario, you may have put focus (cursor) on the Output Channel. You need to put cursor to the Kotlin code editor area. Then it issue would be resolved.

**Comment by formulahendry** [comment]
BTW, if you want to clear previous output before each run, you could config as below:
```
"code-runner.clearPreviousOutput": true
```
