### ISSUE TITLE
code runner v0.6.28  Ctrl+Alt+N don't work

### ISSUE THREAD

**Issue by skyhiter** [formulahendry/vscode-code-runner#148]
-----ENV-------
os:win7 x64
vscode:1.14.2
code runner: 0.6.28
-----------------
hot key Ctrl+Alt+N don't work.
when i press Ctrl+Alt+N, the top of vscode will show:
![image](https://user-images.githubusercontent.com/3953193/28699047-d19979f4-7379-11e7-85c7-79bb427e5b85.png)

And the right-hand button shows ：
![image](https://user-images.githubusercontent.com/3953193/28699096-1f35985a-737a-11e7-97f3-e72004927729.png)

**Comment by formulahendry** [comment]
@skyhiter Could you disable all other extension and try again? One of the extensions would have the keyboard binding conflict with Code Runner.

Go to `File` > `Preferences` > `Keyboard Shortcuts`, you will see
![image](https://user-images.githubusercontent.com/1050213/28699232-fbe5a736-737a-11e7-9844-89e49f2f386d.png)

**Comment by skyhiter** [comment]
thank u very much~
the extension "Advanced New File" also has this  hot key for "newFile.createNewFile".
now, i have changed  "Advanced New File" extension to "Shift+Alt+N"
