### ISSUE TITLE
Code Runner Quits Early When Running Java?

### ISSUE THREAD

**Issue by kpeng9** [formulahendry/vscode-code-runner#150]
When I'm running my java file, its suppose to print out a giant text wall, but code runner seems to quit early? It gives me this message.

"[Done] exited with code=null in 0.774 seconds"

Usually it gives me a code=0 instead of null. Is that the same thing?

**Comment by formulahendry** [comment]
Could you share the screenshot of whole VS Code?

**Comment by kpeng9** [comment]
1: http://imgur.com/a/LPmzW (using code runner)
2: http://imgur.com/a/xVMNq (with terminal)

My java file takes an input file and reverses the lines. I would include the whole code but its a reaaaaaaaaaly big giant text of wall.

**Comment by formulahendry** [comment]
No idea about that, but actually you could run Code Runner in termianl:
```
"code-runner.runInTerminal": true
```

**Comment by kpeng9** [comment]
Is it possible for you to walk me through the steps? I'm fairly new to coding and using VSCode.

**Comment by formulahendry** [comment]
Go to `File`->`Preference`->`Settings`, then add that config.

**Comment by kpeng9** [comment]
Oh wow that's amazing. Thank you!

**Comment by formulahendry** [comment]
Closing.
