### ISSUE TITLE
run C code

### ISSUE THREAD

**Issue by LiFanjieSeizeTheDay** [formulahendry/vscode-code-runner#155]
#include <stdio.h>

int main(void)
{
    int number = 10;
    
    printf("Please enter a number:");
    scanf("%d", &number);

    printf("The number is %d",  number);

    return 0;
}

[Running] cd "c:\Users\steeling\Desktop\临时文件\2017年4月24日——C Primer Plus\" && gcc tempcppedcuwnw.c -o tempcppedcuwnw && "c:\Users\steeling\Desktop\临时文件\2017年4月24日——C Primer Plus\"tempcppedcuwnw

without result

// forc99.c --新的C99块的规则
#include <stdio.h>
int main()
{
	int n = 8;
	
	printf("   Initially, n = %d at %p\n", n, &n);
	for(n=1; n<3; n++)
		printf("	loop 1: n = %d at %p\n", n, &n);
	printf("After loop 1, n = %d at %p\n", n, &n);
	for(n=1; n<3; n++)
	{
		printf(" loop 2 index n = %d at %p\n", n, &n);
		int n = 6;
		printf("	loop 2: n = %d at %p\n", n, &n);
		n++;
	}	
	printf("After loop 2, n = %d at %p\n", n, &n);
	
	return 0;
} 

[Running] cd "c:\Users\steeling\Desktop\临时文件\2017年4月24日——C Primer Plus\第十二章\" && gcc forc99.c -o forc99 && "c:\Users\steeling\Desktop\临时文件\2017年4月24日——C Primer Plus\第十二章\"forc99
   Initially, n = 8 at 00000000009FFE4C
	loop 1: n = 1 at 00000000009FFE4C
	loop 1: n = 2 at 00000000009FFE4C
After loop 1, n = 3 at 00000000009FFE4C
 loop 2 index n = 1 at 00000000009FFE4C
	loop 2: n = 6 at 00000000009FFE48
 loop 2 index n = 2 at 00000000009FFE4C
	loop 2: n = 6 at 00000000009FFE48
After loop 2, n = 3 at 00000000009FFE4C

**Comment by LiFanjieSeizeTheDay** [comment]
How to give the value for a parameter in the code

**Comment by formulahendry** [comment]
For input support, please refer to #91 .
