### ISSUE TITLE
run the file not the selection

### ISSUE THREAD

**Issue by monkeysuffrage** [formulahendry/vscode-code-runner#156]
Can we have a command to run the whole file and not just the selection? Sometimes I will accidentally have something selected and I never want it to do just the selection.

**Comment by formulahendry** [comment]
Use below setting (`File`->`Preference`->`Settings`) to ignore selection:
```json
{
    "code-runner.ignoreSelection": true
}
```

**Comment by monkeysuffrage** [comment]
Awesome.
Thanks for this.
