### ISSUE TITLE
when code isn't select output is empty

### ISSUE THREAD

**Issue by holen1210** [formulahendry/vscode-code-runner#157]
* when code isn't been selected output is Empty
![8bb8c6f4-d0b2-45f8-b5c9-f84cd6d93307](https://user-images.githubusercontent.com/20247164/28936499-856c9ad4-78ba-11e7-914f-3fd70d99f027.png)

* when code is been selected output is Well
![51e438af-44c3-4838-bfc3-271d3394630e](https://user-images.githubusercontent.com/20247164/28936509-89742ffc-78ba-11e7-968f-525129b37f5a.png)

**Comment by formulahendry** [comment]
Could you try below things?

* Run Node.js or other language to see if there is similar issue
* Run python with `python3 -u ***.py`
* Use setting `"code-runner.runInTerminal": true` to run code in Terminal

**Comment by holen1210** [comment]
Sooooo Stupid!
I forget  save it before  I run it

**Comment by formulahendry** [comment]
Closing then..

**Comment by formulahendry** [comment]
You could config `"code-runner.saveFileBeforeRun": true` to save the current file before running.
