### ISSUE TITLE
Mac os VSCode always tried to use /bin/sh to start ts-node, but there is no any (only in zsh). Can there be option to choose what shell to use for execution?

### ISSUE THREAD

**Issue by idchlife** [formulahendry/vscode-code-runner#158]

**Comment by formulahendry** [comment]
You could below setting (`File`->`Preference`->`Settings`) to run code in Integrated Terminal:
```json
{
    "code-runner.runInTerminal": true
}
```
Then, follow the [doc](https://code.visualstudio.com/docs/editor/integrated-terminal#_configuration) to set zsh as Integrated Terminal of VS Code
