### ISSUE TITLE
User input causes program to hang.

### ISSUE THREAD

**Issue by haz-q** [formulahendry/vscode-code-runner#16]
Hello,

I'm a total noob at programming, so I appreciate your help and patience. I've been searching around for the best IDE (or IDE-like) setting to learn Python and I think I'd like to settle on VS Code.  I'm trying to run a simple program that prompts the user for input, but when I do, the program just hangs indefinitely until I terminate it. I can't input the string and complete the program run. What am I missing? I'm running ht latest version of Python 3.5x. Thanks!
![screenshot](https://cloud.githubusercontent.com/assets/21263827/18009412/c0ad7e1c-6b71-11e6-929d-5f2eca3e011b.PNG)

**Comment by formulahendry** [comment]
Hi @haz-q , it is due to the limit of the Code Runner extension. It does not support to read data from input for now, thus it hangs. I will investigate to support the stdin for this extension.

**Comment by formulahendry** [comment]
@haz-q , I have added support to read user input. Please install the latest version, set `code-runner.runInTerminal` as `true` and then have a try:
```json
{
    "code-runner.runInTerminal": true
}
```
