### ISSUE TITLE
/bin/sh: ts-node: command not found

### ISSUE THREAD

**Issue by mrdulin** [formulahendry/vscode-code-runner#162]
I have already install `ts-node`.

I did not do any setting up.

**Comment by formulahendry** [comment]
Is ts-node in your PATH environment variable, and have you restarted VS Code?

**Comment by mrdulin** [comment]
@formulahendry `ts-node` in `node_modules/.bin/ts-node`. And, I  use `command + q` quit vscode and restarted. The problem still there

**Comment by mrdulin** [comment]
@formulahendry `ts-node` in `node_modules/.bin/ts-node`. And, I  use `command + q` quit vscode and restarted. The problem still there

**Comment by formulahendry** [comment]
You need either put ts-node in your PATH environment variable, or set the path of ts-node in `File`->`Preference`->`Settings`:
```json
"code-runner.executorMap": {
    "typescript": "node_modules/.bin/ts-node"
}
```

**Comment by mrdulin** [comment]
@formulahendry 

1. I don't want to use `ts-node` global installed.
2. expect `code-runner` look up `ts-node` locally

**Comment by formulahendry** [comment]
Since Code Runner supports several languages and user is able to customize the path, we will not support this feature. You could udpate `executorMap` per your need.

**Comment by HaoyangFan** [comment]
is it possible for code runner supports the use of `npx` which automatically loads the binaries from local node_modules, and bundle with the locally installed `ts-node` automatically so that we don't need to add anything to the user setting/ workspace setting?

**Comment by mrdulin** [comment]
My solution is: 

```json
 "code-runner.executorMap": {
    "typescript": "node -r ts-node/register"
  }
```

I think it's better than the solution @formulahendry provide. You don't need care about the path of `${whatever PATH}/node_modules/.bin/ts-node`

**Comment by yankfy** [comment]
you must install ts-node global, u can try again

**Comment by manuelduarte077** [comment]
npm install -g ts-node

**Comment by dbehmoaras** [comment]
Late to the game, but @mrdulin 's solution worked for me. Installing ts-node globally is not a realistic option when collaborating with other devs.

**Comment by zq0904** [comment]
> 



> My solution is:
> 
> ```json
>  "code-runner.executorMap": {
>     "typescript": "node -r ts-node/register",
>     "javascript": "node"
>   }
> ```
> 
> I think it's better than the solution @formulahendry provided. You don't need care about the path like this: `${whatever PATH}/node_modules/.bin/ts-node`. Because the `PATH` often changes.

However, there is still no support for TS-Node that is not installed in the project root such as monorepo project
My expectation is that NPX ts-Node will look for the address in the executable file directory

**Comment by AkbarHusein** [comment]
My solution is:
In code-runner.executorMap, check if 'typescript:ts-node' is not there then add it
` "code-runner.executorMap": {
    "typescript": "ts-node",
    "javascript": "node"
  }`

**Comment by atejap05** [comment]
npm install -g tsx

and then:

"code-runner.executorMap": {
"typescript": "tsx",
"javascript": "node"
}

**Comment by Edamijueda** [comment]
After battling with this error for 3 hours. What worked for me was that I had to restart my computer.
After installing 'code runner' vs code extension I get this error when I try to run my typescript code using 'code runner'.  I used ts-node to do  "ts-node fileName.ts" in terminal this run my file.ts, but using 'code runner' does not work for me.  The error persist even when I restart my vs code. What solve it for me was restarting my mac computer. So I guess what happened is that code runner expect a pc reboot before it can identify ts-node commands.

**Comment by falconchen** [comment]
it works for node installed by nvm :

``` json
"code-runner.executorMap": {
     "typescript": "`which node` -r ts-node/register ",

}
```

**Comment by dimsumc** [comment]
The solution I found is to start VSCode (e.g., code {project path}) from the terminal instead of using the shortcut. If I start VSCode from the shortcut, Code Runner reports “ts-node not found,” but this issue doesn’t occur when I start it from the terminal.
