### ISSUE TITLE
Java:     编译没报GBK的错误，但输出的中文就是乱码了

### ISSUE THREAD

**Issue by xiaoTangtao** [formulahendry/vscode-code-runner#163]
![image](https://user-images.githubusercontent.com/28929130/29491428-8ef9f098-858e-11e7-9b30-dff3927d230b.png)

**Comment by xiaoTangtao** [comment]
重新打开一下软件居然就可以了，郁闷，为何看上去如此偶然

**Comment by formulahendry** [comment]
重启大法好
