### ISSUE TITLE
Keeps running old code, either code is not updating or compiling new code

### ISSUE THREAD

**Issue by Jamisco** [formulahendry/vscode-code-runner#165]
say I had a simply statement
System.out.println("hi");  

at first it would run that code and print hi but say I were to change that statement to

System.out.println("hello");  

when I run the code, output will still show hi

**Comment by formulahendry** [comment]
Have you saved the code?

**Comment by Jamisco** [comment]
so it must be saved before being ran?

**Comment by Jamisco** [comment]
yup it must be saved, I see

**Comment by Jamisco** [comment]
thanks for pointing that out

**Comment by formulahendry** [comment]
Of course, but you could go to `File`->`Preference`->`Settings` to set config as below:
```json
"code-runner.saveFileBeforeRun": true
```
Then the code will be saved before running.

**Comment by Jamisco** [comment]
ok, thanks you sir
