### ISSUE TITLE
Julia support

### ISSUE THREAD

**Issue by mjaniec2013** [formulahendry/vscode-code-runner#168]
Any chance Julia (julialang.org) support will be added?

Thanks in advance.

**Comment by formulahendry** [comment]
I think it is already supported: https://github.com/formulahendry/vscode-code-runner/blob/master/package.json#L128

**Comment by mjaniec2013** [comment]
@formulahendry 

Thank you! Julia was not mentioned in the extension's description.

**Comment by formulahendry** [comment]
You may miss that. 😃 
![image](https://user-images.githubusercontent.com/1050213/29705174-717c2f8e-89af-11e7-9e36-8eb81e25761c.png)

**Comment by mjaniec2013** [comment]
@formulahendry 

Right again. Seems I'm blind ;)

**Comment by mjaniec2013** [comment]
@formulahendry 

Nevertheless, great extension. Will test it with a couple more languages, like R and Python.
