### ISSUE TITLE
User input not working

### ISSUE THREAD

**Issue by LeNDuyA** [formulahendry/vscode-code-runner#170]
I use C and right now I don't know how I can input into the running program. Even this simple piece of code won't run correctly:
```
#include <stdio.h>

int main() {

    printf("enter number: ");
    int i;
    scanf("%d", &i);
    printf("%d\n", i);

    return 0;
}
```

Basically gets stucked at: `[Running] cd "/home/lenduya/Downloads/" && g++ hello.c -std=c++11 -g -pedantic -Wall -Wshadow -o hello.out && "/home/lenduya/Downloads/"hello.out`

and I have to terminate it manually.

Also, how do I run my programs with aguments? For example `./hello.out 13`?

**Comment by formulahendry** [comment]
For input, you could refer to #91 
For aguments, you could update `code-runner.executorMap`, refer to https://github.com/formulahendry/vscode-code-runner#configuration
