### ISSUE TITLE
No Time To Input 

### ISSUE THREAD

**Issue by Yeba** [formulahendry/vscode-code-runner#172]
```
#include<stdio.h>
int main(){
    getchar();
    printf("1");
    getchar();
    printf("2");
    getchar();
    return 0;
}
```
I did "code-runner.runInTerminal": true 
It should have time for me to input char, but it immediately print “12”。
![1](https://user-images.githubusercontent.com/18240596/30000107-9dbace40-9092-11e7-88df-1ebc94b97e9b.png)

**Comment by Yeba** [comment]
as well as 

![1](https://user-images.githubusercontent.com/18240596/30000128-526ea5f0-9093-11e7-93e1-4e8fe65a997e.png)

**Comment by formulahendry** [comment]
What if you run the same code in CMD of Windows?

**Comment by Yeba** [comment]
it works good in cmd

**Comment by formulahendry** [comment]
What about PowerShell?

**Comment by Yeba** [comment]
It works good in powershellStep 。
What's more, step by step，it works well.
![1](https://user-images.githubusercontent.com/18240596/30000794-93010a06-90aa-11e7-8141-d77af5c2fbd5.png)

**Comment by Yeba** [comment]
哦，是powershell 的锅。C:\TDM-GCC-64\bin\gcc.exe c.c -o c.exe | ./c.exe 这句命令有问题。
你的默认命令在我的电脑行不通，便用这句话代替了。

**Comment by Yeba** [comment]
solved，   `C:\TDM-GCC-64\bin\gcc.exe c.c -o c.exe ； ./c.exe ` will be OK。

**Comment by Yeba** [comment]
I suggest than you should have different solution in different system.
For example，TDM-GCC on Windows can use this:
`"c": "C:\\TDM-GCC-64\\bin\\gcc.exe $fileName -o $fileNameWithoutExt.exe ; ./$fileNameWithoutExt.exe",`

**Comment by Yeba** [comment]
What's more, why not save the code before we run ti?

**Comment by formulahendry** [comment]
For saving file, if you have read the README, you could set `"code-runner.saveFileBeforeRun": true`
For `&&`, it is already handled if you are using PowerShell. It will be replaced as below:
![image](https://user-images.githubusercontent.com/1050213/30001401-88c488b4-90bf-11e7-8205-d879c286f124.png)

**Comment by formulahendry** [comment]
Did you try keep the `&&` in original command?

**Comment by Yeba** [comment]
oh, my lack knowledge about this. Yes, you are right,  `&&` is better.
