### ISSUE TITLE
我是Java初学者，中文乱码请问怎么解决？

### ISSUE THREAD

**Issue by ZoolYe** [formulahendry/vscode-code-runner#175]
![qq 20170915141421](https://user-images.githubusercontent.com/7373629/30468867-3578b6c0-9a20-11e7-8772-9cf803eb2ad8.png)

还有想问一个问题，二进制.class文件能不能单独放在另外一个文件夹中，或者删除，我也看了其他者的提问，但是无奈英文不好看不懂，希望作者能照顾一下中国人，谢谢！

**Comment by formulahendry** [comment]
对于中文乱码，可以进行如下设置：
``` json
{
    "code-runner.runInTerminal": true
}
```
对.class文件的输出目录，可以更改以下设置：
```json
{
    "code-runner.executorMap": {
        "java": "cd $dir && javac -d <any_folder_path> $fileName && java $fileNameWithoutExt"
    }
}
```

**Comment by ZoolYe** [comment]
我要设置的目录是D:\ZOOL\Study\bin  ，要怎么做？ 我更改了设置出现拒绝访问

**Comment by formulahendry** [comment]
截图？

**Comment by ZoolYe** [comment]
![qq 20170915144850](https://user-images.githubusercontent.com/7373629/30469861-08769598-9a25-11e7-9d39-86aa7eda714e.png)

**Comment by ZoolYe** [comment]
不集成终端的情况下，没办法支持中文吗？

**Comment by formulahendry** [comment]
后面的路径也要改：
```json
"java": "cd $dir && javac -d <any_folder_path> $fileName && java <any_folder_path>\\$fileNameWithoutExt"
```
或者
```json
"java": "cd <any_output_folder_path> && javac $fullFileName && java $fileNameWithoutExt",
```

支持中文目前只有这个方法。

**Comment by ZoolYe** [comment]
我的设置有问题？
"java": "cd $dir && javac -d D:\\ZOOL\\Study\\bin $fileName && java D:\\ZOOL\\Study\\bin $fileNameWithoutExt",

**Comment by formulahendry** [comment]
`"java": "cd $dir && javac -d D:\\ZOOL\\Study\\bin $fileName && java D:\\ZOOL\\Study\\bin\\ $fileNameWithoutExt"`

**Comment by ZoolYe** [comment]
跟你的一样啊，那边目录是\\，复制过来就\了，还是报错。

**Comment by ZoolYe** [comment]
cmd里不会报错

**Comment by formulahendry** [comment]
请截图

**Comment by ZoolYe** [comment]
![01](https://user-images.githubusercontent.com/7373629/30470954-61eee068-9a29-11e7-9d12-953868540d73.jpg)
![02](https://user-images.githubusercontent.com/7373629/30470956-61f204c8-9a29-11e7-89eb-484dc26db7bb.jpg)
![03](https://user-images.githubusercontent.com/7373629/30470955-61f14d6c-9a29-11e7-911e-433f6e388fa7.jpg)

**Comment by formulahendry** [comment]
`D:\\ZOOL\\Study\\bin\\$fileNameWithoutExt` 你后面多了个空格啊。
建议你好好学习下Java编译执行的各个命令参数。我并不写Java，也都是Google的。

**Comment by ZoolYe** [comment]
正确的配置是这样的，跟空格无关，也没有空格。
"java": "cd $dir && javac -d D:\\ZOOL\\Study\\bin $fileName && java -cp D:\\ZOOL\\Study\\bin\\$fileNameWithoutExt"
