### ISSUE TITLE
Can't run Go programs

### ISSUE THREAD

**Issue by nikitavoloboev** [formulahendry/vscode-code-runner#176]
I get this when trying to run them in Output : 

```Bash
[Running] go run "/Users/nikivi/learning/go-play/main.go"
# command-line-arguments
flag provided but not defined: -goversion
usage: compile [options] file.go...
  -%	debug non-static initializers
  -+	compiling runtime
  -A	for bootstrapping, allow 'any' type
  -B	disable bounds checking
  -D path
    	set relative path for local imports
```

But running it in terminal from VS Code works : 

![2017-09-16 at 23 01](https://user-images.githubusercontent.com/6391776/30515984-0622d414-9b33-11e7-8fe4-fa30c41d7c1a.png)

Thank you for any help.

**Comment by nikitavoloboev** [comment]
Updating Go fixed it 🙂

**Comment by JsOoO** [comment]
Sorry, my go version is "go1.9.2 darwin/amd64", but I still can not run go programs...
