### ISSUE TITLE
Save the file before running

### ISSUE THREAD

**Issue by sadbakh** [formulahendry/vscode-code-runner#178]
I expect that when I press the run button the source file is saved first and the code runs. But this is not working properly in this extension.
I tried to change the vs-code setting to "files.autoSave": "onFocusChange" as a solution but this way the code is run first and the file saved afterward!

Visual Studio Version 1.16.1
.run version 0.7.1
Linux 64-bit

**Comment by formulahendry** [comment]
Hi @sadbakh , you could use below settings:
```json
{
    "code-runner.saveFileBeforeRun": true
}
``` 
For more settings, you could refer to https://github.com/formulahendry/vscode-code-runner#configuration

**Comment by weinand** [comment]
For "Code Runner" users that don't have "auto saved" enabled it will be very confusing that there latest edits are not used when running a script.
Wouldn't it make sense to check for this case and ask the user whether they want to enable the `"code-runner.saveFileBeforeRun"` setting?
