### ISSUE TITLE
出现了乱码

### ISSUE THREAD

**Issue by wangpingyue** [formulahendry/vscode-code-runner#179]
![default](https://user-images.githubusercontent.com/30410455/30742761-38079692-9fcd-11e7-94a1-d7ba0df79987.png)
运行时出现这个，能想办法解决吗？

**Comment by wangpingyue** [comment]
用的win10系统

**Comment by wangpingyue** [comment]
听人说和环境变量有关，请问如何设置

**Comment by formulahendry** [comment]
You could use below setting to avoid messy code:
``` json
{
    "code-runner.runInTerminal": true
}
```
