### ISSUE TITLE
ReferenceError: window is not defined

### ISSUE THREAD

**Issue by Dan503** [formulahendry/vscode-code-runner#180]
`window` is undefined in code-runner. This is native code in browsers so it should be defined in code-runner.

I realise it doesn't have a browser window to reference but it could maybe use the editor window as a reference point instead. If that's not possible then using a generic fixed screen size for the sake of testing would be good enough to work with.

`window` should have all (or at least as many as possible) of the same values that can be found in a standard unmodified window object found in a modern browser.

**Comment by formulahendry** [comment]
Are you running JavaScript Code using Node.js?

**Comment by Dan503** [comment]
This was for code that was to be used in browser. Not for Node.js.

I might have code-runner set up to run off node which wouldn't have a window object (I'm just using default settings). Is there a certain way I should configure code-runner to allow access to a defined window object?

**Comment by zikalino** [comment]
i think it would be pretty tough to implement window in node.js ;-)

**Comment by Dan503** [comment]
Maybe utilise [Phantom.js](http://phantomjs.org/)?

**Comment by Dan503** [comment]
Or only define the static values in `window` like `window.innerWidth`?

**Comment by formulahendry** [comment]
By default, Code Runner use Node.js to run JavaScript code, while Node.js not support `window`. You could choose other executor as you like.

**Comment by eesati** [comment]
Use global instead
