### ISSUE TITLE
Windows 中使用终端时的路径问题

### ISSUE THREAD

**Issue by eelord** [formulahendry/vscode-code-runner#181]
操作系统：Windows
终端：git bash
Windows 下终端的路径中的反斜杠 `\` 应写成双反斜杠 `\\` ，参见用户设置中的 `terminal.external.windowsExec` 和 `terminal.integrated.shell.windows`

![_20170926200113](https://user-images.githubusercontent.com/9635792/30860660-7b0c2c5c-a2fa-11e7-8e55-a96b6a3d95c3.png)

**Comment by formulahendry** [comment]
Interesting bug. This only happens when you run a file which is in the root folder of a drive on Windows.

**Comment by formulahendry** [comment]
Seems that is not the root cause.
You are using bash on Windows? What bash are you using?

**Comment by formulahendry** [comment]
For Git Bash, you could use below settings to handle the file path in Git Bash:
```
"code-runner.terminalRoot": "/"
```
Let me know whether it works for you.

**Comment by eelord** [comment]
@formulahendry It works! Thank you.
