### ISSUE TITLE
New $FileDrive Supported customized parameter

### ISSUE THREAD

**Issue by cycle4passion** [formulahendry/vscode-code-runner#182]
I run my test code and Autohotkey language executable off a USB drive. The drive letter changes depending on the computer it is plugged into. 

I am requesting a new $FileDrive custom parameter, in order to define  the drive letter from the file being run, and this I can use it to find/execute the language executable on the same drive.

Example:
Try to run test.ahk, whose path is F:\AHK\Testing\test.ahk
autohotkey.exe is at F:\AHK\AutoHotKey Portable\Autohotkey.exe

$FileDrive would give me "F:"
and I could do "\"$FileDrive\AHK\AutoHotKey Portable\Autohotkey.exe\""

**Comment by formulahendry** [comment]
Hi @cycle4passion , I am thinking this request may be to specific. And this seems only useful for Windows. You could simply update the config in each computer to specify the path of `Autohotkey.exe`.
Keep this issue open for discussion.

**Comment by cycle4passion** [comment]
I agree it's specific L, but I am also running vscode portably off the USB drive so the coderunner user preferences file would have to be updated every time I plug into a new computer.

**Comment by formulahendry** [comment]
@cycle4passion , a new `$driveLetter` is added per your request, please install the latest version and have a try.
