### ISSUE TITLE
Input issue in C++ (.cpp files)

### ISSUE THREAD

**Issue by Kkim50** [formulahendry/vscode-code-runner#187]
Hello! I am able to get input working for the most part. I only seem to be having an issue when reading inputs through a loop because it does not prompt the user for any value. 
I'm on the most updated version of VS Code and am on Windows 10. 

For example,` std::cin >> value;` works great and prompts the user for some value.
However, something like `while(std::cin >> value)` gives no prompt and  no output message. 

I tried looking through forums and through the issues page but I could not find anything other than to change these two settings (which I have done already):
"code-runner.runInTerminal": true,
"code-runner.ignoreSelection": true

I'd appreciate any help, thank you.

**Comment by formulahendry** [comment]
Have you tried running same code in PowerShell, CMD or other IDE? Does it have the same issue?

**Comment by Kkim50** [comment]
Ahh tried it in Mingw64 and it seems only the .exe file executes correctly! Simply compiling the cpp file does not work. Thank you so much for the quick response, and sorry for the bother! 👍

**Comment by formulahendry** [comment]
Good to know. Closing this then.
