### ISSUE TITLE
Quick rerun of code where default language is already set

### ISSUE THREAD

**Issue by MJCD** [formulahendry/vscode-code-runner#189]
**Code Runner 0.7.2**
Visual Studio Code 1.17.0
Node 7.9.0
Windows 10 Home Insider Preview 1703/16278.1000

**Notes:**
Have already set "code-runner.defaultLanguage": "javascript"

**Reproduce Behavior:**
Write code with a syntax error and save->
Run code->Stop code->
Fix syntax error and save->
Run code->
[ERROR]
=Wait some time=
After this it will sometimes run fine, and sometimes get the error I presume from the old syntax error source? Not 100% sure

**Issue:**
![screenshot_1](https://user-images.githubusercontent.com/5105009/31378105-c8570c4c-addc-11e7-9af6-e50e5b9a57f3.png)

**Source:**
![screenshot_2](https://user-images.githubusercontent.com/5105009/31378137-debdeaaa-addc-11e7-9820-08567088510f.png)

**Suspected Fix**
I suspect that before the extension reports the code has ended this temporary file needs to be unlinked (deleted) ready for a clean restart.  I suspect at the present time the output that the code has ended is done before this happens.

Ideally the existence of this temp file should act as a lock to prevent code re-run (perhaps in the same source that currently shows "Code is already running" which will also prevent it erroring.

**Comment by formulahendry** [comment]
`tempCodeRunnerFile.***` indicates that you have selected code snippet. I think you are selecting part of code by accident.
To avoid that, you could use this settings: `"code-runner. ignoreSelection": true`

**Comment by MJCD** [comment]
That resolves it nicely and was likely what was happening. The selection may not always be visible to the user (say they are scrolled down or whatever) so it might be an idea to add two separate shortcuts instead of it being context sensitive to if you have something selected or not.

Just a thought! Thanks for your hard work <3
