### ISSUE TITLE
ABOUT SET PYTHON PATH

### ISSUE THREAD

**Issue by zhaohaixin** [formulahendry/vscode-code-runner#19]
i set the path of python like this:
    "code-runner.executorMap": {
        "python": "C:\Program Files\Python35\python.exe"
    }
 but run faid：
[Running] C:\Program Files\Python35\python.exe "c:\Users\Administrator\Desktop\中文\temp-fuopntmsyc.py"
'C:\Program' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���

[Done] exited with code=1 in 0.045 seconds

what can i do ,thank you!

**Comment by formulahendry** [comment]
"c:\Users\Administrator\Desktop\中文\temp-fuopntmsyc.py" python文件的路径里面有中文字符，你试试看没有中文路径的

**Comment by formulahendry** [comment]
应该是Python.exe的路径有空格，改成下面的试试
"code-runner.executorMap": 
{ 
"python": "\"C:\\Program Files\\Python35\\python.exe\"" 
}

**Comment by zhaohaixin** [comment]
换成英文路径 文件名后 还是老问题，更改path路径 程序读不出python地址。我在run内只配置了python 路径 其他没有配置过 按你们提供的方法 右键点击代码 运行就出现了这些错误。

发自我的 iPhone

**Comment by formulahendry** [comment]
Solution#1:
你把python 路径加到环境变量里，就不用任何配置了

Solution#2:
你试下把[Running]后面的命令放到cmd去run，看看有没有一样的问题:
`"C:\Program Files\Python35\python.exe" "c:\Users\Administrator\Desktop\中文\*******.py"`

还有，你`"C:\Program Files\Python35\python.exe"`加双引号了吗？当中有空格的话，肯定会fail

**Comment by zhaohaixin** [comment]
谢谢 我有添加系统环境变量 所以没必要再去修改插件上的python路径 这样就可以run了。 还有个问题 我在使用input后 在输出里面怎么输入数据呢？

发自我的 iPhone

**Comment by formulahendry** [comment]
Input目前还不支持   现在有issue #17 在track

**Comment by formulahendry** [comment]
@zhaohaixin , I have added support to read user input now. Please install the latest version, and set `code-runner.runInTerminal` as `true` and then have a try:
```json
{
    "code-runner.runInTerminal": true
}
```

**Comment by zhaohaixin** [comment]
Thanks,that is awesome 

发自我的 iPhone
