### ISSUE TITLE
korean character problem

### ISSUE THREAD

**Issue by produce102** [formulahendry/vscode-code-runner#190]
https://i.imgur.com/QXut64V.png

Is there any way to resolve it?

**Comment by formulahendry** [comment]
You could refer to https://github.com/formulahendry/vscode-code-runner/issues/25#issuecomment-263170907 for solution

**Comment by produce102** [comment]
![002712](https://user-images.githubusercontent.com/31151596/31532672-a2b18c2a-b029-11e7-9a03-9ed207093fbf.png)
![002713](https://user-images.githubusercontent.com/31151596/31532673-a468dfb4-b029-11e7-8e56-43572e948802.png)

thank you! it works!
