### ISSUE TITLE
Code left running not registering after vscode restart

### ISSUE THREAD

**Issue by MJCD** [formulahendry/vscode-code-runner#191]
**Reproduce**
Start code running
Close vscode without terminating running code
Open vscode
Trying to run program will give port in use error as app still running
Trying to Stop Code will do nothing as nothing has been started that it knows of

**Expected behavior**
Runtimes started via code runner would be force terminated when all/the vscode instance(s) are closed OR
That runtimes created are tracked as to be able to stop them from within vscode after restarting.

**Comment by formulahendry** [comment]
Hi @MJCD , this issue has been fixed: It will stop running code when VS Code is closed. Please install the latest version and have a try.
