### ISSUE TITLE
Problems on using Code Runner 

### ISSUE THREAD

**Issue by Saluxlee** [formulahendry/vscode-code-runner#193]
Hello! I have some problems on using the Runner.
I wrote something to test it.
![12](https://user-images.githubusercontent.com/32934320/31778292-d8943f60-b522-11e7-9546-1c658d3e5bd7.png)
But the input is messy code and it showed that 
![11](https://user-images.githubusercontent.com/32934320/31778322-ebf19f1c-b522-11e7-987b-870231edb888.png)
I've found that someone has the same problem. They clicked the bulb next to the head file and set the path like this.
![13](https://user-images.githubusercontent.com/32934320/31778886-5e89e4ac-b524-11e7-90df-29f2d17c6ead.png)
However, there's still the same question. the terminal shows 
![20](https://user-images.githubusercontent.com/32934320/31778920-7ae3648e-b524-11e7-95b4-be2fbd720b09.png)
Someone had the same question as me, you told him to set the executormap from 
![15](https://user-images.githubusercontent.com/32934320/31779935-f02d3268-b526-11e7-863d-c7972ea41ac7.png)
to 
![21](https://user-images.githubusercontent.com/32934320/31779938-f53a21bc-b526-11e7-9c80-cbb59536ef46.png)
and restart the VSC. But it didn't work on my computer. It shows 
![14](https://user-images.githubusercontent.com/32934320/31779947-fb659f26-b526-11e7-948e-ecc2d90846fe.png)
By the way, I had already set the terminal like this 
![16](https://user-images.githubusercontent.com/32934320/31779957-ffaf9e9c-b526-11e7-9034-01e001448cae.png)
And this is the environment path on my computer 
![17](https://user-images.githubusercontent.com/32934320/31779961-0510945e-b527-11e7-97b2-70211fb7eabd.png)
![18](https://user-images.githubusercontent.com/32934320/31779969-0a2cbdfa-b527-11e7-803f-561da6e3a7a9.png)
And my version of VSC.
![19](https://user-images.githubusercontent.com/32934320/31779979-1035d394-b527-11e7-8592-48fc7f228865.png)
And extensions on my VSC are C/C++, C#, c++ intellisense, power mode and VSC icons.
Sorry to bother you, but I spent a whole day dealing with it but failed. Could you help me?

**Comment by Saluxlee** [comment]
OK. I have solved this problems. The extension Code Runner can't work while the extension C/C++ is running. After unistalling the C/C++, the runner works. Thank you for this amazing extension.

**Comment by formulahendry** [comment]
Good to know it is working now. Closing this then. Though it is a little strange, C/C++ extension should not have any impact on Code Runner. 😕
