### ISSUE TITLE
'language' is not recognized as an internal or external command, operable program or batch file

### ISSUE THREAD

**Issue by davie890** [formulahendry/vscode-code-runner#194]
When I tried to run my ocaml code or a simple print line for python, I get the error stated:
"'language' is not recognized as an internal or external command, operable program or batch file".
What does this mean and how can I fix it?
![runbug](https://user-images.githubusercontent.com/14946197/31846719-1700ed60-b5c4-11e7-9523-e1156be4d40b.png)

**Comment by formulahendry** [comment]
Hi @davie890 , you need to install Python, and put the folder path of python.exe into PATH environment variable.

**Comment by davie890** [comment]
How do I go about doing that, in the details part of your extension in vsCode it says "you could also add entry into code-runner.executorMap". Where do I find that to add the path, and is it possible to add the path if I only installed python/ocaml through the vsCode extension?

**Comment by formulahendry** [comment]
> Where do I find that to add the path

Go to `File`->`Preference`->`Settings`

> is it possible to add the path if I only installed python/ocaml through the vsCode extension?

You need to install Python from https://www.python.org/downloads/, not the Python extension
