### ISSUE TITLE
run code hotkey not working

### ISSUE THREAD

**Issue by jessekrubin** [formulahendry/vscode-code-runner#196]
idk why but the hot key combo on my windows comp with vscode and code runner stopped working, though the play button (not the debug play button) in the top right corner affiliated with the extension (and has the 'same' hot key combo) works. 

EDIT:
I usually get a VScode message when I use the hot key combo that reads 'INFO: Code language not supported or defined.'

**Comment by mmsaffari** [comment]
Starting from today, **Ctrl+Alt+N** doesn't work with an "INFO" message of "Code language not supported or defined."; however, using the play button or pressing **Ctrl+Alt+J** and selecting python, runs the code.
I tried settings like 
```
    "code-runner.executorMapByFileExtension": {
        ".py":"python"
    },
    "code-runner.languageIdToFileExtensionMap": {
        "python":".py"
    },
```
too, with no success.

**Comment by formulahendry** [comment]
Hi @jessekrubin , @mmsaffari , sorry for the issue. I have published a new version to fix this. Please have a try.

**Comment by mmsaffari** [comment]
Hello @formulahendry and thank you very much for this very quick fix.  
It's working just fine now :)

**Comment by adonis07** [comment]
Actually that happened to me today, removing the package "streetsidesoftware.code-spell-checker" the behavior revert back to normal. I don't know if it's a bug with the package or a conflict

**Comment by formulahendry** [comment]
@adonis07 , it should be the code bug of Code Runner I released several hours ago. Now it has been fixed.

**Comment by jessekrubin** [comment]
@mmsaffari 
IM NOT GOING CRAZY!?
I tried those settings as well. Nothing worked.

**Comment by bobstheman** [comment]
ctrl + alt + n does not run code... error ---> code is already running!
 and user can not input data get error ---> cannot edit in read only editor

**Comment by jaynj908** [comment]
It was working fine now its not. I did not install any extensions just running code.

**Comment by nottnottloop** [comment]
Try turning on Numlock, this worked for me. I have zero idea why this works
