### ISSUE TITLE
[Python]UnicodeEncodeError: 'ascii' codec can't encode characters in position 9-10: ordinal not in range(128)

### ISSUE THREAD

**Issue by iLibra** [formulahendry/vscode-code-runner#197]
I'm using vscode-code-runner on MACOS with python2.7
if I print some Chinese Char to output window. it will meet this error:
UnicodeEncodeError: 'ascii' codec can't encode characters in position 9-10: ordinal not in range(128)

I have tried to submit an issue for VSCode, however VSCode author thinks it's code-runner plugin issue.
because code-runner runs python with not UTF-8 but ascii.
if I run the python in Terminal, everything goes well.

**Comment by formulahendry** [comment]
Hi @iLibra , you could try the solution in https://github.com/formulahendry/vscode-code-runner/issues/25#issuecomment-263170907

**Comment by iLibra** [comment]
@formulahendry ,hi , thanks, yes ,the solution in #25 works. before I submit this issue, I already use that method as a workaround, but I hope it  can be fixed by root cause. otherwise every user must spend a lot of time to find this solution. and you also should spend a lot of time to explain it one by one.

**Comment by PatrickRoot** [comment]
Mac and python3.6.
It did't work when I use  https://github.com/formulahendry/vscode-code-runner/issues/25#issuecomment-263170907,
but it finally works when I set "code-runner.runInTerminal" as https://github.com/formulahendry/vscode-code-runner/issues/25#issuecomment-329669224

**Comment by leonardon473** [comment]
In Terminal run `export LC_ALL='en_US.utf8'`
