### ISSUE TITLE
It doesn't show anything in ouputbox except command

### ISSUE THREAD

**Issue by lflys** [formulahendry/vscode-code-runner#198]
When I press the run code button, the output box only shows a command:
![workspace 1_001](https://user-images.githubusercontent.com/32433404/32099102-90172dc2-bb41-11e7-8b50-70a9a590f0cd.png)

Press again:
![workspace 1_002](https://user-images.githubusercontent.com/32433404/32099239-197fa846-bb42-11e7-81c2-5e2b905e9861.png)

However, if I paste this command into the terminal, it can work.
![workspace 1_003](https://user-images.githubusercontent.com/32433404/32099224-0ddaa3f6-bb42-11e7-98ce-bc959a51b8d0.png)

Thanks in advance.

**Comment by formulahendry** [comment]
For quick workaround, you could use below setting (`File`->`Preference`->`Settings`) to run code in Integrated Terminal:
```json
{
    "code-runner.runInTerminal": true
}
```
If you go to `Help` -> `Toggle Developer Tool`, do you see any error log in console tab?

**Comment by formulahendry** [comment]
Also, without `"code-runner.runInTerminal": true`, could you please disable all other extensions and try again?

**Comment by lflys** [comment]
The problem has been solved by changing the setting!
Actually, I'm a college student and a beginner in this field.It's such a simple problem but still troubles me.
Thanks a lot!  ：）

**Comment by formulahendry** [comment]
Good to know. Closing this issue then.
