### ISSUE TITLE
code-runner.cwd support variables

### ISSUE THREAD

**Issue by SailorMax** [formulahendry/vscode-code-runner#20]
Can you add support variables like ${fileDirname} for "Set the working directory" setting?
I need exec scripts from local directory.

thank you.

**Comment by formulahendry** [comment]
Currently, the cwd will be set as root folder opened in VS code. How about add a config entry to determine to use root folder or folder of current running file?

**Comment by SailorMax** [comment]
Sample?

**Comment by formulahendry** [comment]
any difference bertween filename without directory and full path of file?

**Comment by formulahendry** [comment]
Please install the visx in attached zip file (use VS Code to open the visx to install), and set `code-runner.fileDirectoryAsCwd` as true in User Settings or Workspace Settings. It will set the cwd as directory of file. Let me know whether it meets with your requirement. 😃 

[code-runner-0.2.3.zip](https://github.com/formulahendry/vscode-code-runner/files/476706/code-runner-0.2.3.zip)

**Comment by formulahendry** [comment]
Just ship the v0.2.4, you could have a try. For the filename issue, I did not see the difference between filename without directory and full path of file, so I will not change the behavior.

**Comment by SailorMax** [comment]
yes. Script can work via web in chroot directory => in command line we can try to emulate same behavior:
1. current directory = chrooted directory
2. path to file = /scripts/update_records.php, where "/" is based on current directory.

But this is little another task. Plus I made required fixes in my script for correct work even with old settings.
Anyway, thanks for modification. It can be useful.
