### ISSUE TITLE
运行Java代码输出乱码

### ISSUE THREAD

**Issue by francesha** [formulahendry/vscode-code-runner#201]
https://segmentfault.com/q/1010000011835892

**Comment by formulahendry** [comment]
Could you try below setting (`File`->`Preference`->`Settings`) to run code in Integrated Terminal:
```json
{
    "code-runner.runInTerminal": true
}
```

**Comment by francesha** [comment]
我把你说的设置项打开之后，终端提示找不到主类，我又把关掉，竟然可以正常运行了...我又把它打开，依然可以正常运行...反正就是突然就好了...I don't know why...

**Comment by formulahendry** [comment]
Magic ..
