### ISSUE TITLE
How to customize the path for complied .exe file

### ISSUE THREAD

**Issue by ruiding** [formulahendry/vscode-code-runner#203]
I want to put all .exe files in ./build folder
![2017-11-11_205235](https://user-images.githubusercontent.com/15034870/32689581-7d260c3c-c722-11e7-8786-66f7b83073f4.png)
I tried to set `"c": "cd $dir && gcc $fileName -o {workspaceRoot}/build/${fileBasenameNoExtension}.exe && {workspaceRoot}/build/${fileBasenameNoExtension}.exe"`, but it does not work
![2017-11-11_212148](https://user-images.githubusercontent.com/15034870/32689829-638a9ac8-c726-11e7-8ebd-ef738ac57c19.png)

**Comment by formulahendry** [comment]
You could refer to the **Supported customized parameters** section of https://github.com/formulahendry/vscode-code-runner#configuration

**Comment by ruiding** [comment]
I set the path to `gcc $fileName -o $dir\\build\\$fileNameWithoutExt.exe`, and it gives me an error:
![image](https://user-images.githubusercontent.com/15034870/32727585-fae1ba18-c8b7-11e7-9cb6-16a76f9f86d8.png)
I think it is the quotation that makes this error. Is there any way to remove the quotation?

**Comment by formulahendry** [comment]
Could you try `gcc $fileName -o build\\$fileNameWithoutExt.exe`?

**Comment by ruiding** [comment]
It works. Thank you
