### ISSUE TITLE
config user-settings are not used

### ISSUE THREAD

**Issue by AddictArts** [formulahendry/vscode-code-runner#204]
```
    "code-runner.executorMapByFileExtension": {
        ".mjs": "cd $dir && node -v && echo"
    }
```
If I put this in user-settings and run a .mjs file it runs it using the javascript executorMap and not the one I define.

**Comment by formulahendry** [comment]
VS Code treats `.mjs` as javascript: https://github.com/Microsoft/vscode/blob/master/extensions/javascript/package.json#L42

So you need to update the javascript section of `"code-runner.executorMap"`.
