### ISSUE TITLE
Extended $PATH not recognized

### ISSUE THREAD

**Issue by narimiran** [formulahendry/vscode-code-runner#205]
I have installed Python via Miniconda, and Nim via Choosenim. For both of these to work, their `bin` directory needs to be added to $PATH, which I did via `export PATH=xyz:$PATH` put in `.bashrc`, so now I can do in terminal `python` or `nim` and it runs fine.

In VS Code, when I try to run with `Ctrl+Alt+N`, Code Runner just searches in original $PATH (ignoring added directories), so in case of Python it runs system's Python, and in case of Nim - it can't find it.

Any idea why this happens?  
If terminal recognizes extended $PATH, shouldn't Code Runner too?

**Comment by formulahendry** [comment]
For `.bashrc` support, please use below setting (`File`->`Preference`->`Settings`) to run code in Integrated Terminal:
```json
{
    "code-runner.runInTerminal": true
}
```

**Comment by narimiran** [comment]
So it is not possible to use custom $PATH (as described above) in output window?

**Comment by formulahendry** [comment]
Yes, currently, I did not find a way to support `.bashrc` in output window...
