### ISSUE TITLE
python 输出中文乱码如何解决？

### ISSUE THREAD

**Issue by jiazone** [formulahendry/vscode-code-runner#206]
百度找了很多办法，输出还是显示中文乱码。有时候还有Unicode的错误

**Comment by jiazone** [comment]
![Uploading image.png…]()

**Comment by formulahendry** [comment]
Two solutions:
1. Try https://github.com/formulahendry/vscode-code-runner/issues/25#issuecomment-263170907
2. use below setting (`File`->`Preference`->`Settings`) to run code in Integrated Terminal:
```json
{
    "code-runner.runInTerminal": true
}
```

**Comment by jiazone** [comment]
第一种方法不行，第二种方法，当打印网页源代码时候，显示不全，并且没有代码运行时间

**Comment by formulahendry** [comment]
You could use `CTRL+C` to stop running code.

**Comment by formulahendry** [comment]
What are missed in output of the web page source code?
