### ISSUE TITLE
测试中文输出的时候是乱码！

### ISSUE THREAD

**Issue by pygrowing** [formulahendry/vscode-code-runner#209]
![tim 20171118143456](https://user-images.githubusercontent.com/24885235/32977708-cb262e76-cc6d-11e7-91d7-0a11e0e54d52.jpg)
测试中文的乱码问题如何解决！
我已经设置了"code-runner.runInTerminal": true，还是乱码。

同时我还有一个问题就是之前我运行测试代码直接鼠标右键选择run code来运行，但老是会额外生成一个tempCodeRunnerFile.java ，这样导致我的类名和文件名不统一发送错误，但是我ctrl+alt+j 在选择java运行就可以了，我想直接右键 run code ，不额外再生产个tempCodeRunnerFile.java 的文件，而是直接运行当前类要如何设置。
![tim 20171118143808](https://user-images.githubusercontent.com/24885235/32977735-47e265e2-cc6e-11e7-9b88-82a5dd76950f.jpg)

谢谢...

**Comment by formulahendry** [comment]
For messy code, what encoding are you using?
![image](https://user-images.githubusercontent.com/1050213/33005552-44d9a038-ce01-11e7-9f38-860acdce54c4.png)

For tempCodeRunnerFile.java, it is because you have selection on the code. You could use below setting to avoid that:
```json
{
    "code-runner.ignoreSelection": true
}
```

**Comment by pygrowing** [comment]
我使用的是UTF—8的编码方式，但是我这边试了下还是乱码：

第二个运行的问题已经完美解决了！


------------------ 原始邮件 ------------------
发件人: "Jun Han";<notifications@github.com>;
发送时间: 2017年11月20日(星期一) 下午2:46
收件人: "formulahendry/vscode-code-runner"<vscode-code-runner@noreply.github.com>;
抄送: "E╮先生   🎈 "<1470976@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [formulahendry/vscode-code-runner] 测试中文输出的时候是乱码！ (#209)




For messy code, what encoding are you using?
 
 
For tempCodeRunnerFile.java, it is because you have selection on the code. You could use below setting to avoid that:
 {     "code-runner.ignoreSelection": true }

**Comment by formulahendry** [comment]
For messy code, could you try to run it in the terminal of your OS?

**Comment by pygrowing** [comment]
果然是系统终端的问题，我按照百度设置了AVA_TOOL_OPTIONS编码方式，但是依旧还是存在乱码问题，请问您可以告诉我有什么解决办法吗？





------------------ 原始邮件 ------------------
发件人: "Jun Han";<notifications@github.com>;
发送时间: 2017年11月20日(星期一) 下午3:30
收件人: "formulahendry/vscode-code-runner"<vscode-code-runner@noreply.github.com>;
抄送: "E╮先生   🎈 "<1470976@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [formulahendry/vscode-code-runner] 测试中文输出的时候是乱码！ (#209)




For messy code, could you try to run it in the terminal of your OS?

**Comment by formulahendry** [comment]
Sorry, no idea about that. Closing it as external issue.

**Comment by Cologler** [comment]
@pygrowing 我刚提交了一个 PR 试图解决这个乱码。

**Comment by hanshou101** [comment]
@formulahendry 关于UTF-8编码的.java文件乱码的问题，可以通过如下方式解决：

![temp](https://user-images.githubusercontent.com/19248935/40462632-5a2e311e-5f43-11e8-92ba-e5c02ca5b300.png)

在"code-runner.executorMap"的java命令里，
由原先的
`"java": "cd $dir && javac $fileName && java $fileNameWithoutExt"`

在编译时，添加上用UTF-8编译的配置，变成
`"java": "cd $dir && javac  -encoding UTF-8  $fileName && java $fileNameWithoutExt"`

（`javac`后面多了` -encoding UTF-8 `）

即可实现无乱码的效果。

**Comment by 1470391328** [comment]
@hanshou101 thanks for your solution
