### ISSUE TITLE
"Run Code" in Output console

### ISSUE THREAD

**Issue by SailorMax** [formulahendry/vscode-code-runner#21]
Currently context menu of Output panel has "Run Code" menu, which return "Code language not supported or defined."

Is it bug or a feature?

**Comment by formulahendry** [comment]
@SailorMax Thanks for reporting it! Seems like it is a VS Code bug. Open an [issue](https://github.com/Microsoft/vscode/issues/12263) to VS Code.

**Comment by formulahendry** [comment]
@SailorMax , this issue has been fixed. Please try the latest version.
