### ISSUE TITLE
如何实现执行结束删除生成的可执行文件

### ISSUE THREAD

**Issue by Ciyou** [formulahendry/vscode-code-runner#213]
我主要使用VSCode写一些竞赛题目，有时候Work Dir下会有大量单文件源码，使用Code Runner编译生成的可执行文件也会很多，为目录管理带来不便，想知道如何配置可以实现执行完毕删除可执行文件或者是否可以增加该配置选项？

**Comment by formulahendry** [comment]
You could update below setting (`File`->`Preference`->`Settings`) (using cpp as example):

```json
{
    "code-runner.executorMap": {
        "cpp": "cd $dir && g++ $fileName -o $fileNameWithoutExt && $dir$fileNameWithoutExt && DO_RMOVE_WORK"
    }
}
```

For direct support in extension, #84 is used to track.
