### ISSUE TITLE
${workspaceRoot} not supported

### ISSUE THREAD

**Issue by garytyler** [formulahendry/vscode-code-runner#215]
I realize code-runner supports using `$workspaceRoot` in the paths, but there are two problems with it, and they are possibly related:

1) It doesn't work with python virtual environments when used. It gets stuck and has to be stopped.

2) `{$workspaceRoot}` is the syntax MS uses. So, maybe this is related to whatever causes 1)

. The syntax VS Code uses for this is `${workspaceRoot}`, as in:

 `"python.pythonPath": "${workspaceRoot}\\learning_pytest\\Scripts\\python.exe"`

Could code-runner be updated to support `${workspaceRoot}`?

**Comment by formulahendry** [comment]
Hi @garytyler , what's the problem of you? Code Runner does not respect the config of `"python.pythonPath"`. You need to specify the python path in `"code-runner.executorMap"`, using `$workspaceRoot` not `${workspaceRoot}`

**Comment by garytyler** [comment]
That does work, but I cannot use this variable in flexible ways. If possible, I wish I could use the `${workspaceRoot}` variable so that I could put it in the middle of a path. A use case would be for virtual environments. It is nice to be able to set `"code-runner.executorMap": {"python": ".\\env_${workspaceRoot}\\Scripts\\python.exe"},`. This way, I can leave this setting and use it across projects for unique virtual environment labels. If it can't be done, then OK. If it can, it would be more consistent with the VS Code variable of `${workspaceRoot}` as well.

**Comment by formulahendry** [comment]
So if you use `"code-runner.executorMap": {"python": ".\\env_$workspaceRoot\\Scripts\\python.exe"}`, it will not work? What's the expected?

**Comment by garytyler** [comment]
I'm sorry! I am accepting this probably would not work anyhow since it is a path. I would need a variable for the folder name. Not sure what I was thinking. Thank you.

**Comment by garytyler** [comment]
I'm sorry. I don't believe that would work anyhow. Please forgive me. Not sure what I was thinking. 

But, the given variable of '$workspaceRoot` does not work correctly for me in a virtual environment. I am using the following:
![capture5](https://user-images.githubusercontent.com/15917021/33537871-1d1782b4-d88c-11e7-9767-6693a8b3d98b.PNG)

The result is the code runs but it does not end as it should. I have to stop it myself. It runs fine when ran from command line or through the python plugin. I am testing with a `print('Hello world')` in Python.

**Comment by formulahendry** [comment]
Could you share the screenshot when you run with Code Runner?

**Comment by garytyler** [comment]
![capture6](https://user-images.githubusercontent.com/15917021/33539476-a3716796-d894-11e7-8942-d63ba21d6517.PNG)

**Comment by formulahendry** [comment]
Oh, I see.
You need to use `"code-runner.executorMap": {"python": $workspaceRoot\\.env\\Scripts\\python.exe $fullFileName"}`
(If you use any customized parameters, $fullFileName will not be auto added)

**Comment by garytyler** [comment]
OK yes thank you!
