### ISSUE TITLE
Not taking the VS Code "powershell.developer.powerShellExePath"

### ISSUE THREAD

**Issue by MaximoTrinidad** [formulahendry/vscode-code-runner#22]
### Issue Description
I'm using the "Code Runner" VS extension and I'm not able to change PowerShell executable path to point to ver. 6.0.0.10:
"C:/Program Files/PowerShell/6.0.0.10/PowerShell.exe" in "settings.json" file.

Following instructions on link: https://github.com/PowerShell/PowerShell/blob/master/docs/learning-powershell/using-vscode.md 

In VS Code Output panel $PSVersionTable results stills shows: PSVersion 5.1.14300.1000.

I did open an incident VS code but the path change works on their Debug option:
"VS Code "powershell.developer.powerShellExePath" not changing path to executable #295"

### System Details

- Operating system name and version: Windows Server 2016 TP5
- VS Code version: 1.5.2
- PowerShell extension version: PowerShell 6.0.0-alpha.10
- Output from `$PSVersionTable`: See attached image.

Please see attached image.
![vscodeposhpathissue](https://cloud.githubusercontent.com/assets/19892435/18610214/40f98614-7ce4-11e6-8d94-5e97390e91fa.png)

**Comment by formulahendry** [comment]
You need to config as below:
```json
"code-runner.executorMap": {
        "powershell": "C:/Program Files/PowerShell/6.0.0.10/PowerShell.exe -ExecutionPolicy ByPass -File"
    }
```

**Comment by MaximoTrinidad** [comment]
I did the change but still getting an error:
[Running] C://Program Files/PowerShell//6.0.0.10//powershell.exe -ExecutionPolicy ByPass -File "c:\Users\mtrinidad\Documents\SAPIEN\PowerShell Studio 2015\Files\chkPowerShellVersion.ps1"
'C://Program' is not recognized as an internal or external command,
operable program or batch file.

[Done] exited with code=1 in 0.045 seconds

- Also I for the following "launch.json":
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "PowerShell",
            "type": "PowerShell",
            "program": "${file}"
        }
    ] 
}

![vscoderunner1_2016-09-19](https://cloud.githubusercontent.com/assets/19892435/18640531/9e04e118-7e66-11e6-8bf3-a1e3adb9826b.jpg)

**Comment by formulahendry** [comment]
It is because there is a blank space in the path, please use quotation marks to wrap:
```json
"code-runner.executorMap": {
        "powershell": "\"C:/Program Files/PowerShell/6.0.0.10/PowerShell.exe\" -ExecutionPolicy ByPass -File"
}
```
BTW, launch.json is not needed for this extension.  :)

**Comment by MaximoTrinidad** [comment]
That's Awesome!!  

It works!  Greatly Appreciate the help.  I will soon blog in this and I'm getting ready for my Sept 29th online Florida PowerShell User Group meeting. I'm showcasing all this in a Cross-Platform environment.

Woohoo!

**Comment by formulahendry** [comment]
Great! Good luck! 😃 
BTW, to use this extension, you just need to config the `code-runner.executorMap`. The `powershell.developer.powerShellExePath` is not needed.
For more instructions about other configurations, you could refer to https://github.com/formulahendry/vscode-code-runner#configuration

**Comment by formulahendry** [comment]
Look forward to your blog post. 😄
