### ISSUE TITLE
mac os 运行python3代码，如何配置既可以支持python3,又可以打印中文。

### ISSUE THREAD

**Issue by fusen-github** [formulahendry/vscode-code-runner#220]
我尝试了如下的设置，但是无效，会报错。
{
    "code-runner.executorMap": {
        "python": "set PYTHONIOENCODING=utf8 && /usr/local/bin/python3"
    }
}
请问，如何处理可以兼顾到支持python3,也可以打印中文。

**Comment by formulahendry** [comment]
Could you share the screenshot of the error message?

**Comment by fusen-github** [comment]
我的setting.json:
![40f91fff-68c2-4516-aeb1-e87a1a449367](https://user-images.githubusercontent.com/11560800/33973276-f3d888c4-e0bc-11e7-862e-767e68945071.png)
我的error info:
![3e1f1888-96b1-48ab-8b8e-5de3e7805126](https://user-images.githubusercontent.com/11560800/33973329-2e485f02-e0bd-11e7-9496-f945ebbc1ebf.png)

**Comment by formulahendry** [comment]
Do your file save as UTF-8?
![image](https://user-images.githubusercontent.com/1050213/33973963-c9d018cc-e0c0-11e7-989d-c65b3d96cc6d.png)

**Comment by fusen-github** [comment]
是的，是UTF-8.

**Comment by formulahendry** [comment]
How about adding below setting?
```json
{
    "code-runner.runInTerminal": true
}
```

**Comment by fusen-github** [comment]
{
    "code-runner.runInTerminal": true
}
这样设置是可以的。

**Comment by formulahendry** [comment]
Closing then.
