### ISSUE TITLE
no module named pytrends.request

### ISSUE THREAD

**Issue by nathanparekh** [formulahendry/vscode-code-runner#225]
I am trying to run python 3.6 code in VS Code using the plugin, but it can't find the module that I installed using `pip3 install pytrends`, throws an error, and quits:

> Traceback (most recent call last):
  File "/Users/nathanparekh/python-project/.../fetch.py", line 4, in <module>
    `from pytrends.request import TrendReq`
ImportError: No module named pytrends.request

However, using VSCode "Run Python File in Terminal" works just fine.

How do I fix this?

**Comment by formulahendry** [comment]
Could you share the screenshot of the whole output?
Another way is to use below setting to run code in Integrated Terminal:
```json
{
    "code-runner.runInTerminal": true
}
```

**Comment by nathanparekh** [comment]
![screen shot 2017-12-24 at 11 58 22 am](https://user-images.githubusercontent.com/33500247/34328887-c53834b4-e8a1-11e7-9d43-58cf084e4d5d.jpg)

I installed pytrends using pip, and it works from the Integrated Terminal.

**Comment by nathanparekh** [comment]
I think I found the problem, but I don't know how to fix it: Code Runner doesn't respect the selected python interpreter, so it is running using python 2.7 instead of python 3.6 where the module is installed. Is there any fix to this? 
For right now I'm using "Run Python File in Terminal"  in the right-click menu that I think is built into Visual Studio.

**Comment by formulahendry** [comment]
You need to below setting (`File`->`Preference`->`Settings`) to specify which Python to use:
```json
{
    "code-runner.executorMap": {
        "python": "/foo/bar/python"
    }
}
```
For `respect the selected python interpreter`, use #226 to track.

**Comment by sravanstrns** [comment]
i am using python 2.7.14 along with the pip but i am also facing this issue 

Traceback (most recent call last):
  File "E:\pytrends\pytrends-master\examples\example.py", line 2, in <module>
    from pytrends.request import TrendReq
ImportError: No module named pytrends.request
