### ISSUE TITLE
Auto select version of Python interpreter (Respect 'Python: Select Interpreter')

### ISSUE THREAD

**Issue by Spacebody** [formulahendry/vscode-code-runner#226]
I have used this plugin for python3 file and for some specified code which can only be used under py3, it goes syntax error since the python set in the excutorMap is ```python```. 

So is it any method that makes the plugin automatically select correct python interpreter version? 

Thanks forward and Merry Christmas.

**Comment by formulahendry** [comment]
Currently, you need to update the `excutorMap` to specify the path of Python (e.g. `python3`)

**Comment by Spacebody** [comment]
So hope  the later update can add this feature.

**Comment by formulahendry** [comment]
It is supported in latest release, please update with below setting and have a try:
```json
"code-runner.executorMap": {
    "python":"$pythonPath $fullFileName"
}
```
