### ISSUE TITLE
System.InvalidOperationException for console app in vscode

### ISSUE THREAD

**Issue by dhowe** [formulahendry/vscode-code-runner#227]
Getting the following error when I run c# console code via code-runner in vscode (scriptcs is installed):
"Unhandled Exception: System.InvalidOperationException: Cannot read keys when either application does not have a console or when console input has been redirected. Try Console.Read."

Same code runs from from terminal
Is there a way to get it to run in vscode/code-runner ?
I've tried setting "code-runner.runInTerminal" = true, but no help

**Comment by formulahendry** [comment]
Could you share the screenshot when you set `code-runner.runInTerminal`. Does it run in terminal?

**Comment by dhowe** [comment]
ah sorry, my bad... I had that option inside  "code-runner.executorMap": {...}
which is why it didn't take effect -- all good now
