### ISSUE TITLE
Run code that uses (nuget) packages

### ISSUE THREAD

**Issue by dhowe** [formulahendry/vscode-code-runner#228]
So I have a simple csharp program (see below) which works in vscode/code-runner until I add a package. As soon as I install one via nuget (e.g., Antlr4),  I can no longer run via code-runner, though things still compile ok. 

What am I doing wrong? Thanks

````csharp
using System;
using Antlr4.Runtime; 

namespace test {
  public class Program {
    public static void Main(string[] args) {
      Console.WriteLine(new AntlrInputStream("Test"));
    }
  }
}

**Comment by formulahendry** [comment]
Could you share the screenshot of the output?

Code Runner supports two types of C# project:

- .NET Core project: you need `Run Code` from .csproj file
- csx (C# script): you need instal http://scriptcs.net/

**Comment by dhowe** [comment]
Thanks! I'm just trying to create a basic console app for .NET core. You can see below that my executorMap is set to use mcs and mono on the current file, which I'm guessing is not correct, as it doesn't know about the package location for antlr... 

Is there a simple example I can reference that uses 'run code' from .csproj (ideally with one or more nuget packages)?

![image](https://user-images.githubusercontent.com/737638/34370257-79b5de5c-eafd-11e7-9183-2ea1beda28e8.png)

**Comment by formulahendry** [comment]
I am not familiar with Mono. I guess you need another command to do nuget restore.
However, if you are using .NET Core: https://www.microsoft.com/net/download/windows  You could simply run your project with `dotnet run`: https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-run?tabs=netcore2x   It will help you restore NuGet dependencies
