### ISSUE TITLE
C++输出中文乱码

### ISSUE THREAD

**Issue by zhangzw16** [formulahendry/vscode-code-runner#229]
how can I fix the problem to show Chinese correctly?
![image](https://user-images.githubusercontent.com/26004183/34386444-a1e22b72-eb63-11e7-81ee-8afa49af5102.png)

I pressed Ctrl+Shift+N four times and didn't change anything else but the outcome was diffrent! Why?
![image](https://user-images.githubusercontent.com/26004183/34386302-f440d0c2-eb62-11e7-8b26-40bd6fd90770.png)

**Comment by formulahendry** [comment]
For `outcome was diffrent`. It is your code to need any key to continue. So the `c` is eaten by your program itself.
![image](https://user-images.githubusercontent.com/1050213/34434661-808dd538-ecc2-11e7-92dd-7c539bee8334.png)
For `show Chinese correctly`, it should be the bug of VS Code terminal. Please report this issue to VS Code repo.
