### ISSUE TITLE
gibberish happened

### ISSUE THREAD

**Issue by cike8899** [formulahendry/vscode-code-runner#23]
When I run typescript file,gibberish happened.I juest write one line code,`"console.info("jike");" `,so as follows:

[Running] ts-node "f:\vscodeSpace\typingsTest\app.ts"
'ts-node' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���

**Comment by formulahendry** [comment]
I guess your OS language is not en-us.
If so, please try below config:
```json
{
    "code-runner.executorMap": {
        "typescript": "chcp 65001 & ts-node"
    }
}
```
BTW, have you installed [ts-node](https://github.com/TypeStrong/ts-node)?

**Comment by cike8899** [comment]
I'm so sorry.I did not install ts-node.

**Comment by formulahendry** [comment]
Never mind. 😄
