### ISSUE TITLE
How to specify the file needs to executed.

### ISSUE THREAD

**Issue by shanmugharajk** [formulahendry/vscode-code-runner#232]
For example I have this structure

```
- src
     - folder01
     - folder02
main.py
```

when I am working a file in folder01 and if I press the hotkey to run it takes the currently opened file and executes. Instead I want to run only main.py irrespective of current file opened in viscose.

I changed the configuration here

```
"code-runner.executorMap": {
    "python": "python3.6 ../main.py",
}
```
This is working but its giving like this path output in the console while executing

<img width="781" alt="screen shot 2018-01-01 at 8 54 47 am" src="https://user-images.githubusercontent.com/11159061/34465413-7a4c6f7a-eed1-11e7-82e5-07c1112caeab.png">

How to do this in a proper way.

Please help me.

**Comment by formulahendry** [comment]
You could try below setting:
```json
"code-runner.executorMap": {
    "python": "cd $workspaceRoot && python3.6 main.py",
}
```

**Comment by shanmugharajk** [comment]
Thanks. It's properly working.

**Comment by formulahendry** [comment]
You see the full list in `Supported customized parameters` section of https://github.com/formulahendry/vscode-code-runner#configuration
