### ISSUE TITLE
Respect 'Python: Select Interpreter' and/or '/usr/bin/env' shebang

### ISSUE THREAD

**Issue by citizenrich** [formulahendry/vscode-code-runner#233]
Coming here from:
https://github.com/Microsoft/vscode-python/issues/497

I'm curious if code-runner will support the settings for Python path from the command palette (Python: Select Interpreter) or support the '#!/usr/bin/env python{2, 3}' shebang? What should be done to configure code-runner to respect python3?

**Comment by formulahendry** [comment]
You need to below setting (`File`->`Preference`->`Settings`) to specify which Python to use:
```json
{
    "code-runner.executorMap": {
        "python": "/foo/bar/python"
    }
}
```
For `respect the selected python interpreter`, use #226 to track.

**Comment by formulahendry** [comment]
@citizenrich FYI, in latest release, Shebang is supported now.

**Comment by formulahendry** [comment]
@ClericPy How about adding a setting to control whether to ignore shebang?

**Comment by ClericPy** [comment]
That will be much more flexible. 
Btw, now I found shebang is very useful to distinguish between python2 and python3, because they are .py files both. Now I can set python2 field in "code-runner.executorMap", it's cooler than py-launcher on windows.

**Comment by formulahendry** [comment]
@ClericPy Thanks for your feedback! BTW, a new setting `code-runner.respectShebang` is added.

**Comment by ClericPy** [comment]
Thanks for this excellent toolkit.

**Comment by ClericPy** [comment]
@formulahendry 
User Settings of settings.json is a smart choice. Is it possible to have an option to set ignore the shebang pattern like
`code-runner.ignoreShebang: ['#! coding: *', '#! *test*']`

**Comment by formulahendry** [comment]
Thanks @ClericPy for the feedback! Have created an issue to track #323
