### ISSUE TITLE
bug?or feature?

### ISSUE THREAD

**Issue by fA1sEr** [formulahendry/vscode-code-runner#235]
for example
run
while 1:print(1)
in python
it will stop in 1 second

**Comment by formulahendry** [comment]
What do you mean `it will stop in 1 second`?

**Comment by fA1sEr** [comment]
run it in Terminal, it will loop forever
but run it with coderunner, it will stop in 1 second

**Comment by formulahendry** [comment]
It seems due to the output is too much in a short time, since you do not `sleep` in the loop. You could use below setting (`File`->`Preference`->`Settings`) to run code in Integrated Terminal:
```json
{
    "code-runner.runInTerminal": true
}
```

**Comment by fA1sEr** [comment]
thanks
