### ISSUE TITLE
Code Runner not running

### ISSUE THREAD

**Issue by passacaglia** [formulahendry/vscode-code-runner#237]
After I run code from the editor context menu, nothing happened. 

Here is a gif image shows the issue  (https://s10.postimg.org/70dcch3rt/GIF.gif)

How do I solve this problem?

**Comment by formulahendry** [comment]
If you go to `Help` -> `Toggle Developer Tool`, do you see any error log in console tab?
Also, could you try to uninstall and install the extension again?

**Comment by passacaglia** [comment]
Thank you. It's weird not to be working even after I try to uninstall and re-install VSC yesterday. But it works now, still weird.

**Comment by passacaglia** [comment]
Seems code runner won't run if there's nothing in the workspace. Once I add a folder to the workspace, the runner runs.

**Comment by formulahendry** [comment]
@passacaglia I could not repro from my side. Could you share more details?
