### ISSUE TITLE
Option to remove output info

### ISSUE THREAD

**Issue by emadb** [formulahendry/vscode-code-runner#24]
It would be useful have a setting to remove the pre ([Running]) and post ([Done]) labels in the output console.
thx

**Comment by formulahendry** [comment]
Option to remove the two whole lines of [running] and [done], not just the two labels, right？

**Comment by emadb** [comment]
Yes. Exactly. In some cases in too noisy.

**Comment by formulahendry** [comment]
@emadb , just add a config entry `code-runner.showExecutionMessage`. Please install the latest version and have a try.

**Comment by gaoryrt** [comment]
What if I don't need [running] while do need [done], like #315 ?
Maybe we should split `code-runner.showExecutionMessage` into `showRunningMessage` and `showDoneMessage`

**Comment by amansheaven** [comment]
Even if there is no message output window is open is there a way to bypass that?
