### ISSUE TITLE
How to add -W -Wall -Wextra -Werror flags fro CPP compilation

### ISSUE THREAD

**Issue by baborlelefan** [formulahendry/vscode-code-runner#243]
Hi, 

I'd like to know how I could compile with flags.
Also how can I compile several files (such as *.cpp for example), and how I can compile with a Makefile.
Thanks a lot for your help,
Babor

**Comment by cpplucifer** [comment]
@baborlelefan 
1. Compile a single cpp file:  

```
"code-runner.executorMap": {
    "cpp": "g++ /path/to/main.cpp -Wall -g -o /path/to/target"
}
```

2. Compile a project:

```
"code-runner.customCommand": "cd /path/to/build && make"
```

**Comment by formulahendry** [comment]
Thanks @cpplucifer !
Closing this issue then. @baborlelefan Please reopen the issue if you need other help.

**Comment by adarshanand67** [comment]
Thanks working !
