### ISSUE TITLE
Bash environment picked up only when running in terminal

### ISSUE THREAD

**Issue by lidderupk** [formulahendry/vscode-code-runner#244]
The bash_profile is not picked when 
`"code-runner.runInTerminal": false,`
The output is shown in `output` window. I get
`ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ibm_db.cpython-36m-darwin.so, 2): Library not loaded: libdb2.dylib`

If I change 
`"code-runner.runInTerminal": true,`
The output is shown in `terminal` window and the bash_profile exports are picked up. The export to fix the above error is in bash_profile as:
`export DYLD_LIBRARY_PATH=/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/clidriver/lib:$DYLD_LIBRARY_PATH`

Is this working as expected? Thank you.

**Comment by DongShelton** [comment]
I have the same problem. I am using nvm to manager nodejs, if I set:
```
"code-runner.runInTerminal": false,
```
It would result in:
```
/bin/sh: node: command not found
```
But I set:
```
"code-runner.runInTerminal": true,
```
It would work corretly, is it a issue?

**Comment by formulahendry** [comment]
Yes, to support bash_profile, you need set `"code-runner.runInTerminal": true`.

**Comment by jakkn** [comment]
Took me a while to find this information. Same situation as above - using nvm. Workaround works fine. Issue could do with a fyi label.
