### ISSUE TITLE
Code-Runner not working with Node under WSL

### ISSUE THREAD

**Issue by zoomclub** [formulahendry/vscode-code-runner#247]
To complete the setup on my new Windows 10 machine I was hoping to use Code-Runner but I'm getting "node is not recognized as an internal or external command, operable program or batch file" as output when I try to use it.

Looking around at the issues of the day it does look like VSCode and WSL are still being integrated, there is now a useWSL option that can be used in launch.json. Still, running code in the Debugger versus Code-Runner are different experiences. Is useWSL useful for Code-Runner or is there something else I can config so that Code-Runner will recognize and use the Node I've install under WSL?

**Comment by formulahendry** [comment]
Have you installed https://nodejs.org/ and set it in PATH environment variables?

**Comment by formulahendry** [comment]
I see, you installed in WSL, so you need set as below to run in terminal
```json
{
    "code-runner.runInTerminal": true
}
```

**Comment by zoomclub** [comment]
That worked like a charm, thank you 👍
