### ISSUE TITLE
output utf8 chars  incorrect

### ISSUE THREAD

**Issue by yufengzjj** [formulahendry/vscode-code-runner#25]
python3.5.2
![out](https://cloud.githubusercontent.com/assets/7138035/19831786/36d083f4-9e45-11e6-9c45-35abdf0996c6.png)

**Comment by formulahendry** [comment]
You may try below two options for this issue:
1.Use chcp to set code page of consloe
```json
{
    "code-runner.executorMap": {
        "python": "chcp 65001 | py"
    }
}
```

2.Run it in built-in terminal to see if it works (I have not tested it, but should work)
```json
{
    "code-runner.runInTerminal": true
}
```

**Comment by yufengzjj** [comment]
running in terminal works.

**Comment by formulahendry** [comment]
So the first method is not working? Could you show me the output? And could you try ` "chcp 65001 & py"` and show me the output?

**Comment by yufengzjj** [comment]
default codepage 936
----main.py---
print("呵呵")
----------------
output:
![out](https://cloud.githubusercontent.com/assets/7138035/19835549/55b75cb8-9ec5-11e6-821f-84bc6549c29e.png)

**Comment by formulahendry** [comment]
Could you please try run `py ***` and `chcp 65001 & py ***` in OS terminal (cmd?)

**Comment by yufengzjj** [comment]
same main.py:
![1](https://cloud.githubusercontent.com/assets/7138035/19844163/b5a39eee-9f64-11e6-99f3-1cdbbe08231b.png)
run chcp 65001 py -3 main.py:
![2](https://cloud.githubusercontent.com/assets/7138035/19844173/d3853a80-9f64-11e6-9148-f741419cb3d3.png)

**Comment by formulahendry** [comment]
Hi @yufengzjj , this issue is similar to #33 , and @sunqi1993 has found a way to resolve it. Could you please have a try to see whether it works for you?

``` json
{
    "code-runner.executorMap": {
        "python": "set PYTHONIOENCODING=utf8 && python"
    }
}
```
![image](https://cloud.githubusercontent.com/assets/12682690/20649794/1462b03e-b502-11e6-877d-a473cd3efc81.png)

**Comment by yufengzjj** [comment]
it works:
![image](https://cloud.githubusercontent.com/assets/7138035/20654975/2732dca0-b559-11e6-9e19-b1104b93063f.png)

**Comment by xcf007** [comment]
java的输出也乱码

**Comment by formulahendry** [comment]
@xcf007 Did you try these two methods? https://github.com/formulahendry/vscode-code-runner/issues/25#issuecomment-257123682

**Comment by xcf007** [comment]
"code-runner.runInTerminal": true
谢谢，这个可以了。另外 JAVA_HOME没设置，这个不想全局修改环境变量，再vsc里可以配吗，我java.home配置了没起作用

**Comment by formulahendry** [comment]
You could set Java path in below settings: 
```json
"code-runner.executorMap": {
        "java": "/foo/bar/java ****"
}
```

**Comment by fusen-github** [comment]
如何设置，既能支持python3，又可以输出中文？

**Comment by blurhead** [comment]
export PYTHONENCODING=utf8 && python fileName, it works for me in macOS

**Comment by iamhectorotero** [comment]
Did you mean to type
```
export PYTHONIOENCODING=utf8
```
@blurhead?

**Comment by Antecer** [comment]
![image](https://github.com/formulahendry/vscode-code-runner/assets/8684916/68ffb45b-87da-4ad7-a5fc-8fca7f571b17)

C语言也乱码

**Comment by Antecer** [comment]
```
"code-runner.executorMap": {
    "c": "cd $dir && gcc $fileName -o R:/$fileNameWithoutExt && R:/$fileNameWithoutExt && del R:/$fileNameWithoutExt.exe"
}
```
![image](https://github.com/formulahendry/vscode-code-runner/assets/8684916/d7a290e1-1439-487a-a0a0-678df62cafca)
