### ISSUE TITLE
How to add entry into code-runner.executorMap?

### ISSUE THREAD

**Issue by articulatesnail** [formulahendry/vscode-code-runner#252]
In the configuration section it says to:

You could also add entry into code-runner.executorMap to set the executor PATH. e.g. To set the executor PATH for ruby, php and html:

How do I add this entry to that file. I can't find it in any directory or through VScode.

Thanks!

**Comment by formulahendry** [comment]
Hi @articulatesnail , please refer to https://code.visualstudio.com/docs/getstarted/settings#_creating-user-and-workspace-settings

**Comment by Graynoble** [comment]
> That link shows how to replace the entire map. Its does not show how to modify/add a single entry.

Hello @articulatesnail , I also had this issue. I took the entire map and replaced it.  I only changed/modified the entries I needed and left the rest as original.

**Comment by imankm86** [comment]
I am new to python and VS Code. Where is the code-runner.executorMap file located? I am on Unix.

**Comment by mgrollins** [comment]
Open your global settings (Ctrl+Shift+P or Ctrl+,) and then enter "code-run" in the search box.

Scroll down through the results and choose "Edit in settings.json" under the "Executor Map" that you would like to edit. (e.g. Global, by File Extension, by Glob)

Under my install, the specific "Setting ID" I was looking for was titled: 
    `code-runner.executorMapByFileExtension`

**Comment by Rayshard** [comment]
Go to the .vscode//extensions//"The code runner name"//package.json and edit it there

**Comment by rlawns324** [comment]
Go Extension -> Click **"Code Runner"** 's gear icon -> Click **"Configure Extension Settings"** -> Search **"Code-runner: Executor Map"** -> Click **"Edit in settings.json"** then you will see a **.json** code like this(could be different depending on your system setting)   

```
{
    "C_Cpp.updateChannel": "Insiders",
    "editor.fontSize": 14,
    "window.zoomLevel": 0,
    "atomKeymap.promptV3Features": true,
    "editor.multiCursorModifier": "ctrlCmd",
    "editor.formatOnPaste": true,
    "code-runner.runInTerminal": true,
    "C_Cpp.default.cppStandard": "c++14",
    "C_Cpp.default.cStandard": "c11",
}
```  

You can add entry like this. `"code-runner.executorMap": { ~ ` 

```
 {
    "C_Cpp.updateChannel": "Insiders",
    "editor.fontSize": 14,
    "window.zoomLevel": 0,
    "atomKeymap.promptV3Features": true,
    "editor.multiCursorModifier": "ctrlCmd",
    "editor.formatOnPaste": true,
    "code-runner.runInTerminal": true,
    "C_Cpp.default.cppStandard": "c++14",
    "C_Cpp.default.cStandard": "c11",
    "code-runner.executorMap": {
        "javascript": "node",
        "php": "C:\\php\\php.exe",
        "python": "python",
        "perl": "perl",
        "ruby": "C:\\Ruby23-x64\\bin\\ruby.exe",
        "go": "go run",
        "html": "\"C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe\"",
        "java": "cd $dir && javac $fileName && java $fileNameWithoutExt",
        "c": "cd $dir && gcc $fileName -o $fileNameWithoutExt && $dir$fileNameWithoutExt",
        "cpp": "cd $dir && g++ -std=c++14 $fileName -o $fileNameWithoutExt && $dir$fileNameWithoutExt"
    }
}
```  
I set this for modern c++ environment setting. hope this helpful :)

**Comment by niemand20** [comment]
what should i change in mac OS for html?

**Comment by rlawns324** [comment]
@niemand20 this page should help :)
Frist, I recommend to use 'alias' command to execute chrome app on command, then you can add this command to code-runner executorMap. the screenshot below explains all.
<img width="500" alt="Screen Shot 2020-07-11 at 2 53 40 PM" src="https://user-images.githubusercontent.com/28533936/87217727-70482900-c387-11ea-95cd-ac8b1bd76067.png">
<img width="500" alt="Screen Shot 2020-07-11 at 2 54 02 PM" src="https://user-images.githubusercontent.com/28533936/87217733-80600880-c387-11ea-8cc9-cbb0085466b0.png">

reference
https://apple.stackexchange.com/questions/83630/create-a-terminal-command-to-open-file-with-chrome

**Comment by SsNipeR1** [comment]
Im using windows and i hate it filesystem because i use git bash as default terminal and if i want to compile c++ i need to do it manually. Command is `cd "d:\folder1\folder 2"\` but reversed slash can be used to add spaces or other symbols to command, but using it without "". I can write "hello world" or hello\ world. And because that i cant set it to normal. help
