### ISSUE TITLE
Not able to run a simple java class

### ISSUE THREAD

**Issue by Shababsoft** [formulahendry/vscode-code-runner#256]
I am getting the below error message when trying to run a simple java class. It says file not found but there is a file with name Test.java in Java Test folder.
`[Running] cd "c:\Users\Admin\Desktop\Java Test\" && javac Test.java && java Test
javac: file not found: Test.java
Usage: javac <options> <source files>
use -help for a list of possible options
`

**Comment by formulahendry** [comment]
Could you have a screenshot of the whole VS Code?

**Comment by ereDaMeme** [comment]
It can't find the file you're trying to execute, try running it from terminal.

Also try checking the path of your file

**Comment by Shababsoft** [comment]
Please see the bellow screenshot.
![2018-03-12 09_26_56-test java - ppl-sfdc - visual studio code](https://user-images.githubusercontent.com/4686730/37275604-9dfd181a-25d7-11e8-8bf8-18841f74c463.png)

**Comment by Shababsoft** [comment]
@ereDaMeme  - The path is fine becausae I have opened a file in vscode and the plugin is getting the correct path but it is not able to build and run the file.

**Comment by formulahendry** [comment]
@Shababsoft  Could you try to run the same command in terminal?

**Comment by Shababsoft** [comment]
@formulahendry  - The following commands work in CMD and vscode terminal.
![2018-03-12 14_55_08-test java - ppl-sfdc - visual studio code](https://user-images.githubusercontent.com/4686730/37290925-6aac8f4e-2605-11e8-9930-d371e4f45177.png)
![2018-03-12 14_53_08-test java - ppl-sfdc - visual studio code](https://user-images.githubusercontent.com/4686730/37290927-6ad150ea-2605-11e8-9838-1a8c396f169f.png)

**Comment by Nirajn2311** [comment]
@Shababsoft Does your main class file and program have same name

**Comment by formulahendry** [comment]
@Shababsoft Did you open a project that in `E:\` folder? Try below setting: `"code-runner.fileDirectoryAsCwd": true`

**Comment by ereDaMeme** [comment]
@Shababsoft try setting "code-runner,runInTerminal" = true and make sure powershell is selected as terminal

**Comment by Shababsoft** [comment]
"code-runner.fileDirectoryAsCwd": true  resolved the issue on window 10. Thanks
