### ISSUE TITLE
Javascript ECMA 6/7 Support

### ISSUE THREAD

**Issue by JuniorDiasOliveira** [formulahendry/vscode-code-runner#257]
I'm getting "Unexpected Token import" when trying to run a simple ECMA 6 code with an "import" on the top of the file.
![image](https://user-images.githubusercontent.com/1569162/36222822-a7cfa048-11a9-11e8-916a-3e4461c21244.png)

**Comment by formulahendry** [comment]
What's your Node.js version? If you run the same js in terminal, what's the result? It is not related to this extension but your Node.js version.
