### ISSUE TITLE
Output prints once ended the script

### ISSUE THREAD

**Issue by ismaelestalayo** [formulahendry/vscode-code-runner#258]
I'm doing some Python scripting where I'm doing 20-30 calls to an API, and after each of the calls I print the ouput of some of it. But, for some reason, it prints the whole output once the script has ended, and not while it's running.

(Running the script on the terminal does print the output while running the script)

**Comment by formulahendry** [comment]
Please refer to below two solutions:

- https://github.com/formulahendry/vscode-code-runner/issues/70#issuecomment-277164298
- https://github.com/formulahendry/vscode-code-runner/issues/70#issuecomment-309744247
