### ISSUE TITLE
Add Support for Ocaml

### ISSUE THREAD

**Issue by jamroks** [formulahendry/vscode-code-runner#26]
I'm using vs code with the ocaml extension , and it has been a joy . 
Please can you add support for running ocaml code too , it would be fantastic for the ocaml users of vs code

**Comment by formulahendry** [comment]
Hi @jamroks , I am not familiar with Ocaml, but it seems that we need to compile first then run it. Currently, our extension only supports script language which does not need compilation. Per this [article](http://www2.lib.uchicago.edu/keith/ocaml-class/compiling.html), I see we could run ocaml file directly without compiling. 

Therefore, in short term, I will add support to run ocaml without compilation. In long term, I will try to add support for compiled language like Java, C++ as well as Ocaml. What do you think of it?

**Comment by jamroks** [comment]
Yes please that would be great for a start !

**Comment by formulahendry** [comment]
@jamroks , support to run OCaml Script is added in latest version. Please install and have a try. For the support of compiled language. Use #30 to track. So close this issue.

**Comment by jmadiot** [comment]
Hello, this is great. It would be even better to replace "OCaml Script" with "OCaml" in the README, as it is the name of the language, and it is not really a script language. Calling simply "ocaml" is as fast as running the bytecode compiler and running the compiled code anyway.

If one really wants performance it is also possible to get faster code by calling the optimizing native-code compiler `ocamlopt`, by adding the following line to the configuration, but I think it is overkill and that the current configuration is fine.

`        "ocamlopt": "cd $dir && ocamlopt $fileName -o $fileNameWithoutExt && $dir$fileNameWithoutExt",`
