### ISSUE TITLE
Cargo Run doesn't run in terminal even with the setting enabled

### ISSUE THREAD

**Issue by sarthakn7** [formulahendry/vscode-code-runner#261]
I was unable to enter any input when running Rust programs, and then I found #72 and #260 and added the runInTerminal setting. Now when a Rust file is run, it's executed in the terminal (and I can enter an input) but Cargo run still runs in the output window and I can't enter any input there.

Can this issue with Cargo be fixed ?

**Comment by formulahendry** [comment]
The setting should be same for all languages. Could you share a screenshot of `Cargo run still runs in the output window`?

**Comment by sarthakn7** [comment]
There you go:

![cargo_run_in_output](https://user-images.githubusercontent.com/12890299/36647746-309b5848-1a58-11e8-9081-a09f3020b805.jpg)

**Comment by formulahendry** [comment]
How do you trigger `Cargo` run? Obviously, it is not using `Code Runner` extension. I guess you are using other extension to run.

**Comment by sarthakn7** [comment]
This is how I run it:
1) Press Ctrl + Shift + P
2) Type "Cargo", getting Cargo run below it, or now in my case it always appears under recently used:
![cargo_run](https://user-images.githubusercontent.com/12890299/36652767-ba8f2838-1a7e-11e8-8f76-c1e08dd1c03b.jpg)

3) Click on Cargo: Run

And about using other extensions - I only have the Code Runner and Rust extensions installed, there is no question of triggering Cargo run using some other extension.

**Comment by formulahendry** [comment]
`Cargo: Run` is in Rust extension
![image](https://user-images.githubusercontent.com/1050213/36653185-840015d2-1aee-11e8-9b59-73231c761123.png)

**Comment by sarthakn7** [comment]
Yes, I just found out myself too. Thanks.
