### ISSUE TITLE
how to run scheme/racket?

### ISSUE THREAD

**Issue by lgqfhwy** [formulahendry/vscode-code-runner#262]
I am a beginner and I want to learn scheme or racket. But I don't want to use emacs ( too hard for me),
I like vscode, so I want to write scheme or racket on vscode like other language, just "run", could you help me, thank you so much!

**Comment by formulahendry** [comment]
racket is already supported, What issue do you meet with?

**Comment by lgqfhwy** [comment]
<img width="883" alt="screen shot 2018-02-28 at 18 52 17" src="https://user-images.githubusercontent.com/16728136/36783912-9b5820f0-1cb8-11e8-8045-9042319249a8.png">

**Comment by lgqfhwy** [comment]
I can't run scheme, how to do this?

**Comment by formulahendry** [comment]
scheme is not supported yet, so it would be a feature request

**Comment by formulahendry** [comment]
BTW, what interpreter/compiler are widely used in Scheme?

**Comment by lgqfhwy** [comment]
racket, (https://racket-lang.org), thank you so much.

**Comment by formulahendry** [comment]
Sorry, I am not familiar with Racket and scheme. Are't they different languages? Just want to know more context about this.

**Comment by formulahendry** [comment]
Currently, you could run with `.rkt` file

**Comment by lgqfhwy** [comment]
Yes, that's all right. Thank you so much!

**Comment by lgqfhwy** [comment]
As far as I know, many people who using scheme may be prefer MIT/GUN SCHEME(https://www.gnu.org/software/mit-scheme/), so maybe it is not a good idea to add support to 
run racket for .scm. Because it may make some people confused, actually it has some difference between scheme and racket.
So I argue that adding support MIT/GUN SCHEME for .scm would be a great idea.
I am a beginner,  what I said may have some mistakes. So it is better to listen to what other excellence programmers said.
Thank you so much. I am very satisfied  with current version.

**Comment by formulahendry** [comment]
Thanks @lgqfhwy for the information!
