### ISSUE TITLE
Not able to run Swift

### ISSUE THREAD

**Issue by kareemamrr1203** [formulahendry/vscode-code-runner#263]
I'm getting the below error when trying to run some swift code.
`[Running] swift "c:\Users\Kareem\Desktop\test.swift"
'swift' is not recognized as an internal or external command,
operable program or batch file.`

**Comment by MzIy05** [comment]
swift is compiled with Xcode and Xcode only works with Mac OS X, you can use an online compiling service with VB code or get  Mac OS X (through Virtual box or apple based system)

If you somehow managed to make swift run under windows the problem is your system variable path.

**Comment by formulahendry** [comment]
Thanks @MzIy05 for the detailed explanation! Closing this issue.

**Comment by Mashiro3131** [comment]
This work now for me but now I have a new error: <unknown>:0: error: could not load the swift standard library.
Any idea how to solve this?
