### ISSUE TITLE
Config code-runner

### ISSUE THREAD

**Issue by Jomme5** [formulahendry/vscode-code-runner#264]
Where do I have to put this?

{
    "code-runner.executorMap": {
        "javascript": "node",
        "php": "C:\\php\\php.exe",
        "python": "python",
        "perl": "perl",
        "ruby": "C:\\Ruby23-x64\\bin\\ruby.exe",
        "go": "go run",
        "html": "\"C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe\"",
        "java": "cd $dir && javac $fileName && java $fileNameWithoutExt",
        "c": "cd $dir && gcc $fileName -o $fileNameWithoutExt && $dir$fileNameWithoutExt"
    }
}

**Comment by formulahendry** [comment]
Please refer to https://code.visualstudio.com/docs/getstarted/settings#_creating-user-and-workspace-settings
