### ISSUE TITLE
New shebang support for python scripts not working properly in windows.

### ISSUE THREAD

**Issue by rtxg** [formulahendry/vscode-code-runner#265]
Hi,

When a python script using the shebang format

#!/usr/bin/env python

or 

#!/usr/bin/env python3

is run using ctrl-alt-n it fails with the messages:-
![code-runner-failed](https://user-images.githubusercontent.com/30565077/37123523-4e36c6ac-22b0-11e8-978b-b1a541b8c8dd.jpg)
![code-runner-failed-3](https://user-images.githubusercontent.com/30565077/37123524-4e893392-22b0-11e8-8d88-8baaa1743d1f.jpg)

The only way I can now run python scripts using the #!/usr/bin/env python style shebang is to hit ctrl-alt-j and then select python.

It's definitely related to the shebang as it has only started failing since the last update, and if I remove the shebang or change it to just #!python or #!python3 it works fine as shown below, but I then lose some portability between windows and linux.

![code-runner-success](https://user-images.githubusercontent.com/30565077/37123670-d12261f2-22b0-11e8-8853-fc33025d7764.jpg)
![code-runner-success-3](https://user-images.githubusercontent.com/30565077/37123672-d17571f8-22b0-11e8-8ee6-36600db51db4.jpg)

I've played with the "code-runner.executorMap" settings, among others, but without any success.

A way to correctly interpret the #!/usr/bin/env style shebang, or even just a setting to ignore the shebang altogether would be great.

**Comment by formulahendry** [comment]
@rtxg A new setting `code-runner.respectShebang`, you could set it as false to ignore the shebang, please have a try.

**Comment by rtxg** [comment]
Works perfectly. Many thanks.

**Comment by RealFlachmann** [comment]
That' a helpful feature, but in my opinion "False" should be the default.

**Comment by VideoPlayerCode** [comment]
@RealFlachmann I agree, or at least False on Windows.

**Comment by VideoPlayerCode** [comment]
@RealFlachmann I agree, or at least intelligently default to False on Windows and True on Linux/Mac.

@formulahendry What do you think? :-)
