### ISSUE TITLE
Runs gcc but not execute code

### ISSUE THREAD

**Issue by ereDaMeme** [formulahendry/vscode-code-runner#270]
![image](https://user-images.githubusercontent.com/35110449/37258732-7b4239e8-2552-11e8-8451-f1cb1d8301ba.png)

This is becoming annoying having to keep installing.

EDIT: Tried reinstalling it but won't work still.

**Comment by formulahendry** [comment]
Could you try to run the same command in terminal?

**Comment by ereDaMeme** [comment]
sure

**Comment by ereDaMeme** [comment]
Got it to work.

**Comment by ereDaMeme** [comment]
*its happening again i hate life*

**Comment by formulahendry** [comment]
What if you just run a simple hello world cpp file?

**Comment by ereDaMeme** [comment]
I just need to run in powershell, I was running in Git Bash/
