### ISSUE TITLE
Python Chinese print("中文测试") BUG

### ISSUE THREAD

**Issue by Tonysmark** [formulahendry/vscode-code-runner#271]
Let me explain myself, I'm a Chinese people but when I use the runner to run python file, things are getting ugly.
1. input("中文测试") I will get this  ����������N�� 
2. print("中文测试") I will get this  �����루��0����1��2����

However, if I  use "# -*- coding: utf-8 -*-" at the front things will not get better

And the environment I'm using is Windows10 with Anaconda

**Comment by formulahendry** [comment]
For stdin support and encoding issue, please use below setting (`File`->`Preference`->`Settings`) to run code in Integrated Terminal:
```json
{
    "code-runner.runInTerminal": true
}
```

**Comment by Tonysmark** [comment]
Thank you very much!!! 

发送自 Windows 10 版邮件应用

发件人: Jun Han
发送时间: 2018年3月12日 22:34
收件人: formulahendry/vscode-code-runner
抄送: tony; Author
主题: Re: [formulahendry/vscode-code-runner] Python Chinese print("中文测试") BUG (#271)

For stdin support and encoding issue, please use below setting (File->Preference->Settings) to run code in Integrated Terminal:
{
    "code-runner.runInTerminal": true
}

**Comment by Sbrjt** [comment]
I could solve it by changing this in executor map:

    "code-runner.executorMap": {
        "python": "set PYTHONIOENCODING=utf8 && python -u $fullFileName",

@Tonysmark
