### ISSUE TITLE
Run files without extension (using code-runner.defaultLanguage) 

### ISSUE THREAD

**Issue by caub** [formulahendry/vscode-code-runner#273]
I'd like to run files without extensions, typically bash scripts using your great code-runner extension

Currently it works if a script has the `.sh` extension, not without (which is more usual for scripts)

Is this possible to implement?

it could respect default language setting for those files

    "code-runner.defaultLanguage": "shellscript",

running `./foo` or `bash foo` or `sh foo` work in the terminal, before you ask (the file has the right permissions)

**Comment by formulahendry** [comment]
I think you could use `code-runner.customCommand`.

**Comment by caub** [comment]
@formulahendry thanks, but I'd need a different shortcut to run it, not very practical

It's very common that bash/shell script are extension-less, so it would be great that it uses the defaultLanguage when there is no extension. I cloned the repo, looked at the sources, but didn't find why it wasn't working. How can I load your extension locally instead of the marketplace one to test?

things I'd like to work on
- add tests
- make file with no extension use `defaultLanguage` mapping
- try to read a possible hashbang

**Comment by formulahendry** [comment]
Sorry, I am not very clear about you requirement. Could you please share more details? What's the current behavior? And what's your expected behavior?

To debug the extension, just clone the repo, run `npm install`, then press `F5`.

**Comment by caub** [comment]
![2018-03-19-131031_1354x1040_scrot](https://user-images.githubusercontent.com/3134574/37594967-3e49a15e-2b77-11e8-8671-78593cd04032.png)

![2018-03-19-131156_1354x1039_scrot](https://user-images.githubusercontent.com/3134574/37594973-4227ed4e-2b77-11e8-805c-3dfc3a83b385.png)

my code-runner settings:

```json
	"code-runner.saveFileBeforeRun": true,
	// "code-runner.runInTerminal": true,
	"code-runner.clearPreviousOutput": true,
	"code-runner.defaultLanguage": "shellscript",
	"code-runner.enableAppInsights": false,
	"code-runner.showExecutionMessage": true,
	"code-runner.executorMap": {
		"sql": "psql -U postgres -f",
		"bash": "bash"
	},
```

I'd want to still be able to run the `lol` file, like I would run it if it were `lol.sh` or `lol.bash`

**Comment by formulahendry** [comment]
Oh! This is a bug of the extension.
