### ISSUE TITLE
UnicodeEncodeError

### ISSUE THREAD

**Issue by kobzar** [formulahendry/vscode-code-runner#276]
Hello. Thanks for the good plugin. But i have the trouble with python run script. 
When i run my script from runner terminal or from system console - all is fine. 
But if i run the same from runner my app returned UnicodeEncodeError when i send data. 
Use "code-runner.runInTerminal": true, it's not solution for me. This action does't have points of this. 

"code-runner.executorMap" with diff parameters doesn't help me to. My app just listen and printed data.
Data the same. Data in utf. And work well if i run it from runner terminal.

**Comment by formulahendry** [comment]
What if you run a simple hello world python script? Could you have a screenshot?

**Comment by kobzar** [comment]
It was my mistake.
Runner was start script with system python, not from ENV
