### ISSUE TITLE
python 读取文件，不能找到相应的文件

### ISSUE THREAD

**Issue by Cyrus97** [formulahendry/vscode-code-runner#279]
![image](https://user-images.githubusercontent.com/27063514/37562752-fca0f332-2aaa-11e8-98a9-ed52dd8d5ecc.png)

![image](https://user-images.githubusercontent.com/27063514/37562763-45520bde-2aab-11e8-9e45-1254f95cbf31.png)

使用 code runner 运行 python 读取文件时，找不到相应的文件，但是我在 powershell 上可以正常运行。

**Comment by formulahendry** [comment]
`./test.json` -> you are using the relative path. Please refer to https://github.com/formulahendry/vscode-code-runner#about-cwd-setting-current-working-directory for the working director
