### ISSUE TITLE
C++中文输出还是有bug啊……可能是编译生成的问题？

### ISSUE THREAD

**Issue by grdaimap** [formulahendry/vscode-code-runner#283]
在vscode中使用coderunner乱码。
![20180324233834](https://user-images.githubusercontent.com/36882078/37865783-7f69415a-2fbc-11e8-9c2e-dfb4c51905fc.png)
命令提示符中运行生成的exe乱码（而且是不同的乱码）。
![20180324234151](https://user-images.githubusercontent.com/36882078/37865845-16e77ace-2fbd-11e8-9880-99477a15df3d.png)
coderunner保持全部默认设置。

**Comment by formulahendry** [comment]
Please use this setting to run code in terminal : `"code-runner.runInTerminal": true`

**Comment by grdaimap** [comment]
现在就一直用终端来输出了……
