### ISSUE TITLE
When [Running]  javascript code

### ISSUE THREAD

**Issue by Nerzool1989** [formulahendry/vscode-code-runner#284]
[Running] node "d:\DEVELOPER\FRONTEND\JS\On Kantor lesson\main.jsx"
"node" �� ���� ����७��� ��� ���譥�
��������, �ᯮ��塞�� �ணࠬ��� ��� ������ 䠩���.

[Done] exited with code=1 in 0.039 seconds

what to do ???

**Comment by formulahendry** [comment]
To avoid the messy code, please use bellow setting:
``` json
{
    "code-runner.runInTerminal": true
}
```

BTW, I guess the Node.js is not installed or Node interpreter is not set in your PATH environment variables.

**Comment by Nerzool1989** [comment]
thank you)
