### ISSUE TITLE
executor map and error

### ISSUE THREAD

**Issue by devxsss** [formulahendry/vscode-code-runner#285]
PS C:\Users\user\Documents\cppp> C:\MinGW\bin\g++.exe "c:\Users\user\Documents\cppp\mainn.cpp"
PS C:\Users\user\Documents\cppp> cd "c:\Users\user\Documents\c\" ; if ($?) { gcc test.c -o test } ; if ($?) { .\test }
insert:C:\MinGW\bin\g++.exe "c:\Users\user\Documents\cppp\mainn.cpp"

I try using code runner, but when execute files, there is no output in terminal and only showing code above.
is there an error on code above? there is no output in terminal

I read that I need to change executor map too

           // Set the executor of each language.
          "code-runner.executorMap": {
        "javascript": "node",
        "java": "cd $dir && javac $fileName && java $fileNameWithoutExt",
            "c": "cd $dir && gcc $fileName -o $fileNameWithoutExt &&       $dir$fileNameWithoutExt",
        "cpp": "cd $dir && g++ $fileName -o $fileNameWithoutExt &&    $dir$fileNameWithoutExt",
        "objective-c": "cd $dir && gcc -framework Cocoa $fileName -o $fileNameWithoutExt && $dir$fileNameWithoutExt",
         "php": "php",
        "python": "python",
        "perl": "perl",
        "perl6": "perl6",
        "ruby": "ruby",
        "go": "go run",
        "lua": "lua",
        "groovy": "groovy",
        "powershell": "powershell -ExecutionPolicy ByPass -File",
        "bat": "cmd /c",
        "shellscript": "bash",
        "fsharp": "fsi",
        "csharp": "scriptcs",
        "vbscript": "cscript //Nologo",
        "typescript": "ts-node",
        "coffeescript": "coffee",
        "scala": "scala",
        "swift": "swift",
        "julia": "julia",
        "crystal": "crystal",
        "ocaml": "ocaml",
        "r": "Rscript",
        "applescript": "osascript",
        "clojure": "lein exec",
        "haxe": "haxe --cwd $dirWithoutTrailingSlash --run $fileNameWithoutExt",
        "rust": "cd $dir && rustc $fileName && $dir$fileNameWithoutExt",
        "racket": "racket",
        "ahk": "autohotkey",
        "autoit": "autoit3",
        "dart": "dart",
        "pascal": "cd $dir && fpc $fileName && $dir$fileNameWithoutExt",
        "d": "cd $dir && dmd $fileName && $dir$fileNameWithoutExt",
        "haskell": "runhaskell",
        "nim": "nim compile --verbosity:0 --hints:off --run"
      },
    
this is the executor map, should I change it to the gcc folder for example(?) I'm not quite understand , Is this where my project located or where gcc located?

maybe I was wrong when edit some path? and I even uninstalled vs code, and install it again but these keep showing!

**Comment by formulahendry** [comment]
Could you share the screenshot of the output?

**Comment by devxsss** [comment]
![screenshot 137](https://user-images.githubusercontent.com/37922324/38127450-5d679c88-3420-11e8-92eb-e485f2ff2b4e.png)
thankyou for the fast reply, first time I installed it, it run smoothly and I can saw the output, maybe I changed wrong code(?) it produced this. Is there anyway to restart the setting? thanks!

**Comment by formulahendry** [comment]
You change the setting by yourself, you need to delete it.
![image](https://user-images.githubusercontent.com/1050213/38128245-548a37fe-342c-11e8-9335-6de2a07fdfb9.png)

**Comment by formulahendry** [comment]
If you want to customize, refer to the `Supported customized parameters` in https://github.com/formulahendry/vscode-code-runner#configuration

**Comment by devxsss** [comment]
![screenshot 139](https://user-images.githubusercontent.com/37922324/38128835-7a8b19ce-3426-11e8-8657-0a660bdd62e7.png)
i delete the cpp one, but produce the last line in terminal, what should i do?
do you mean i don't have to change anything for executor map?

**Comment by formulahendry** [comment]
Does the mainn.cpp run as expected? What's your expected behavior?

**Comment by devxsss** [comment]
it run, but can i change the output in terminal like in your demo? and also showing time execution ? in your demo it is so neat, beside can i debug here too?

**Comment by formulahendry** [comment]
You could just set `runInTerminal` to `false`

**Comment by formulahendry** [comment]
And this extension does not support debug

**Comment by devxsss** [comment]
![screenshot 141](https://user-images.githubusercontent.com/37922324/38136531-3c042010-3449-11e8-958d-eeaab7880b95.png)
thanks, i set runinterminal to false, but the program running like this but no input shown?

**Comment by formulahendry** [comment]
Yes, for input support. need to set runinterminal to true.
