### ISSUE TITLE
run code hotkey (ctrl + alt + n) doesn't work

### ISSUE THREAD

**Issue by jasonhuang1115** [formulahendry/vscode-code-runner#286]
Hi, 

I am running VSCode 1.21.1 on Windows 10. Pretty vanilla installation without much customizations.
When pressing ctrl+alt+N, nothing happened in VSCode, not even an error message. Right mouse click to run code and the play button on top right corner to run code work fine.

I tried 4 main hotkeys of Run Code (Ctrl + Alt + J, N, K, M). Only the `Ctrl+Alt+M` responds but it's due to that hotkey is assigned to send Mel code to Maya.

Anyone experiencing this?

**Comment by formulahendry** [comment]
> send Mel code to Maya

Sorry, I did not get you. Could you explain more?
And could you disable all other extension and try again? Sometimes, there is key binding conflict with extensions.

**Comment by jasonhuang1115** [comment]
Hi, I have just tried with the mayaPort extension disabled and experienced the same issue.
Basically, when I hit ctrl+alt+N, nothing happens. The hotkey doesn't work for me. But if I right-click and click on Run Code, it works fine. Or if I click the "play" button on the top right corner to run code, it works fine too.

**Comment by formulahendry** [comment]
Could you try updating the key bindings? https://code.visualstudio.com/docs/getstarted/keybindings#_keyboard-shortcuts-editor

**Comment by jasonhuang1115** [comment]
So I removed the keybinding for Run Code through the Keyboard Shortcuts (Right click -> Remove keybindings). Now the Run Code keybinding is empty and the source shows User (instead of Default). Then Right click -> Add Keybinding, VSCode wouldn't let me press Ctrl+Alt+n to add the keybinding. I then Right click -> reset keybinding to set it back.  Still, after all this, the hotkey still doesn't work...
VSCode didn't detect any keybinding conflict for ctrl+alt+n.

**Comment by jasonhuang1115** [comment]
I set the keybinding to something else and it works like a charm. Thanks! Not sure why the default keybinding doesn't work though.

**Comment by formulahendry** [comment]
Good to know it is working for other keybinding. Closing this then.

**Comment by KRSatpute** [comment]
This was working properly for me until recent VSCode update. Now character "ṇ" gets printed even if ctrl+alt+N is mapped to Run Code in key mappings.

This is definitely a issue that needs fixing.

Not working in version 1.31.1. Was working before that.

As mentioned above a different key binding works but default behavior should not change abruptly.

**Comment by diego-quiroga** [comment]
Found the same issue today. Even the mapping is there it does not work.

**Comment by falcon97** [comment]
The key mapping doesn't work after VSCode updated to v1.31.1. Please fix this issue.

**Comment by KRSatpute** [comment]
This is happening specifically for ctrl+alt combination keys.... the alternative of mapping a different key binding works fine.

**Comment by jithintomz** [comment]
Issue still persists in version 1.33.0

**Comment by Satanic-temple** [comment]
i got the same problem, by pressing CTRL+ALT+N it showed up a "ṇ" character. but i tried the same old formula. i restarted my system. and guess what ? **it worked**.

**Comment by Yinimi** [comment]
Hi, with US international keyboard layout I get an ñ so it is still not completly fixed I guess.

**Comment by nishnat-rishi** [comment]
Steps to fix:

- Go to 'Advanced keyboard settings'. Ensure the drop-down menu option under 'Override for default input method' is set to 'Use language list (Recommended)'.
- Go to 'Language settings', Make sure under 'Preferred languages', first option is set to 'English (United States)'. Click on it. Click on 'Options'.
- Under 'Keyboards', remove whatever keyboard is there, and add 'US' keyboard instead.

It should be fixed now.

I believe the offending keyboard is 'English (India)', because the 'ṇ' character (and you can produce other such 'weird' characters with Ctrl+Alt+\<letter\>) is a Devanagari transliteration character used to write phonetically correct Devanagari words in Romanized form.

**Comment by nishnat-rishi** [comment]
> This was working properly for me until recent VSCode update. Now character "ṇ" gets printed even if ctrl+alt+N is mapped to Run Code in key mappings.
> 
> This is definitely a issue that needs fixing.
> 
> Not working in version 1.31.1. Was working before that.
> 
> As mentioned above a different key binding works but default behavior should not change abruptly.

Steps to fix:

Go to 'Advanced keyboard settings'. Ensure the drop-down menu option under 'Override for default input method' is set to 'Use language list (Recommended)'.
Go to 'Language settings', Make sure under 'Preferred languages', first option is set to 'English (United States)'. Click on it. Click on 'Options'.
Under 'Keyboards', remove whatever keyboard is there, and add 'US' keyboard instead.
It should be fixed now.

I believe the offending keyboard is 'English (India)', because the 'ṇ' character (and you can produce other such 'weird' characters with Ctrl+Alt+<letter>) is a Devanagari transliteration character used to write phonetically correct Devanagari words in Romanized form.

**Comment by sunny0910** [comment]
The fix by @nishnat-rishi works. Thanks a lot.
Just to add something to his comment, he refers to the 'Advance keyboard settings' of the OS.
I spend some time to search advance keyboard settings in VSCode, lol.

**Comment by Surendarrajan3737** [comment]
> 
> 
> The fix by @nishnat-rishi works. Thanks a lot.
> Just to add something to his comment, he refers to the 'Advance keyboard settings' of the OS.
> I spent some considerable time trying to search advance keyboard settings in VSCode, lol.

Bro how to enter into 'Advanced Keyboard settings'

**Comment by nishnat-rishi** [comment]
> Just to add something to his comment, he refers to the 'Advance keyboard settings' of the OS.

Added the distinction. Thank you! (And although it's a bit too late now, apologies nonetheless!)

**Comment by paolotormon** [comment]
For me, it's the extension 'Namespace Resolver' that caused this issue. There was a hotkey collision

**Comment by asifur-rahman1** [comment]
Just turn on the NumLock -_-

**Comment by NikhilKumarJha** [comment]
> 
> 
> Just turn on the NumLock -_-

Thank you this is simplest way ..

**Comment by Master-Faraz** [comment]
> 
> 
> Just turn on the NumLock -_-

Thanks bro

**Comment by nottnottloop** [comment]
> Just turn on the NumLock -_-

This worked for me too. But WHY does this work? It makes no sense...

**Comment by SourashisHeartHacker** [comment]
> 
> 
> The fix by @nishnat-rishi works. Thanks a lot.
> Just to add something to his comment, he refers to the 'Advance keyboard settings' of the OS.
> I spent some considerable time trying to search advance keyboard settings in VSCode, lol.

just to add something , if it is not working after changing language settings, then restart the pc, it will work them : )

**Comment by striver01** [comment]
We can set another keybinding instead of ctrl+alt+n and that works fine for me.

**Comment by amit920114** [comment]
> This was working properly for me until recent VSCode update. Now character "ṇ" gets printed even if ctrl+alt+N is mapped to Run Code in key mappings.
> 
> This is definitely a issue that needs fixing.
> 
> Not working in version 1.31.1. Was working before that.
> 
> As mentioned above a different key binding works but default behavior should not change abruptly.

Same issues occurred again i just updated vsc to latest one. 16th July 2021

**Comment by bhaskart488** [comment]
> > This was working properly for me until recent VSCode update. Now character "ṇ" gets printed even if ctrl+alt+N is mapped to Run Code in key mappings.
> > This is definitely a issue that needs fixing.
> > Not working in version 1.31.1. Was working before that.
> > As mentioned above a different key binding works but default behavior should not change abruptly.
> 
> Same issues occurred again i just updated vsc to latest one. 16th July 2021

Resolved on 17th July 2021.

### Just turn on NumLock :)

**Comment by Bukangliwayway** [comment]
Switch input language and keyboard layout back using key combinations: **windows key + spacebar**

**Comment by ItzYuzuruYT** [comment]
> > This was working properly for me until recent VSCode update. Now character "ṇ" gets printed even if ctrl+alt+N is mapped to Run Code in key mappings.
> > This is definitely a issue that needs fixing.
> > Not working in version 1.31.1. Was working before that.
> > As mentioned above a different key binding works but default behavior should not change abruptly.
> 
> Steps to fix:
> 
> Search for 'Advanced keyboard settings' in Windows 10 settings. Ensure the drop-down menu option under 'Override for default input method' is set to 'Use language list (Recommended)'.
> Go to 'Language settings', Make sure under 'Preferred languages', first option is set to 'English (United States)'. Click on it. Click on 'Options'.
> Under 'Keyboards', remove whatever keyboard is there, and add 'US' keyboard instead.
> It should be fixed now.
> 
> I believe the offending keyboard is 'English (India)', because the 'ṇ' character (and you can produce other such 'weird' characters with Ctrl+Alt+) is a Devanagari transliteration character used to write phonetically correct Devanagari words in Romanized form.

ty

**Comment by Akshay-K8** [comment]
Try with Num lock on and then press the command it will worked for me

**Comment by filipembcruz** [comment]
I changed the hotkey to (ctrl + alt + b) on File > Preferences > Keyboard Shortcuts

**Comment by codeharshil19272** [comment]
I am facing the similar issue discussed above and the sad part is I have tried all fixes I could as mentioned (except for Num Lock coz...I don't have a Num Lock due to a short keyboard [without NUMPAD😔]

**Comment by RishiK-jpg** [comment]
Hold on! There is a simple solution to this problem.
**Turn on your Num Lock key** and try Cltr+Alt+N . This will solve the issue :)

**Comment by RishiK-jpg** [comment]
> i got the same problem, by pressing CTRL+ALT+N it showed up a "ṇ" character. but i tried the same old formula. i restarted my system. and guess what ? **it worked**.

Guess what! **Turning on your NUM LOCK KEY** might solve the problem.

**Comment by nandish-nandhu** [comment]
Wow truning the NumLock worked that's GREAT ,thanks  ..... :)

**Comment by SahilKhan013** [comment]
> > Just turn on the NumLock -_-
> 
> This worked for me too. But WHY does this work? It makes no sense... if someone knows reply!

NumPad has some cyrillic letters stored in it, so when you turns it on the actual alphabet part of the keyboard goes off

**Comment by aniruddhss** [comment]
> Just turn on the NumLock -_-

Thanks a lot man
