### ISSUE TITLE
Doesn't work for AutoHotkey

### ISSUE THREAD

**Issue by john-cj** [formulahendry/vscode-code-runner#287]
Doesn't work for AutoHotkey.

Test script:

``` ahk
#singleInstance, force
f1::
	formatTime, currentDateTime,, yyMMdd_HHmmss
	sendInput, %currentDateTime%
return
```

There are no spaces or non-latin letters in the script name/path.

```
[Running] autohotkey "c:\Users\John\Desktop\DateTime.ahk"
'autohotkey' is not recognized as an internal or external command,
operable program or batch file.

[Done] exited with code=1 in 0.097 seconds
```

AutoHotkey is already added to the path:

```
"autohotkey": "\"C:\\Program Files\\AutoHotkey\\AutoHotkey.exe\""
```
VS Code version: 1.19.0.

**Comment by john-cj** [comment]
Well, realized. It should be

```
"ahk": "\"C:\\Program Files\\AutoHotkey\\AutoHotkey.exe\"",
```

Note, `ahk`, not `autohotkey`. I will not close this issue, because I think it should work for both `ahk` and `autohotkey`

**Comment by formulahendry** [comment]
It is based on the language id of your language extension:
![image](https://user-images.githubusercontent.com/1050213/38173775-2d2f2e32-35f6-11e8-9f5e-8a35ad2b4c34.png)

**Comment by john-cj** [comment]
Still, it looks very weird and inconsistent.

**Comment by thomasthomas11235** [comment]
How was this solved exactly? I'm getting the same error: 'autohotkey is not recognized...'

**Comment by vglzng** [comment]
Go to: File » Settings 
Search for: code-runner.executorMap
Click on: Edit settings in.json

Copy code in (if you have AutoHotkey default installation):  

`    "code-runner.executorMap": {
        "ahk": "\"C:\\Program Files\\AutoHotkey\\AutoHotkey.exe\""
    }`


* Referenced from:

[https://github.com/formulahendry/vscode-code-runner](url)
