### ISSUE TITLE
Rust: Runs `sh` instead of `rustc` when the first line is `#!`

### ISSUE THREAD

**Issue by cswl** [formulahendry/vscode-code-runner#288]
So in Rust code, if the first line is something like.. 
`#![allow(unreachable_code)]`

Code runner tries to run the file with sh .. `#!` is shebang ofcourse.. 
`/bin/sh: -c: line 0: syntax error near unexpected token `unreachable_code'`

Maybe we could first check the file extension then the shebang at least for Rust...

**Comment by formulahendry** [comment]
You could use this setting to avoid using shebang : `"code-runner.respectShebang": false`

**Comment by cswl** [comment]
But that would turn it off for all scripts wouldnt it?
Since Rust is a compiled language.. you wouldnt use a shebang..

I might wanna leave it on for other scripts ..

**Comment by formulahendry** [comment]
You may want to use this setting per different workspace.

**Comment by megapctr** [comment]
I decided to check out vscode yesterday and run into same problem. Here's a fix
![just add a comment before the false shebang](https://user-images.githubusercontent.com/4096683/43993483-809f8da0-9d8e-11e8-8124-4a6db19e2fd9.PNG)
