### ISSUE TITLE
command 'code-runner.run' not found

### ISSUE THREAD

**Issue by jmarandet** [formulahendry/vscode-code-runner#289]
I have 2 different computer, same VSCode (1.21.1), and same Code-Runner (0.9.3).
One is on Windows 7, and the other one is on Windows 10, but I am not sure that it is relevant...

The strange thing is that one is working fine (W7) and the other just crash when I want to run a code with the arrow-button (W10)...

On the one that fail, I can see this (debug mode on the right side) : 
![vscode_code-runner_0-9-3](https://user-images.githubusercontent.com/32270488/38334790-a4ca7902-385c-11e8-9fbc-16d1058af261.PNG)

On the one that works fine, I can see that : 
![vscode_code-runner_0-9-3_ok](https://user-images.githubusercontent.com/32270488/38334816-bfa2c270-385c-11e8-9a8b-f63873fd9d77.PNG)

It seems that the 'out/src' folder just vanished...

I tried to deactivate/reactivate ; and I also tried to uninstal/reinstal...
But without any success.
Do you understand anything about that stuff ?

**Comment by formulahendry** [comment]
I think it would be the issue VS Code not installing the extension correctly. In general, I would uninstal/reinstall to make it work.. However, it seeems not working is your case.. Maybe you would submit issue to VS Code for help.
