### ISSUE TITLE
Javascript module reference

### ISSUE THREAD

**Issue by rana** [formulahendry/vscode-code-runner#29]
Is there an obvious way to run this JavaScript snippet?
--- js code ---
require('moment')
console.log('--- start')
console.log('moment().format(): ', moment().format())
console.log('--- end')

--- output ---
[Running] node "c:\lab\temp-ackikjupmw.js"
--- start
C:\lab\temp-ackikjupmw.js:3
console.log('moment().format(): ', moment().format())
                                   ^

ReferenceError: moment is not defined
    at Object.<anonymous> (C:\lab\temp-ackikjupmw.js:3:36)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Function.Module.runMain (module.js:575:10)
    at startup (node.js:160:18)
    at node.js:449:3

[Done] exited with code=1 in 0.189 seconds

**Comment by formulahendry** [comment]
Hi @rana , do you have moment npm package installed in global or in `C:\lab\node_modules`?

**Comment by rana** [comment]
Hi @formulahendry, 

I love code-runner, very helpful. Hoping to use it more!

yes, the library is in 'C:\lab\node_modules\moment'. all node modules present after install. not sure about configuring setting up js with vscode-code-runner. Would be great if there was a little more documentation for JavaScript; otherwise, javascript calls without module references run well. Is this a simple case of user not configuring the tool?

Here are some additional questions i would love to see answer in documentation with an example:

1. Can i use require('some-lib') ? If so, how? May i see an example?
2. Can i use import syntax "import moment from 'moment'" ?  If so, how? May i see an example?

Thank you!

Rana

**Comment by formulahendry** [comment]
Hi @rana ,

For question 1, require('some-lib') is supported. Actually, running js with Code Runner has no difference with running your js file as `node C:\lab\your-file.js` in shell. Could you please try run `node C:\lab\your-file.js` in your shell (bash or CMD) to see the result?

For question 2, do you want to run js with es6 syntax?
You could install the [babel-node](https://babeljs.io/docs/usage/cli/): `npm install -g babel-cli`
And set `code-runner.executorMap` as below:
```json
{
    "code-runner.executorMap": {
        "javascript": "babel-node"
    }
}
```

**Comment by eudaimos** [comment]
@formulahendry @rana and anyone else who happens along to here, here's how to run your ES6/7 code **without** having to install `babel-cli` globally (considered not to be a best practice)
```json
    "code-runner.executorMap": {
      "javascript": "$workspaceRoot/node_modules/.bin/babel-node --harmony $fullFileName"
    }
```

The `--harmony` flag will be optional based on how you are using `babel-node`

**Comment by MVSICA-FICTA** [comment]
Works faster with `npm i esm`  then:

`
    "code-runner.executorMap": {
      "javascript": "node -r esm $fullFileName"
    }
`
