### ISSUE TITLE
Cleanup .exe after compilation

### ISSUE THREAD

**Issue by sulkhanp** [formulahendry/vscode-code-runner#295]
I searched and couldn't find for an option that cleans up/removes .exe's after compiling c++/go or any binaries.

**Comment by formulahendry** [comment]
Duplicated with #84

**Comment by suxosuxo123** [comment]
@formulahendry How is rm used to remove binaries? Where does it go?

**Comment by sulkhanp** [comment]
@formulahendry in #84 it is mentioned that it's possible to remove binaries with del/rm. Where would those commands go in the config?

**Comment by formulahendry** [comment]
You could customize the `"code-runner.executorMap"` config, refer to https://github.com/formulahendry/vscode-code-runner#configuration

**Comment by sulkhanp** [comment]
@formulahendry       
"cd $dir && g++ $fileName -o $fileNameWithoutExt && $dir$fileNameWithoutExt del $fileNameWithoutExt.exe"
This doesn't seem to be deleting the file.
