### ISSUE TITLE
I get error "No such file or directory" when I compile C code using gitbash as terminal

### ISSUE THREAD

**Issue by waithope** [formulahendry/vscode-code-runner#296]
Here is the output info:
```
$ cd "d:\VscodeProject\C\demo\" && gcc file1.c -o file1 && "d:\VscodeProject\C\demo\"file1
bash: cd: d:\VscodeProject\C\demo" && gcc file1.c -o file1 && d:VscodeProjectCdemo"file1: No such file or directory

```

### How can I fix it?

**Comment by formulahendry** [comment]
What's your the path of your Git Bash?
Could you set `"code-runner.terminalRoot": "/"`, and try again?

**Comment by waithope** [comment]
@formulahendry, it works. Thank you for the prompt reply.

**Comment by RockerSurajThakur** [comment]
I didn't get the answer please elaborate

**Comment by RockerSurajThakur** [comment]
Guys I was trying to execute C programme for last 3 days but didn't get the answer but today I worked hard and finally it worked for me.

Please try this for C programme
"c": "gcc $fileNameWithoutExt.c -o $fileNameWithoutExt && ./$fileNameWithoutExt.exe"

for cpp
"c": "g++ $fileNameWithoutExt.c -o $fileNameWithoutExt && ./$fileNameWithoutExt.exe"

**Comment by devsungyeon** [comment]
it works. thx!

**Comment by yons101** [comment]
RockerSurajThakur

> Guys I was trying to execute C programme for last 3 days but didn't get the answer but today I worked hard and finally it worked for me.
> 
> Please try this for C programme
> "c": "gcc $fileNameWithoutExt.c -o $fileNameWithoutExt && ./$fileNameWithoutExt.exe"
> 
> for cpp
> "c": "g++ $fileNameWithoutExt.c -o $fileNameWithoutExt && ./$fileNameWithoutExt.exe"

All of a sudden my previous setup stopped working, thank you @RockerSurajThakur, this works

**Comment by Dhaval1112000** [comment]
> I didn't get the answer please elaborate
Simply go to the settings and open the settings.json file. Paste this thing
                            "code-runner.terminalRoot": "/"
in the file and you are ready to go

**Comment by deepakpandey710** [comment]
@Dhaval1112000  it works thank you so much

**Comment by luffylovesmeat** [comment]
> I didn't get the answer please elaborate

press ctrl+shift+p then search settings and open settings.json and add the line "code-runner.terminalRoot": "/" to the code

**Comment by adi1719** [comment]
> 

didn't work

cd : Cannot find path 'C:\Users\adira\Desktop\C Tutorials\truec\Users\adira\Desktop\C Tutorials\' because it does not exist.
At line:1 char:1
+ cd "truec/Users/adira/Desktop/C Tutorials/" ; if ($?) { gcc If else s ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\adira\...op\C Tutorials\:String) [Set-Location], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.SetLocationCommand

**Comment by Himanshupegu** [comment]
> > I didn't get the answer please elaborate
> 
> press ctrl+shift+p then search settings and open settings.json and add the line "code-runner.terminalRoot": "/" to the code

Thanks it works

**Comment by Agustinez02** [comment]
> ¿Cuál es el camino de tu Git Bash? ¿Podría configurar y volver a intentarlo?`"code-runner.terminalRoot": "/"`

Graaaaciaaaa 

> What's the path of your Git Bash? Could you set `"code-runner.terminalRoot": "/"`, and try again?

thaaaaanks bro, i love you

**Comment by dneovu** [comment]
thanks!
