### ISSUE TITLE
python3 UnicodeEncodeError?

### ISSUE THREAD

**Issue by lgqfhwy** [formulahendry/vscode-code-runner#303]
I am using Mac, vscode, code-runner-0.9.3. I meet a program that when I want to open a text and print the context, code-runner run the program raise error.
<img width="981" alt="screen shot 2018-05-08 at 17 43 33" src="https://user-images.githubusercontent.com/16728136/39750319-802d8d82-52e7-11e8-8155-a8c75fbd4c16.png">
I google this error, someone said I should  open the text using utf-8(actually I used), and set bash environment to utf-8 (actually I used). But when I run this code in the terminal, it is no error, run success.
<img width="729" alt="screen shot 2018-05-08 at 17 46 58" src="https://user-images.githubusercontent.com/16728136/39750447-da277604-52e7-11e8-81ce-b407dca39f4f.png">
So I guess maybe code-runner have some problem, I want to solve this problem, I am a beginner, please help me, thank you so much!

**Comment by formulahendry** [comment]
You could use below setting (`File`->`Preference`->`Settings`) to run code in Integrated Terminal:
```json
{
    "code-runner.runInTerminal": true
}
```
