### ISSUE TITLE
Python3.6 module import error

### ISSUE THREAD

**Issue by fullstackpythondeveloper** [formulahendry/vscode-code-runner#304]
When trying to run script via code runner within virtual environment. it shows,
ImportError: No module named queue

FYI. from queue import Queue

However, when I run the script in terminal, the script works well, a potential bug?

**Comment by fullstackpythondeveloper** [comment]
Have set. It will show up in terminal, but not in output, anyway, it works out.

**Comment by Thomas-Hartmann** [comment]
Where should we put this setting?

**Comment by formulahendry** [comment]
@Thomas-Hartmann  Please refer to https://code.visualstudio.com/docs/getstarted/settings#_creating-user-and-workspace-settings
