### ISSUE TITLE
RunCode 不能正常工作，意外结束退出

### ISSUE THREAD

**Issue by yz9968** [formulahendry/vscode-code-runner#307]
你好，我在完成配置以后安装Run Code插件遇到了很奇怪的问题，调试时弹出命令行窗口运行正常，偶尔会有奇怪的异常抛出，但是直接Run Code时就常常意外停止，比如简单的循环，循环尚未结束就会停止循环直接运行到system("pause")语句。另外就是Run Code时终端经常会有如下信息输出：PS E:\VSCode> d "e:\VSCode" ; if ($?) { clang++ jj.cpp -o jj.exe -Wall -g -Og -static-libgcc -fcolor-diagnostics --target=x86_64-w64-mingw -std=c++17 } ; if ($?) { .\jj }    但按理命令最先的应该是cd，有时在程序运行中也会出现这个信息，没能查到相应的问题解决方案，想请教一下这是为什么？

**Comment by formulahendry** [comment]
> 另外就是Run Code时终端经常会有如下信息输出

What's the expected output?

**Comment by yz9968** [comment]
For example, I wrote a little program which use a simple loop to print the numbers between 1 and 1,000. The expected output is 1, 2, 3...1001. Just like the picture:
![image](https://user-images.githubusercontent.com/30971346/42681110-6a366e30-86b9-11e8-963f-7a998869e3ab.png)

 However, if I run the code in terminal, the code runner only shows several numbers, like 1,2,3,  then it stopped and jumped to  the 'system("pause")'. 
![image](https://user-images.githubusercontent.com/30971346/42681150-7d55247a-86b9-11e8-9d6e-850925d0a573.png)

But if I turned the "code-runner.runInTerminal" option into false, the output is as expected though the Chinese words are not shown correctly.
![image](https://user-images.githubusercontent.com/30971346/42681318-eb781ca0-86b9-11e8-8ee7-033fbb83cd85.png)

Just few days ago, I reported another issue, in which you helped me to solve the ' cd or d' problem, but this problem still exists. Thanks for your kindness and hope that you can reply to me. 
Best wishes!

**Comment by formulahendry** [comment]
Reply in https://github.com/formulahendry/vscode-code-runner/issues/328#issuecomment-409806842
