### ISSUE TITLE
can not support utf-8

### ISSUE THREAD

**Issue by veryrich** [formulahendry/vscode-code-runner#308]
hi , i follow #25 , but not working.

my setting :
![image](https://user-images.githubusercontent.com/12951051/40101052-bdfabebe-5918-11e8-979b-e685301ff6c0.png)

my code:
![image](https://user-images.githubusercontent.com/12951051/40101229-60bed5ae-5919-11e8-8ced-4f928f00eea8.png)

i want to using Python3 with utf-8.

but i run this file in terminal , is fine:
![image](https://user-images.githubusercontent.com/12951051/40101285-921cb1ca-5919-11e8-83ee-48b6c38676d9.png)

**Comment by zfh1005** [comment]
The setting will be like this:
![image](https://user-images.githubusercontent.com/1957276/40215197-c31d41d0-5a91-11e8-8fdb-3b6050f51079.png)

**Comment by formulahendry** [comment]
Thanks @zfh1005 !
