### ISSUE TITLE
怎么在Mac环境下运行python3.6

### ISSUE THREAD

**Issue by tomcatone** [formulahendry/vscode-code-runner#314]
我使用它的时候一直提示Traceback (most recent call last):
  File "/Users/huchao/Documents/tom/PromoCode.py", line 2, in <module>
但是使用终端运行无异常

**Comment by formulahendry** [comment]
Could you share the sreenshort?
And what if you run with below setting?
```json
{
    "code-runner.runInTerminal": true
}
```

**Comment by tomcati** [comment]
我已经搞定了谢谢大佬
