### ISSUE TITLE
tempCodeRunnerFile.cr doesn't exist on Windows

### ISSUE THREAD

**Issue by BenDietze** [formulahendry/vscode-code-runner#316]
I tried this extension on Windows, but if i run it, the following error occurs:

![image](https://user-images.githubusercontent.com/39699022/41159886-53154146-6b2e-11e8-8c3e-c724336ac7c3.png)

If i put the file manually there it just was deleted and the error occurs again.

I tried to protect the file, then code-runner hangs; if i remove protection, it just deletes the file again.

_crystal.bat_ is a redirection to crystal command on windows bash.

Just for info: on linux everything is ok...

**Comment by formulahendry** [comment]
I guess it is due to the file path is Windows style.
You could try set the terminal to wsl: https://code.visualstudio.com/docs/editor/integrated-terminal#_windows, and use below setting (`File`->`Preference`->`Settings`) to run code in Integrated Terminal:
```json
{
    "code-runner.runInTerminal": true
}
```

**Comment by BenDietze** [comment]
Thank you, i will try this at home, but it just deletes the needed file everytime i manually create it - so i think the path would be correct? Because of this i create exactly such a file (name), trying to get another error and come closer, but it only deletes this tempfile and does nothing else then erroring file tempCodeRunnerFile.cr does not exist...

I will try look at it :)
