### ISSUE TITLE
package.json browser alias values not picked up

### ISSUE THREAD

**Issue by lvl99** [formulahendry/vscode-code-runner#317]
Attempting to run some javascript with `require()` functions and I'm not sure if I have to specify the `package.json` somewhere in the Code Runner config or if it could detect one by default, but it would be great to do that for picking up the `browser` aliases for custom module locations.

**Comment by formulahendry** [comment]
Sorry, what does `browser` aliases  mean? What if you run the same js file in terminal?

**Comment by lvl99** [comment]
I think the problem I had was that my JS code relies on a build step which uses `browserify` and [`browserify-shim`](https://github.com/thlorenz/browserify-shim) which uses the `browser` property as a collection of aliases to shim `require()` function calls with the aliased path/name before it can run.

It's probably outside the scope of what Code Runner should consider. But otherwise, continue reading...

You can see the [package.json `browser` spec proposal here](https://github.com/defunctzombie/package-browser-field-spec), but I don't know if it's entirely applicable for Code Runner? Would be great if it could some how work as aliases when requiring/importing files. The main idea of using `browserify-shim` is to refer to local files with consistent keywords, rather than long relative paths (e.g. `module-alias` instead of `../../../path/to/module`).

The ideal could be that Code Runner checks that path/package name is in package.json `browser` field, if so then resolves the value path/package from that:

```
// package.json
{
  "browser": {
    "test-a": "../path/to/test-a.js",
    "test-b": "test-c"
  }
}
```
```
// test.js
const testA = require("test-a"); // would import from "../path/to/test-a.js"
const testB = require("test-b"); // would import from "<rootDir>/node_modules/test-c"
```

**Comment by formulahendry** [comment]
It seems out of scope of Code Runner. Code Runner only take care of your NodeJS file not code inside it. e.g. `node /foo/bar/abc.js`
