### ISSUE TITLE
Focus on code window while/after run

### ISSUE THREAD

**Issue by eisisig** [formulahendry/vscode-code-runner#32]
Any way to keep the focus in the code window when running? Adding option to this plugin or is there any known way already?

I have it open in CS Code terminal in window and after run the cursor is in the terminal so I have to manually click the code again, and then, and then...

👍  this plugin!

**Comment by eisisig** [comment]
Actually found a solution that works for me. I use https://github.com/callumlocke/esbox as a executorMap.javascript runner. That starts esbox with my code and watches it

**Comment by formulahendry** [comment]
Thanks for reporting the issue. I will fix it.

**Comment by formulahendry** [comment]
@eisisig , this issue has been fixed. Please try the latest version.

**Comment by eisisig** [comment]
@formulahendry Thank you for this fix! Much appreciated

**Comment by ralfuslongus** [comment]
preserveFocus** does not work (for me) any more:
I am using code-runner with crystal-lang and i try to keep the focus on the editor while using the terminal for coloured output. The "preserveFocus" only works on the default output window of vscode, which unfortunately does not support coloured output of the program. 
vscode version : 1.50.1
code-runner version: 0.11.1
code-runner settings:
    "code-runner.clearPreviousOutput": true,
    "code-runner.ignoreSelection": true,
    "code-runner.saveAllFilesBeforeRun": true,
    "code-runner.saveFileBeforeRun": true,
    **"code-runner.preserveFocus":** true,
    **"code-runner.runInTerminal":** true
