### ISSUE TITLE
“start” can only run in terminal

### ISSUE THREAD

**Issue by linsui** [formulahendry/vscode-code-runner#325]
我把html的运行命令设置为start，使文件在默认浏览器中打开以便使用edge。但当我使用集成终端时会弹出cmd，而我将run in terminal设置为true后可以顺利在Edge中打开。是否有办法在集成终端使用start命令？或者我应该使用其他命令？
I set the HTML run command to “start” so that the file opens in the default browser to use the Edge. However, when I use the integration terminal, CMD will pop up, and I set “run in terminal” to true, which can be opened in Edge smoothly. Is there any way to use the start command at the integration terminal? Or should I use other commands?

**Comment by linsui** [comment]
是的，我希望可以在使用集成的code终端时达到相同效果。我找到方法了，运行命令设置为`""`就可以在集成终端调用系统默认浏览器打开html文件。请问是否有办法设置`"code-runner.executorMapByFileExtension"`在`"code-runner.runInTerminal"`不同时执行不同命令？

**Comment by linsui** [comment]
是的，因为有些命令在集成终端和外部终端不一样。

**Comment by formulahendry** [comment]
Could you share some examples? I want to know how many scenario it would happen, and decide whether to support that.

**Comment by linsui** [comment]
抱歉我发现我之前的理解有误。请问code runner不在终端运行时使用的是cmd吗，vscode默认集成终端是powershell,所以命令有些区别

**Comment by formulahendry** [comment]
Could you share the screenshot or GIF?
