### ISSUE TITLE
The Code Runner couldn't work as expected

### ISSUE THREAD

**Issue by yz9968** [formulahendry/vscode-code-runner#328]
recently I used the Code Runner to run python program which works perfectly, but when I try to compile and run C or C++ programs, the problem I mentioned before still exists. Here are some screenshots.
![image](https://user-images.githubusercontent.com/30971346/42429784-d1639f5a-836d-11e8-9911-041c81309d7a.png)

    In this simple program, I tried to print integers in the constant loop, but it ends like the following picture and won't response any more:
![image](https://user-images.githubusercontent.com/30971346/42429790-db859c54-836d-11e8-8fd8-710548ba1ea2.png)

And some times, it ends like this:
![image](https://user-images.githubusercontent.com/30971346/42429801-e5fb60e2-836d-11e8-9eae-b6341ac16f17.png)

The yellow words should be "cd" but turned out to be "d" which makes the program fail to compile.
Thanks for your help! And apologize for my interruption and poor English.

**Comment by yz9968** [comment]
By the way, this situation just happens when I try to compile and run c++ code. The code runner works perfectly when I try to run python code.

**Comment by formulahendry** [comment]
>  "cd" but turned out to be "d"

This is mostly likely due to the 'c' is eaten by your previous program. Please stop your previous program and try again.

Feel free to reopen the issue if you still meet with this issue

**Comment by yz9968** [comment]
First of all, I want to thank you for helping me. The 'd' problem is surely due to the previous program is not stopped. But there is another problem: the program often stops before where it should finish. Here is an example. The first picture shows the right result, while another shows the result that really happens.

![image](https://user-images.githubusercontent.com/30971346/42458319-4298ded4-83cc-11e8-869a-7ef08230d722.png)
![image](https://user-images.githubusercontent.com/30971346/42458380-6aecaa28-83cc-11e8-868f-f95ab31c4cef.png)

**Comment by yz9968** [comment]
And here is another incorrect result. Thank you for your kindness!
![image](https://user-images.githubusercontent.com/30971346/42458704-d8d858b6-83cc-11e8-8e1c-3d936fbcf6f6.png)

**Comment by formulahendry** [comment]
What if you run the same program if VS Code terminal directly?

**Comment by yz9968** [comment]
Do you mean that run in the VS Code terminal directly? I have tried to turn the 'runinTerminal' option of Code Runner into 'true', is this what you mean? Or there is another way to run the program in terminal directly?

**Comment by formulahendry** [comment]
Just copy/paste the run command `cd "e:***" *** clang++ ***` in terminal and press `enter`.

**Comment by yz9968** [comment]
It shows the same result. Just stopped half-way through.
![image](https://user-images.githubusercontent.com/30971346/42926731-dae0e8ae-8b64-11e8-8e7d-b211083f5bbd.png)
![image](https://user-images.githubusercontent.com/30971346/42926744-e1c2bd3c-8b64-11e8-985c-89aaf2a8c18d.png)

**Comment by formulahendry** [comment]
So it should be the problem of VS Code or your own program, Obviously, it is not related to Code Runner.
