### ISSUE TITLE
executorMapByFileExtension Not Working As Expected

### ISSUE THREAD

**Issue by NavyAdmiral** [formulahendry/vscode-code-runner#329]
Hi. I have a  .someExtension file that I want to associate with Python because of syntax highlighting. I have also set the following settings:
```js
  "code-runner.executorMapByFileExtension": {
      ".someExtension": "bash \"emu ./$fileName\""
  },
    "files.associations": {
    "*.someExtension": "python"
  }
```
I get unexpected behavior, Code Runner runs py $fileName, because I associated .someExtension to Python in vsCode. However, executorMapByFileExtension should disregard the association and only take the file extension into account.

**Comment by NavyAdmiral** [comment]
@formulahendry

**Comment by formulahendry** [comment]
executorMap has higher priority than executorMapByFileExtension, so you need to set undefined for python.

```json
"code-runner.executorMap": {
        "python": undefined 
    }
```

**Comment by NavyAdmiral** [comment]
@formulahendry I don't think this is a solution, because I have already mapped "python" to `py`.

**Comment by formulahendry** [comment]
Could you have a screenshot of your settings?

**Comment by formulahendry** [comment]
```json
"code-runner.executorMapByFileExtension": {
      ".someExtension": "bash \"emu ./$fileName\"",
      ".py": "python"
  },
"code-runner.executorMap": {
        "python": undefined 
    }
```

**Comment by sulkhanp** [comment]
These are my settings exactly:
@formulahendry 
```
  "code-runner.executorMap": {
    "python": "py"
  },
  "code-runner.executorMapByFileExtension": {
    ".sage": "bash -c -i \"sage ./$fileName\""
  },
  "files.associations": {
    "*.sage": "python"
  }
```
Problems: I want to run all Python files with $ py fileName and all sage files with bash.

**Comment by formulahendry** [comment]
Below settings could just work:
```json
"code-runner.executorMapByFileExtension": {
      ".sage": "bash \"emu ./$fileName\"",
      ".py": "python"
  },
"code-runner.executorMap": {
        "python": undefined 
    }
```

**Comment by sulkhanp** [comment]
@formulahendry 
I tried that, undefined doesn't seem to work. Those settings will run  .sage file incorrectly:
```
[Running] python "c:\Users\User\Desktop\Math\file.sage"
```

**Comment by NavyAdmiral** [comment]
@formulahendry 
I tried that, undefined doesn't seem to work. Those settings will run  .sage file incorrectly:
```
[Running] python "c:\Users\User\Desktop\Math\file.sage"
```
Those settings also break python:
```
[Running] python "c:\Users\User\Desktop\Python\file.py"
```

I want to run with $py$, not $python$.

These are my settings exactly:
@formulahendry 
```json
  "code-runner.executorMap": {
    "python": "py"
  },
  "code-runner.executorMapByFileExtension": {
    ".sage": "bash -c -i \"sage ./$fileName\""
  },
  "files.associations": {
    "*.sage": "python"
  }
```
Problems: I want to run all Python files with $ py fileName and all sage files with bash.

**Comment by NavyAdmiral** [comment]
@formulahendry did you take a look at this? i'm pretty sure something's bugged

**Comment by formulahendry** [comment]
Seems that it should be `null` not `undefined`:
```json
"code-runner.executorMapByFileExtension": {
      ".sage": "bash \"emu ./$fileName\"",
      ".py": "python"
  },
"code-runner.executorMap": {
        "python": null
    }
```
![image](https://user-images.githubusercontent.com/1050213/43563266-e9ee347e-9653-11e8-9079-565dd5a14ad2.png)
