### ISSUE TITLE
set env variable  before  excuting python file

### ISSUE THREAD

**Issue by sunqi1993** [formulahendry/vscode-code-runner#33]
First of all,thanks for your ext! It's really awesome
on windows
the default encoding of cmd is cp936,but the this ext output default is utf8 that will case a decoding problem,
like this:
![image](https://cloud.githubusercontent.com/assets/12682690/20419453/7a6b679a-ad91-11e6-8dab-bfb664c5b593.png)

i wonder if it's better to add a feature for some language to set the environment variable before executing *.py file

like the task.json
![image](https://cloud.githubusercontent.com/assets/12682690/20419551/3fc9d670-ad92-11e6-8246-6481b7a6c97b.png)

**Comment by sunqi1993** [comment]
..... 
I made a mistake,"code-runner.executorMap"  can solve this  @problem

**Comment by formulahendry** [comment]
Just curious how you resolve this? 😄

**Comment by sunqi1993** [comment]
![image](https://cloud.githubusercontent.com/assets/12682690/20649751/3b8ae812-b501-11e6-87cc-640d2ec0e0a6.png)

==.... , I see it in your blog !!! haha

**Comment by formulahendry** [comment]
Awesome! 👍
