### ISSUE TITLE
The Code Runner Always Interrupt While Running C++ Programs

### ISSUE THREAD

**Issue by yz9968** [formulahendry/vscode-code-runner#331]
For example, I wrote a little program which use a simple loop to print the numbers between 1 and 1,000. The expected output is 1, 2, 3...1001. Just like the picture:
![image](https://user-images.githubusercontent.com/30971346/42681110-6a366e30-86b9-11e8-963f-7a998869e3ab.png)

 However, if I run the code in terminal, the code runner only shows several numbers, like 1,2,3,  then it stopped and jumped to  the 'system("pause")'. 
![image](https://user-images.githubusercontent.com/30971346/42681150-7d55247a-86b9-11e8-9d6e-850925d0a573.png)

But if I turned the "code-runner.runInTerminal" option into false, the output is as expected though the Chinese words are not shown correctly.
![image](https://user-images.githubusercontent.com/30971346/42681318-eb781ca0-86b9-11e8-8ee7-033fbb83cd85.png)

Just few days ago, I reported another issue, in which you helped me to solve the ' cd or d' problem, but this problem still exists. Thanks for your kindness and hope that you can reply to me. 

I'm really sorry that I bothered you too much. I'm really grateful that you are always there.

Best wishes!

**Comment by formulahendry** [comment]
Reply in https://github.com/formulahendry/vscode-code-runner/issues/328#issuecomment-409806842
