### ISSUE TITLE
I am a new users of VS Code,and i don't know the hotkey on Mac.

### ISSUE THREAD

**Issue by lihui2333** [formulahendry/vscode-code-runner#332]
I am a new user of VS Code.I tried command+option+n,command+control+n,control+option+n,it did not work.

**Comment by formulahendry** [comment]
You should be able to see it on context menu
![image](https://user-images.githubusercontent.com/1050213/43563674-d6c58c7e-9655-11e8-891a-ebe319cb184d.png)
