### ISSUE TITLE
"cannot edit in read only editor"

### ISSUE THREAD

**Issue by jiggyOne** [formulahendry/vscode-code-runner#335]
Issue Type: <b>Bug</b>

i downloaded code runner to run scripts in python but when when i want to run a script where i must type a value i can't and a message "cannot edit in read only editor" appear

Extension version: 0.9.3
VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:43:53.668Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Celeron(R) CPU  N3060  @ 1.60GHz (2 x 1600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|3.92GB (1.57GB free)|
|Process Argv|C:\Program Files (x86)\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by formulahendry** [comment]
Please refer to #91

**Comment by Maqueen1** [comment]
had a similar problem but working on it now...i already started to like VS code and now that happend damn!

**Comment by mlabwa1** [comment]
Just turn code-runner.runInTerminal to true from your File -> Preferences -> Settings

**Comment by jiggyOne** [comment]
Thanks a lot
May Jesus bless you

Sent from my iPhone

On Oct 15, 2018, at 4:18 PM, Daniel Mlabwa <notifications@github.com<mailto:notifications@github.com>> wrote:


Just turn code-runner.runInTerminal to true from your File -> Preferences -> Settings

**Comment by nitish-xm** [comment]
Thanks A Lot Bro

**Comment by fmorace-kj** [comment]
Thanks a lot

**Comment by BlueSky7** [comment]
> i downloaded code runner to run scripts in python but when when i want to run a script where i must type a value i can't and a message "cannot edit in read only editor" appear

**Answer**

Two ways:
**(1)** In setting.json file => add this line- 
{
    "code-runner.runInTerminal": true
//    Other lines...
}
You are done!!
Or
**(2)** Follow these steps-
Step1. Go to File > Preference > Setting.
Step2. Then on the left panel, scroll and find 'Run Code Configuration'. 
Step3. Under that option: keep cursor on "code-runner.runInTerminal" and click on edit icon.
Step4: You will see two true & false option. Make it true. 
Step5: You are done!!

**Comment by insomnius** [comment]
Thanks bro.

**Comment by Olanetsoft** [comment]
thanks a lot bro.

**Comment by cleverboyhamza** [comment]
please hep me getting rid off "cannot edit in read only editor" on macbook pro vs code while using c++

**Comment by JoeMaesai** [comment]
Thank you

**Comment by rudestewing** [comment]
thank you

**Comment by Harsh-patel00** [comment]
What if I have to use OUTPUT window to enter the details and not on TERMINAL ?

**Comment by theking17082000** [comment]
I cant find it .Plz help

**Comment by khartel** [comment]
> What if I have to use OUTPUT window to enter the details and not on TERMINAL ?

Exactly my problem

**Comment by Vovamzur** [comment]
jsut run in terminal 
code .

**Comment by EGUS74** [comment]
> Just turn code-runner.runInTerminal to true from your File -> Preferences -> Settings

life saver... thanks dude!

**Comment by rama2021** [comment]
i think you just need to do right click inside the code area and chose Run Python File in Terminal 
and it will run the code in terminal window 
so you will not need to turn code-runner.runInTerminal to true from your File -> Preferences -> Settings
because if you will turn it to true so every time you have to run the code in output window you will need to turn it to false again 
so it's better to do the solution i maintained above

**Comment by Marines1775** [comment]
I've skimmed through all the reply's and they do work.   Are more settings supposed to be put in the settings.json file? maybe for better performance?    When you use terminal for the output,  you always get the path of the file you're running and the python executable.  Now if you don't need to do input for the file your running code runner works and if you do you have to run it in terminal.   Is there a better process?  Anyone know how to eliminate the path of the file and executable being run? 
Thank you in advance
