### ISSUE TITLE
Bug - Go to Definition

### ISSUE THREAD

**Issue by klapau12019** [formulahendry/vscode-code-runner#34]
Error by using the context menu "go to definition"
![gotodefinition](https://cloud.githubusercontent.com/assets/5271681/20638390/c92de554-b3a6-11e6-8145-75cf122010fd.JPG)

**Comment by formulahendry** [comment]
Hi @klapau12019 , this extension has no relation to "go to definition". Could you please share more about the repro steps?

**Comment by formulahendry** [comment]
Closing this, since it is not related to this extension
