### ISSUE TITLE
Code Runner invoke wrong python path

### ISSUE THREAD

**Issue by Anthorty** [formulahendry/vscode-code-runner#343]
When I use code runner to run my python code in Windows,I found it invoke the Linux command "/usr/bin/env python".it makes  me can't run code normally.
There is the error message:
```
G:\Python Learning>/usr/bin/env python3   "g:\Python Learning\tempCodeRunnerFile.py"
The system could not find the specified path.
```
 I already try to change `settings.json`,but it doesn't work.So how can I solve this problem?

**Comment by formulahendry** [comment]
It seems to use Shebang. You could update the config to ignore it: `"code-runner.respectShebang": false`

**Comment by huiguo2008** [comment]
@formulahendry,  It works, thanks!

**Comment by noubar** [comment]
![image](https://user-images.githubusercontent.com/29734506/124651491-468ee880-de9b-11eb-9e96-26a03873573e.png)

i had the same issue. I have solved it by activatin this setting under the code runner extension settings.
File DIrectory As Cwd

**Comment by AnxoB** [comment]
Thank you very much to those who made this thread because in my institute everything was misconfigured on my computer :)

**Comment by Louis24** [comment]
> "code-runner.respectShebang": false

真nb啊
