### ISSUE TITLE
How to compile multiple file at once? (C/C++)

### ISSUE THREAD

**Issue by HeeamShin** [formulahendry/vscode-code-runner#344]
I searched on the internet, but I cannot find how.  (except by terminal. Creating .o files and linking those files manually). But I want to do these process automatically (like ctrl+alt+F in Code Runner)
I want to know at least it can be possible or not in Code Runner.

Any comments will help me a lot!

Here are my codes.

testMain.c
```c
#include "test.h"

int main(int argc, char const *argv[])
{
   testFunc();
    return 0;
}
```

test.h
```c
#include <stdio.h>

void testFunc(void);
```

test.c
```c
#include "test.h"

void testFunc(void) {
    printf("I feel sad...");
}
```

Thank you.

**Comment by formulahendry** [comment]
You may refer to #184

**Comment by HeeamShin** [comment]
@formulahendry 
Thanks for the useful comment.
I solved the problem.

@to someone who don't know where to put the settings written in above (like me)
There is a "code-runner.executorMap" field in 'settings.json' file.
You modify the contents related to your build language.
If you want to build with C, modify the contents after "c":
