### ISSUE TITLE
bug,it's not work in .lua or .js file

### ISSUE THREAD

**Issue by xuyin58** [formulahendry/vscode-code-runner#35]
when i in office it's work good,but i at home it unworkable.
use same version vscode and code-runner.
![2016-11-27_023703](https://cloud.githubusercontent.com/assets/3367839/20642511/bcba2486-b44b-11e6-9eb5-8362a864cc4f.jpg)
![2016-11-27_024012](https://cloud.githubusercontent.com/assets/3367839/20642513/c0e066d8-b44b-11e6-887a-d9209d57d23d.jpg)

**Comment by formulahendry** [comment]
Hi @xuyin58 , is lua.exe or node.exe in your PATH environment variable? Please open your cmd and run `lua your-file-name.lua` or `node your-file-name.js` to see the result.

**Comment by xuyin58** [comment]
thanks I see.
