### ISSUE TITLE
I can't compile my c++ source code

### ISSUE THREAD

**Issue by Pierre8r** [formulahendry/vscode-code-runner#352]
Hello,

I'm trying to compile these sources files  [filesCPP.zip](https://github.com/formulahendry/vscode-code-runner/files/2333139/filesCPP.zip) and I have the following message:

> Windows PowerShell
Copyright (C) Microsoft Corporation. Tous droits réservés.
PS T:\VSCC++\LEssentiel> cd "t:\VSCC++\LEssentiel\chapitre 2  la programmation orientee objets\choisir_les_constructeurs\" ; if ($?) { g++ main.cpp -o main } ; if ($?) { .\main }je suis arthurje suis bob et je code c++
PS T:\VSCC++\LEssentiel\chapitre 2  la programmation orientee objets\choisir_les_constructeurs>
sir_les_constructeurs> cd "t:\VSCC++\LEssentiel\chapitre 2  la programmation orientee objets\l_enchainement_des_destructeurs\finale\" ; if ($?) { g++ main.cpp -o main } ; if ($?) { .\main }
C:\Users\Pierre\AppData\Local\Temp\ccSkLK4T.o:main.cpp:(.text+0x5c): undefined reference to `personne::personne(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)'
C:\Users\Pierre\AppData\Local\Temp\ccSkLK4T.o:main.cpp:(.text+0x8f): undefined reference to `personne::affiche[abi:cxx11]()'
C:\Users\Pierre\AppData\Local\Temp\ccSkLK4T.o:main.cpp:(.text+0x162): undefined reference to `developpeur::developpeur(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)'
C:\Users\Pierre\AppData\Local\Temp\ccSkLK4T.o:main.cpp:(.text+0x1dd): undefined reference to `developpeur::set_langage(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)'
C:\Users\Pierre\AppData\Local\Temp\ccSkLK4T.o:main.cpp:(.text+0x210): undefined reference to `developpeur::affiche[abi:cxx11]()'

[filesCPP.zip](https://github.com/formulahendry/vscode-code-runner/files/2333139/filesCPP.zip)

**Comment by formulahendry** [comment]
For compiling multiple cpp files, you may refer to #184

**Comment by Brucius** [comment]
@Pierre8r You will need to take away $filename as *.cpp is already a flag in g++ compile command. Hope this helps
