### ISSUE TITLE
/bin/sh: node: command not found

### ISSUE THREAD

**Issue by kisnows** [formulahendry/vscode-code-runner#355]
Every time I try to execute a node file, I will get an error.
![image](https://user-images.githubusercontent.com/9394000/44906517-b7a30e80-ad47-11e8-8cec-caccc64507ba.png)
But in my terminal:
![image](https://user-images.githubusercontent.com/9394000/44906639-1072a700-ad48-11e8-8328-7e7d3273d1ab.png)

I install node use nvm.

**Comment by formulahendry** [comment]
Please use below setting (`File`->`Preference`->`Settings`) to run code in Integrated Terminal:
```json
{
    "code-runner.runInTerminal": true
}
```

**Comment by johnny-c-jiang** [comment]
why this one isn't the default setting?

**Comment by marcosDeveloperr** [comment]
obrigado, sua dica funcionou no visual studio code..gratidão

**Comment by shuhdad** [comment]
> Please use below setting (`File`->`Preference`->`Settings`) to run code in Integrated Terminal:
> 
> ```json
> {
>     "code-runner.runInTerminal": true
> }
> ```

thanks

**Comment by masterdf159** [comment]
On Visual Studio MAC-M1 or Windows download Pack Node.js https://nodejs.org/en/ --- install pack y run code

**Comment by Labrinth011** [comment]
Thank you very much! Have been struggling for hours now.
