### ISSUE TITLE
Python下如何配置Code Runner 可以直接启动调试？

### ISSUE THREAD

**Issue by jiazone** [formulahendry/vscode-code-runner#356]
VS Code 可以在根目录下新建.env文件配置 PYTHONPATH= "xxx"，使在项目下任何.py文件通过”启动调试“运行而不会报 No module named xxx 的错误。直接Run Code 则会报此错误。
我想通过配置 .env文件，在文件下使用Run Code 可以直接启动调试。请问该如何设置？

**Comment by jiazone** [comment]
已解决。code-runner执行 **.py** 文件的原理即在**cmd**中执行命令，所以只需要设置利用**PYTHONPATH**启动.py文件的命令即可。
```
"code-runner.executorMap": {
        "python":"cd $workspaceRoot && set PYTHONPATH=%PYTHONPATH%;$workspaceRoot && $pythonPath $fullFileName"
    }
```

**Comment by HeWanli** [comment]
请教一下，如何配置code Runner 运行虚拟环境
