### ISSUE TITLE
Python Chinese garbled

### ISSUE THREAD

**Issue by AibiTi** [formulahendry/vscode-code-runner#359]
Python Chinese garbled.

Python 3.6，Code Runner 0.9.4.

![360 16421029204125](https://user-images.githubusercontent.com/40224479/45074214-294ad600-b115-11e8-9878-82a801972026.png)

![image](https://user-images.githubusercontent.com/40224479/45074219-31a31100-b115-11e8-9241-25aa7a9fd15a.png)

**Comment by iuhiyuh** [comment]
{"code-runner.runInTerminal": true} 
加到用户设置里

**Comment by formulahendry** [comment]
Thanks @iuhiyuh
