### ISSUE TITLE
&&./a.out 中的"."不是内部或外部的命令，也不是可运行的程序

### ISSUE THREAD

**Issue by PatrickPhang** [formulahendry/vscode-code-runner#36]
![problem](C:\Users\asus-pc\Desktop\snipaste20161204_235349.png)
我在命令行窗口gcc没问题，在VS Code里就提示： &&./a.out 中的"."不是内部或外部的命令，也不是可运行的程序，麻烦您啦~

**Comment by formulahendry** [comment]
截图看不到。。能再发下吗

**Comment by formulahendry** [comment]
This issue should be fixed now.
