### ISSUE TITLE
Python code is ignored unless file is saved every time

### ISSUE THREAD

**Issue by valorien** [formulahendry/vscode-code-runner#363]
I'm editing an existing Python file and have added two new lines to it:
```
print("Core 0")  # Existing code

print("Core 1")  # New line
print("Core 2")  # New line
```

When I run the code _(Ctrl+Alt+N)_, the output window only shows "Core 0" has been printed.
However, if I run the code through VS code's built-in "Run Python file in terminal command", all lines are correctly printed.

After **manually saving** the file and running the code with Code runner again, all lines are printed just fine.

It seems Code Runner needs the code to be saved before it detects any changes to it, while VS code does not.

**Comment by Biohacking-zhangyp** [comment]
Add "code-runner.saveFileBeforeRun": true, into your user setting.

**Comment by valorien** [comment]
That worked, thanks. Why isn't this the default?
If the user wants to run their code, it's obvious they want to run what they're seeing in front of their eyes.
The current behavior is confusing and inconsistent with the way editors/IDEs work.
