### ISSUE TITLE
encoding issues

### ISSUE THREAD

**Issue by aguirreeng** [formulahendry/vscode-code-runner#365]
I'm running a simple script on VSCode and, when running the script with code-runner I'm getting encode errors on output. Using the standard VSCode Python run I have no problems.

The script is:

```python
import feedparser
fman = 'https://fman.io/blog/rss.xml'
f = feedparser.parse(fman)
print(f['entries'])
```

When running with code-runner I have the output error:

```
[Running] python -u "d:\aguirre\repository\rss-fed\rss-fed.py"
Traceback (most recent call last):
  File "d:\aguirre\repository\rss-fed\rss-fed.py", line 9, in <module>
    print(f['entries'])
  File "W:\Miniconda\envs\notebook\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 17480-17482: character maps to <undefined>

[Done] exited with code=1 in 1.03 seconds
```

As I've said before, running with VSCode directly (or on a command prompt) gives me the correct output.

Cheers.

**Comment by formulahendry** [comment]
As workaround, you could use below setting (`File`->`Preference`->`Settings`) to run code in Integrated Terminal:
```json
{
    "code-runner.runInTerminal": true
}
```

**Comment by website-123** [comment]
ㄹㅇㅋㅋ

**Comment by LeGrandMAG** [comment]
> As workaround, you could use below setting (`File`->`Preference`->`Settings`) to run code in Integrated Terminal:
> 
> ```json
> {
>     "code-runner.runInTerminal": true
> }
> ```

This actually helped me a lot.

**Comment by Sbrjt** [comment]
But this is a workaround, not a fix. Why is the issue closed? @formulahendry
