### ISSUE TITLE
Can't use python3

### ISSUE THREAD

**Issue by creeptonik** [formulahendry/vscode-code-runner#366]
I've followed all recommendations and questions asked around and have downloaded the latest version of vs but when I set python to use python3 instead of 2 it just doesn't work. My config:

```
{
    "python.jediEnabled": false,
    "python.pythonPath": "/usr/local/bin/python3",
    "workbench.colorTheme": "Solarized Light",
    "code-runner.runInTerminal": true,
    "code-runner.defaultLanguage": "python",
    "code-runner.clearPreviousOutput": true
}
```
Doing
```
"code-runner.executorMap":
{
"python": "python3"
}
```
isn't working. Any help please?

**Comment by FooKii** [comment]
hey there, i think u can try simply add "code-runner.executorMap.python": "python3 -u" to the user settings and it should work.
cheers!

**Comment by creeptonik** [comment]
> hey there, i think u can try simply add "code-runner.executorMap.python": "python3 -u" to the user settings and it should work.
> cheers!

It says "Unknown configuration setting"
<img width="264" alt="settings json pythontools 2018-09-21 09-41-05" src="https://user-images.githubusercontent.com/10048338/45870353-98b1fe00-bd82-11e8-9a14-4bb2e7bb8e1b.png">

@formulahendry Shebang? Not sure...

**Comment by formulahendry** [comment]
@creeptonik , could you have a screenshot of your output and your python file?

**Comment by creeptonik** [comment]
Here you go, it's the same error as if I was running python 2 ('No module named requests'):
![ft_get_write_video py pythontools 2018-09-21 11-44-14](https://user-images.githubusercontent.com/10048338/45876821-c5224600-bd93-11e8-9869-3a6a4b6220af.png)

**Comment by formulahendry** [comment]
Please set `code-runner.respectShebang` as `false`

**Comment by Davincible** [comment]
The above suggestion also fixed my issue, would be nice if python3 was enabled by default

**Comment by WanerZhang** [comment]
> Please set `code-runner.respectShebang` as `false`

Hello, this still doesn't work for me, do you have any ideas? Thanks!

**Comment by callmekofi** [comment]
Python: Select Interpreter menu. Look for " Python X.X.X " on the bottom left of your screen. Look for "Python X.X.X". This is the currently detected/configured version of Python in your project, and clicking it brings you to the interpreter menu to change the Python version you're using

**Comment by NYKDDD54** [comment]
> > Please set `code-runner.respectShebang` as `false`
> 
> Hello, this still doesn't work for me, do you have any ideas? Thanks! <img alt="截屏2022-01-06 下午8 00 34" width="566" src="https://user-images.githubusercontent.com/97230443/148380121-12c3675e-7a8c-417e-80e3-5cfcb9d20cb1.png">

You are missing a comma at the end of "code-runner.runInTerminal". Also, try "code-runner.executorMap" instead of "code-runner.executorMap.python" and press enter and you should see all the default path of different languages. Now just change the path in "python" you desire.
