### ISSUE TITLE
How to get output files to go in the appropriate folder 

### ISSUE THREAD

**Issue by kevinhpinkerton** [formulahendry/vscode-code-runner#367]
I'm using code runner with java, but it puts all of my .class files in my .src folder whenever I compile and run. Is there any way to get them to go into the .bin folder where I'd like them stored. I have .classpath and .project files. I believe those stipulate that output files go in .bin. 

I'm really unfamiliar with Java and projects so I'd appreciate some help.

**Comment by formulahendry** [comment]
You could update `code-runner.executorMap` for java, refer to https://github.com/formulahendry/vscode-code-runner#configuration
