### ISSUE TITLE
Support Go tests

### ISSUE THREAD

**Issue by bang88** [formulahendry/vscode-code-runner#37]

**Comment by formulahendry** [comment]
Hi @bang88 , could you please provide more details about Go tests?

**Comment by bang88** [comment]
A go file with tests looks like : 

```go
λ ls -al
total 9
drwxr-xr-x 1 bang 197609   0 Dec  5 18:13 ./
drwxr-xr-x 1 bang 197609   0 Dec  5 18:17 ../
-rw-r--r-- 1 bang 197609 219 Dec  5 18:09 main.go
-rw-r--r-- 1 bang 197609 965 Dec  5 18:17 main_test.go
```
When I change the map as below and run code it should include the source files. 

```go
  "code-runner.executorMap": {
        "go": "go test"
    }
```
But now the arguments is only the current file.

```sh
[Running] go test "e:\GoLang\src\bank\main_test.go"
# command-line-arguments
bank\main_test.go:46: undefined: Deposit
bank\main_test.go:47: undefined: Balance
bank\main_test.go:66: undefined: Balance
FAIL	command-line-arguments [build failed]

[Done] exited with code=2 in 0.279 seconds
```

**Comment by formulahendry** [comment]
So what's your expected command for go test? Or rather, how do you run go test in shell?

**Comment by bang88** [comment]
Test file:

```sh
go test file1_test.go file1.go
```

**Comment by bang88** [comment]
When we test a single file we need the source file too.

**Comment by formulahendry** [comment]
You may try below settings:
```json
"code-runner.executorMap": {
    "go": "go test $fullFileName file1.go"
}
```

**Comment by bang88** [comment]
```
file1.go // this is dynamic just like the $fullFileName
``

**Comment by bang88** [comment]
By the way , can i use JS function in the map rule ?

eg: `$fullFileName.replace()`

**Comment by formulahendry** [comment]
If the source file is `abc.go`, the test file is `abc_test.go`?

**Comment by bang88** [comment]
Yes,this is Go test.

**Comment by formulahendry** [comment]
You may try the new feature (run custom command) of this extension with the latest version:
```json
"code-runner.customCommand": "cd $dir && go test $fileNameWithoutExt_test.go $fileName"
```
Then, use keyboard shortcut `Ctrl+Alt+K` (The active editor should be on the source file) to run test, use `Ctrl+Alt+N` to run code.

**Comment by bang88** [comment]
OK. Thanks
