### ISSUE TITLE
Running Code from Keyboard Shortcut (Ctrl+Alt+N) doesn't work as expected

### ISSUE THREAD

**Issue by phfatmonkey** [formulahendry/vscode-code-runner#375]
I'm working on a Text Adventure Creator in Python. 

When I right-click and choose **Run Python File in Terminal** it works as expected.
![image](https://user-images.githubusercontent.com/3812933/46491348-57c4db00-c7bf-11e8-9264-a9f7fdd2e53e.png)
![image](https://user-images.githubusercontent.com/3812933/46491458-a3778480-c7bf-11e8-83b2-be8e43990637.png)

But when I press Ctrl+Alt+N I get this:
![image](https://user-images.githubusercontent.com/3812933/46492129-8e035a00-c7c1-11e8-8bf4-2dcae3c14e1f.png)

I think it's still trying to use Python 2.7. I have Python 2.7 on my machine and the Python27 folder was in my path. When that was happening the file would run in terminal with Ctrl+Alt+N, but it would halt when it got to the input function, since Python2 tried to evaluate the result of the input function instead of just get the string like Python3. 

But even though I've updated the Path Environment variable and have Python 3.4 selected in VS Code:
![image](https://user-images.githubusercontent.com/3812933/46491844-bb9bd380-c7c0-11e8-8013-c79fe8b04df0.png)

I'm still getting this weird discrepancy between the shortcut and the right-click menu.

Any ideas?

**Comment by babu-thomas** [comment]
What's the run command for python in `code-runner.executorMap` in your `settings.json`?

**Comment by phfatmonkey** [comment]
Ok, so after I restarted my machine the keyboard shortcut works fine now and I can't reproduce. I guess the fix is "turn it off and on again."

**Comment by formulahendry** [comment]
Good to know it is working

**Comment by paolotormon** [comment]
It's not working for me after restarting
