### ISSUE TITLE
compiling and running commands are not correct

### ISSUE THREAD

**Issue by GreekEvo** [formulahendry/vscode-code-runner#390]
- VS Code Version: 1.28.2
- OS Version: Ubuntu 18.10 64-bit
- Code Runner Version: 0.9.5

**Describe the bug**
I'm trying my best to explain. So I made a simple C program and want to compile and run it, with the plugin enabled I press the run code button so as to be compiled and run automatically and on the output I the correct commands being executed except the last part where a quotation mark is wrongfully placed before the name of the application (see screenshot below) so the program never actually runs. 

**To Reproduce**

1. Create a C program (haven't used other languages)
2. Click the Run code button or (ctrl+alt+N)
3. Observe the output command

**Actual behavior**
it stays stuck at the command as the program never actually runs

**Expected behavior**
source file to be compiled and run

**Screenshots**
![07wmdbn](https://user-images.githubusercontent.com/28892220/48094140-0a9eb380-e21a-11e8-9d90-fffba1fb1c39.png)

**Comment by saddhu1005** [comment]
I had encountered the same issue but it got fixed up by changing the setting for code runner extension.
Simply **go to "File->Preferences->Extensions->Run code configurations"** and select the option of
 **"Run In Terminal"**
So if the code runs in integrated Terminal then it will not cause any issue.
  a **screenshot** of the same is attached.
![test run code](https://user-images.githubusercontent.com/31150629/54312871-01758700-45fe-11e9-9bd3-5df2b2ab5297.png)

**Comment by saddhu1005** [comment]
>     * VS Code Version: 1.28.2
> 
>     * OS Version: Ubuntu 18.10 64-bit
> 
>     * Code Runner Version: 0.9.5
> 
> 
> **Describe the bug**
> I'm trying my best to explain. So I made a simple C program and want to compile and run it, with the plugin enabled I press the run code button so as to be compiled and run automatically and on the output I the correct commands being executed except the last part where a quotation mark is wrongfully placed before the name of the application (see screenshot below) so the program never actually runs.
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
>     1. Create a C program (haven't used other languages)
> 
>     2. Click the Run code button or (ctrl+alt+N)
> 
>     3. Observe the output command
> 
> 
> **Actual behavior**
> it stays stuck at the command as the program never actually runs
> 
> **Expected behavior**
> source file to be compiled and run
> 
> **Screenshots**
> ![07wmdbn](https://user-images.githubusercontent.com/28892220/48094140-0a9eb380-e21a-11e8-9d90-fffba1fb1c39.png)



>     * VS Code Version: 1.28.2
> 
>     * OS Version: Ubuntu 18.10 64-bit
> 
>     * Code Runner Version: 0.9.5
> 
> 
> **Describe the bug**
> I'm trying my best to explain. So I made a simple C program and want to compile and run it, with the plugin enabled I press the run code button so as to be compiled and run automatically and on the output I the correct commands being executed except the last part where a quotation mark is wrongfully placed before the name of the application (see screenshot below) so the program never actually runs.
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
>     1. Create a C program (haven't used other languages)
> 
>     2. Click the Run code button or (ctrl+alt+N)
> 
>     3. Observe the output command
> 
> 
> **Actual behavior**
> it stays stuck at the command as the program never actually runs
> 
> **Expected behavior**
> source file to be compiled and run
> 
> **Screenshots**
> ![07wmdbn](https://user-images.githubusercontent.com/28892220/48094140-0a9eb380-e21a-11e8-9d90-fffba1fb1c39.png)

Try the above fix
hope it works :p.

**Comment by GreekEvo** [comment]
> 
> 
> I had encountered the same issue but it got fixed up by changing the setting for code runner extension.
> Simply **go to "File->Preferences->Extensions->Run code configurations"** and select the option of
> **"Run In Terminal"**
> So if the code runs in integrated Terminal then it will not cause any issue.
> a **screenshot** of the same is attached.
> ![test run code](https://user-images.githubusercontent.com/31150629/54312871-01758700-45fe-11e9-9bd3-5df2b2ab5297.png)

yup that did the trick. thanks for this little fix
