### ISSUE TITLE
output panels reuse

### ISSUE THREAD

**Issue by rickmed** [formulahendry/vscode-code-runner#4]
EDIT: this issue is irrelevant and don't belong in this repo. Apologies

The runner creates an output panel every time its goes, should it reuse only one?

**Comment by formulahendry** [comment]
Hi @rickmed , what VS code version and OS are you using? I could not repro this. I only see one output panel called 'Code' after I triggers several runs.
![picture](https://cloud.githubusercontent.com/assets/1050213/17454175/ac348a28-5bbf-11e6-98e4-f44b8fcad285.png)

**Comment by rickmed** [comment]
vscode 1.4

win10 x64

**Comment by formulahendry** [comment]
Could you please share the screenshot. And a GIF of the repro steps would be even better.

**Comment by rickmed** [comment]
@formulahendry 
I'm sooo sorry. I confused extensions! (posted the issues on the wrong ones)

I'll open a new issue with the correct one.

**Comment by formulahendry** [comment]
Never mind. :smile:
