### ISSUE TITLE
Add diy shortcut

### ISSUE THREAD

**Issue by tianzhipengfei** [formulahendry/vscode-code-runner#404]
**Is your feature request related to a problem? Please describe.**
I am not used to use Ctrl + Alt + N/M to run or stop codes. 

**Describe the solution you'd like**
Add a configuration part to set shortcut.

**Comment by dominick-designs** [comment]
> **Is your feature request related to a problem? Please describe.**
> I am not used to use Ctrl + Alt + N/M to run or stop codes.
> 
> **Describe the solution you'd like**
> Add a configuration part to set shortcut.

see this issue: https://github.com/formulahendry/vscode-code-runner/issues/286

which refers to how to set keyboard shortcuts in VS Code: https://code.visualstudio.com/docs/getstarted/keybindings#_keyboard-shortcuts-editor

**Comment by formulahendry** [comment]
Thanks @tianzhipengfei !
