### ISSUE TITLE
Can not run the new code immediately after edited.

### ISSUE THREAD

**Issue by zhengger** [formulahendry/vscode-code-runner#405]
- VS Code Version:1.30.1 (1.30.1)
- OS Version:10.14.1
- Code Runner Version:0.9.5

**Describe the bug**
There is much delay for running code which is edited just now. It just runs the old code unless you save the code manually.

**To Reproduce**

1. 
2. 

**Actual behavior**
Description of what happened actually.

**Expected behavior**
Description of what you expected to happen.

**Screenshots**

**Comment by zhengger** [comment]
I just change the time delay to 1 ms for autosave and then it works perfectly. Thanks!!!

**Comment by rdhar** [comment]
Hey @zhengger, out of interest, did you manage to get Code Runner to execute automatically upon file save? If so, how did you do it (as it might help resolve #455)?
