### ISSUE TITLE
on c/cpp file, while right click the "run code", errors would occur on windows

### ISSUE THREAD

**Issue by lsmale** [formulahendry/vscode-code-runner#41]
The default "code-runner.executorMap" of "c": "gcc $fullFileName && ./a.out" and "cpp": "g++ $fullFileName && ./a.out", but in pc the default output file name is "a.exe", and exec method should be "a.exe" or "a".

**Comment by formulahendry** [comment]
Thanks @lsmale for reporting it, I will fix it for Windows.

**Comment by formulahendry** [comment]
Hi @lsmale , this issue has been fixed. Please install the latest version and have a try.

**Comment by lsmale** [comment]
Hi @formulahendry , I tried it and I find you used command "cd $dir", and I test it with the file in different drive, it turns out the command cannot cross drive and while in different drive it may result in "g++: error: name.cpp: No such file or directory“.

**Comment by formulahendry** [comment]
HI @lsmale , the current working directory would be the root folder that you open in VS Code. Thus, the drive of current working directory should be same as that of the cpp file. So are you opening a file from another drive in VS Code? To Fix this, there are two options, refer to https://github.com/formulahendry/vscode-code-runner#about-cwd-setting-current-working-directory:
1. Set `code-runner.cwd` to the drive of cpp file
2. Ser `code-runner.fileDirectoryAsCwd` as `true`

**Comment by formulahendry** [comment]
Or, you could replace `cd` with `pushd` or `cd /d`. Refer to http://stackoverflow.com/questions/17753986/how-to-change-directory-in-windows

**Comment by lsmale** [comment]
Hi @formulahendry , I get it! Thanks.
