### ISSUE TITLE
SyntaxError: invalid syntax during output in Python code

### ISSUE THREAD

**Issue by vzaletny** [formulahendry/vscode-code-runner#420]
- VS Code Version: 1.30.2
- OS Version: LinuxMint 18.3 
- Code Runner Version:  0.9.6

[Running] python -u "/home/dima/lessons.py"
  File "/home/dima/lessons.py", line 11
    print(hh, mm, sep=' ')
                     ^
SyntaxError: invalid syntax

[Done] exited with code=1 in 0.065 seconds

Run this code in a console with no issue. 
Remove "sep='  '" - run the code with no issue.

**Comment by vzaletny** [comment]
Need change running python version in VS Code JSON config file.

**Comment by drewcicchetti** [comment]
@vzaletny i am completely new at all this, how do i change running python version in VS Code because i keep getting the same error as well when running code with sep=

Thank you
