### ISSUE TITLE
main.rs file started with `#![feature(generators, generator_trait)]` treated as shell script not Rust code

### ISSUE THREAD

**Issue by aramazani** [formulahendry/vscode-code-runner#425]
- VS Code Version: 1.30.2 x64
- OS Version: Linux Ubuntu x86_64
- Code Runner Version: 0.9.7 (2019-01-29)

**Describe the bug**
Description of what the bug is.
`main.rs` file started with `#![feature(generators, generator_trait)]` treated as shell script not Rust code

**To Reproduce**

1. use this `main.rs` file and run it using code runner:
```
#![feature(generators, generator_trait)]

use std::ops::Generator;
use std::pin::Pin;
fn main() {
    let mut generator = || {
        println!("2");
        yield;
        println!("4");
    };

    println!("1");
    Pin::new(&mut generator).resume();
    println!("3");
    Pin::new(&mut generator).resume();
    println!("5");
}

```
 
**Actual behavior**
Description of what happened actually.
```
$ [feature(generators, generator_trait)] "/home/user/code/rs/yield1/src/tempCodeRunnerFile.rs"
bash: syntax error near unexpected token `generators,'
```
**Expected behavior**
Description of what you expected to happen.
```
cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.01s
     Running `target/debug/yield1`
1
2
3
4
5
```

**Comment by caub** [comment]
yes, same with 
```rust
#![allow(dead_code)]

let x = 1
```
that `#!..` is interpreted as a hashbang by code-runner

**Comment by caub** [comment]
@formulahendry I PR'ed a simple fix
