### ISSUE TITLE
能不能增加对elixir的支持?

### ISSUE THREAD

**Issue by ilessy** [formulahendry/vscode-code-runner#43]
如题

**Comment by formulahendry** [comment]
Seems there are two types of elixir file: `.ex` and `.exs`. We could easily support `.exs` as script mode. Or you want to support both?
If you'd like to implement it, PR is welcome. 😃

**Comment by formulahendry** [comment]
Hi @ilessy , I have added support for `.exs`.  Please install the latest version and have a try.

**Comment by ilessy** [comment]
Thanks a lot. I just added it myself as told in the document like this:
```
"code-runner.executorMapByFileExtension": {
    ".ex": "elixir",
    ".exs": "elixir"
  }
```
and it works.
