### ISSUE TITLE
Wrong node version referenced

### ISSUE THREAD

**Issue by Mr-Binary** [formulahendry/vscode-code-runner#44]
Hi, great extensions, thanks.

I use [nvm](https://github.com/creationix/nvm) to manage a multi-version node environment.

The problem is like below:
1. Start VSC, (node version = 4.7)
2. in the integrated terminal, which has the following settings in the user settings
```json
//to enable running bash as a login shell (which runs `.bash_profile`)
"terminal.integrated.shellArgs.osx": [
        "-l"
    ],
```
3. Run the command, "nvm use 6", now the node version changes to 6
4. Executing `console.log(process.version)`, the output is `v4.7.0`
5. In the integrated terminal, executing the file by `node test.js`, the output is `v6.9.2`
6. `nvm` will add the following lines to the `.bash_profile`:
```bash
export NVM_DIR="/Users/albertgao/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm
```
7. but seems I don't know how to add it to the `"code-runner.executorMap": {}`

It would be super nice if the code-runner could use the interpreter which comes from the integrated terminal or at least we can configure it :) Thanks.

**Comment by formulahendry** [comment]
There would be two options:
* Set `"code-runner.runInTerminal": true` in the user settings, so that the js file will run in integrated terminal
* Customize the script in executorMap what you like. I am not familiar with nvm, but per you description, you may add setting like below to use node version 6:
```json
"code-runner.executorMap": {
    "javascript": "nvm use 6 && node"
}
```

**Comment by Mr-Binary** [comment]
the first one works like a charm while the second not, thanks!
