### ISSUE TITLE
Run C code with git bash

### ISSUE THREAD

**Issue by Yijx** [formulahendry/vscode-code-runner#451]
os：win10
shell：git bash
question：
If I not set "code-runner.runInTerminal": true,c code operating normally.
but when I set "code-runner.runInTerminal": true,git bash show me "No such file or directory".
this question only appear in git bash，cmd and powerShell all ok.
ok:
[![A0Co1e.md.png](https://s2.ax1x.com/2019/03/29/A0Co1e.md.png)](https://imgchr.com/i/A0Co1e)
no ok :(
[![A0Cq0I.md.png](https://s2.ax1x.com/2019/03/29/A0Cq0I.md.png)](https://imgchr.com/i/A0Cq0I)

what happened between runInTerminal and git bash？

**Comment by CorPython** [comment]
I also want to know how to solve this problem

**Comment by kyle-goodwin** [comment]
This has something to do with Bash and Window's backslashes. If you escape the backslash with another or replace them with a forward slashes it works.
![example](https://user-images.githubusercontent.com/45823898/77863315-6727b780-71ef-11ea-8627-8778fb1be710.png)
The command generated for Bash works fine in Command Prompt as well. Perhaps the output console is using Command Prompt and not Bash?
