### ISSUE TITLE
tempCodeRunnerFile.js not being deleted 

### ISSUE THREAD

**Issue by rag4214** [formulahendry/vscode-code-runner#453]
- VS Code Version: 1.32.3
- OS Version: Windows 10 Pro 1809
- Code Runner Version: 0.9.7

**Describe the bug**
If I highlight a code snippet -> right click -> Run Code the `tempCodeRunnerFile.js` is created but not deleted after it's executed

**To Reproduce**

1. Highlight Code Snippet
2. Right Click
3. Run Code
4. `tempCodeRunnerFile.js` is not deleted

**Actual behavior**
`tempCodeRunnerFile.js` is executed and not deleted after execution

**Expected behavior**
`tempCodeRunnerFile.js` is executed and deleted 

**Screenshots**
![Untitled](https://user-images.githubusercontent.com/35985028/55209277-23533a00-51b8-11e9-89c4-6cdf70186315.png)

![Untitled2](https://user-images.githubusercontent.com/35985028/55209286-25b59400-51b8-11e9-9e33-ddfca1bf53f7.png)

**Comment by formulahendry** [comment]
This issue has been fixed. Please try the latest v0.9.9 version

**Comment by alanlunspace** [comment]
This comes back for latest v0.9.15.

**Comment by formulahendry** [comment]
@alanlunspace  Are you running code in terminal? If yes, it will not be deleted.

**Comment by alanlunspace** [comment]
> @alanlunspace Are you running code in terminal? If yes, it will not be deleted.

Thanks for your prompt reply.
May I know how can I run and delete the temp file then?

**Comment by sambragg** [comment]
I'd also like to know how I can run code in terminal whilst also deleting the temp file.

**Comment by CwjXFH** [comment]
> @alanlunspace Are you running code in terminal? If yes, it will not be deleted.

If not run in the terminal, when output Chinese characters will garbled.

**Comment by CwjXFH** [comment]
> @formulahendry

If not run in the terminal, when output Chinese characters will garbled.

**Comment by ZakiyyullohDev** [comment]
bro you need to delete code runner extension!
