### ISSUE TITLE
No module named tkinter

### ISSUE THREAD

**Issue by EnzoPandulce** [formulahendry/vscode-code-runner#470]
- VS Code Version: 1.33.1
- OS Version: Linux Mint Cinnamon 19.1
- Code Runner Version: 0.98

**Describe the bug**
At the moment of running a code in python it says: Not called tkinter module, but this problem only gives me through Code runner, since at the time of running it goes through the vscode debugger, it works fine, and install the modules for python 2 and python 3, in the same way if the same Idle code of python, it does not give problems, I even run it in windows and it works fine, the error is in linux

Thank you

**Screenshots**
![Selección_001](https://user-images.githubusercontent.com/47549669/56713586-4dcce000-66ef-11e9-93ff-e49f0e132d70.png)

**Comment by jslvtr** [comment]
Hey Enzo, this is probably because Code Runner is running with Python 2 and Python 2 doesn't have a tkinter module. In Python 2 it's called Tkinter.

There's nothing to install though since it comes with Python.

You can change Code Runner settings to use Python 3, or to make it use the virtual environment of your project if you have one.

**Comment by EnzoPandulce** [comment]
If in fact it was the first thing that you check and in vscode is configured to be for python 3, could you modify said for meter for code runner?

Thanks for answering

regards

![imagen](https://user-images.githubusercontent.com/47549669/57162734-5f2b8180-6dac-11e9-9525-ca3901260dee.png)

**Comment by EnzoPandulce** [comment]
At the time of reviewing the notes of the official page, it is mentioned that the PATH must be reviewed, of the language that will be executed, so I put the path of the path to python3 and it worked, besides I also deactivate the messages of Pylint and now the code runs No problem

Settings.json : 

    "code-runner.executorMap": {"python": "/usr/bin/python3.7",},
    "python.linting.enabled": false
