### ISSUE TITLE
Are you missing a using directive or an assembly reference?

### ISSUE THREAD

**Issue by moleszek** [formulahendry/vscode-code-runner#490]
Hi,

I've download code runner and I have a problem (probably configuration problem).
When I'm trying to compile part of the code (C#) I receive an error CS7021 => missing `XmlDocument`  but when I start the code normally `dotnet run` this error does not occur.

Code that I'm trying to compile:
   public void CreateXml()
    {
            XmlDocument doc = new XmlDocument();
            XmlNode docNode = doc.CreateXmlDeclaration("1.0", "UTF-8", null);
            doc.AppendChild(docNode);
            doc.Save(Console.Out);
            Console.ReadKey();
    }

I'm using: 
.net core 3.0
C#
Visual Studio Code

**Comment by imba-tjd** [comment]
![图片](https://user-images.githubusercontent.com/24759802/59021298-233d7d80-887e-11e9-9124-647d2c716c4a.png)
