### ISSUE TITLE
Errors in running c++.

### ISSUE THREAD

**Issue by xia1065** [formulahendry/vscode-code-runner#492]
(I sent an official question to vs code, which they said was part of the market plug-in problem):

Causes of the error:
Previously, there was no problem in writing c++ programs for a period of time.
When the C++ program was written this time, it forgot to write a break statement, which resulted in a dead loop, and then got stuck.
Then I forcibly shut down, restart vs code, code runner has this error.

This is the following error report:

PS C: Users XXX > CD "f: cpp" & g+ + 1007.cpp-o 1007 & "f: cpp"1007"

Location line: 1 character: 14

+ CD "f: cpp" & G + + 1007.cpp-o 1007 & f: cpp 1007

+~~

The tag "&&" is not a valid statement separator in this version.

Location line: 1 character: 38

+ CD "f: cpp" & G + + 1007.cpp-o 1007 & f: cpp 1007

+~~

The tag "&&" is not a valid statement separator in this version.

Location line: 1 character: 41

+ CD "f: cpp" & G + + 1007.cpp-o 1007 & f: cpp 1007

+~~~~~~~~~

Only expressions are allowed as the first element of a pipeline.

Location line: 1 character: 50

+ CD "f: cpp" & G + + 1007.cpp-o 1007 & f: cpp 1007

+~~~~

The expression or statement contains the unexpected tag "1007".

+ Category Info: ParserError: (:) [], Parent Contains Error Record Exception

+ Fully Qualified Error Id: Invalid EndOfLine

I have poor programming ability, how to solve this issue? Thanks.

**Comment by formulahendry** [comment]
Refer to https://github.com/formulahendry/vscode-code-runner/issues/491#issuecomment-499408887 for workaround

**Comment by formulahendry** [comment]
Duplicated with #491
