### ISSUE TITLE
 ${workspaceRoot} support

### ISSUE THREAD

**Issue by ryanptr** [formulahendry/vscode-code-runner#51]
In the setting file, how to enter the workspaceRoot directory?  such as  "cpp": "_cd **$workspaceRoot** && build && out.exe"_.

**Comment by formulahendry** [comment]
By default, the current working directory is already the workspaceRoot directory. Actually, you do not need `cd $workspaceRoot`.  So I have not supported $workspaceRoot yet. If you have other requirement for $workspaceRoot, I will consider supporting it. 😄

**Comment by ryanptr** [comment]
When I changed the subdirectory file, need to switch to the main file before build .If support $workspaceRoot will be very convenient. however, thank you for reply.  :p

**Comment by formulahendry** [comment]
Got it. Will add support for it.

**Comment by formulahendry** [comment]
Hi @ryanptr , I have added support for $workspaceRoot. Please install the latest version and have a try.

**Comment by ryanptr** [comment]
I just tested it, It is cool! thx.
