### ISSUE TITLE
Grabled in Windows

### ISSUE THREAD

**Issue by huyinjie** [formulahendry/vscode-code-runner#52]
![snipaste20170115_015037](https://cloud.githubusercontent.com/assets/8533957/21956888/230b95e0-dac5-11e6-839e-de05b69b95fa.png)

**Comment by formulahendry** [comment]
You could try below two options for this issue:
1. Use chcp to set code page of console
``` json
{
    "code-runner.executorMap": {
        "javascript": "chcp 65001>nul && node"
    }
}
```
2. Run it in built-in terminal 
``` json
{
    "code-runner.runInTerminal": true
}
```

BTW, I guess your node.exe interpreter is not in your PATH environment variables, and you need use `console.log(age)` instead of `alert()`

**Comment by huyinjie** [comment]
How to run this code in Windows
```
{
    "code-runner.executorMap": {
        "javascript": "chcp 65001>nul && node"
    }
}
```

**Comment by formulahendry** [comment]
This is a User Setting under menu of `File` > `Preferences`, refer to [this](https://code.visualstudio.com/docs/customization/userandworkspace#_creating-user-and-workspace-settings) to see how to add User Setting. Then, put the `code-runner.executorMap` setting into User Setting.

**Comment by huyinjie** [comment]
Just like this? 
Why I saved the right .json file but the left one(Settings.json) not changed?
Thanks


![snipaste20170115_150413](https://cloud.githubusercontent.com/assets/8533957/21960918/65134ad0-db35-11e6-8008-2eb8e49bd349.png)

**Comment by formulahendry** [comment]
The left json is read-only. After you change right json, it will overwrite the default one. You are OK to run JS now.

**Comment by huyinjie** [comment]
Error still...
![snipaste20170115_194907](https://cloud.githubusercontent.com/assets/8533957/21962233/c285d9fa-db5b-11e6-8278-12fc8bf45568.png)

**Comment by formulahendry** [comment]
Could you try option#2?

**Comment by huyinjie** [comment]
I have added these code to Settings.json
![snipaste20170115_201539](https://cloud.githubusercontent.com/assets/8533957/21962372/890fdabe-db5f-11e6-9859-0a51f8215931.png)

**Comment by huyinjie** [comment]
I added nodejs to the System Path and this problem fixed
Thank you very much
