### ISSUE TITLE
Output function results just like expressions

### ISSUE THREAD

**Issue by codefoster** [formulahendry/vscode-code-runner#521]
I am using Code Runner for TypeScript code and noticed that if I execute a statement like `1 + 2` it (as expected) runs successfully and outputs `3` in the Output window. However, if I execute `Math.random()` it runs successfully but doesn't output the result. I'm not sure why it wouldn't.

**Comment by formulahendry** [comment]
you need to use `console.log()`

**Comment by codefoster** [comment]
Right. That's what I've been doing, but it feels like a workaround. I'd love to be able to highlight any bit of code and run it and see the result - including function calls.

**Comment by formulahendry** [comment]
Thanks for your feedback!
Actually, it is related to Node.js, not the extension itself, So closing this as external.
