### ISSUE TITLE
Error when running Kotlin code

### ISSUE THREAD

**Issue by zisco67** [formulahendry/vscode-code-runner#529]
VSCode: 1.38.0
Code Runner: 0.9.14
Kotlin: kotlin-native-windows-1.3.50

When I'm trying to run the helloworld.kt
```
fun main(args: Array<String>) {
    println("Hello Kotlin")    
}
```
I get this error:
```
[Running] cd "c:\Users\dev\first_kotlin\" && kotlinc helloworld.kt -include-runtime -d helloworld.jar && java -jar helloworld.jar
error: invalid argument: -include-runtime

```
Any ideas? THX

**Comment by zisco67** [comment]
Really no ideas?

**Comment by endemics** [comment]
For reference if someone run into this as I did: to solve this problem, you need the kotlin compiler and NOT kotlin native ;)

**Comment by staenker** [comment]
thank you very much!
