### ISSUE TITLE
能否加入对TestNG的支持

### ISSUE THREAD

**Issue by LarkinZero** [formulahendry/vscode-code-runner#53]
通常在工作目录下执行
```
mvn test -Dtest=com.test.api.testcase#case1
```
即可运行一个测试case

希望run code可以加入此类文件的执行

**Comment by formulahendry** [comment]
How about using `custom command`? Setting anything you want to run as below:
```json
{
    "code-runner.customCommand": "echo Hello"
}
```
Then use shortcut `Ctrl+Alt+K`.

**Comment by LarkinZero** [comment]
It works,but the package name will change,class name will change,even case name will change.
How can I get the command parameters dynamically?

**Comment by formulahendry** [comment]
This extension is to auto-detect the language and run corresponding command per language. Or, let user defines the custom command by himself. In short term, I have no plan to do test case detection. So I suggest you write your own command and put it into `code-runner.customCommand`.
e.g.
```json
{
    "code-runner.customCommand": "RunTestNG.cmd"
}
```
