### ISSUE TITLE
[REQUEST] VisualBasic.NET Support

### ISSUE THREAD

**Issue by ElektroStudios** [formulahendry/vscode-code-runner#54]
Since this extension can support C# and managed C++ (VC++) languages, and we know that VB.NET is also "natively" supported in VS Code as part of the .NET platform like the two other mentioned languages, then I would like to ask why this extension ddn't added support VB.NET, and if it is going to add support for that language in the near future (I imagine it only would require little modifications).

Thanks for read.

**Comment by formulahendry** [comment]
Hi @ElektroStudios , I have added support for VB.NET. Please install the latest version and have a try. And you need to make sure the path of VB.NET compiler (vbc.exe) is in your PATH environment variable
