### ISSUE TITLE
Encode error while run Python3 to output Chinese

### ISSUE THREAD

**Issue by 1095553554** [formulahendry/vscode-code-runner#556]
This maybe  a bug, because I can output Chinese while run python file in terminal, but run it by Run Code extension will be an error "'charmap' codec can't encode characters".

Of course , I already set "# -*- coding:utf-8 -*-"  in head. Hope Run Code extension writer can look into this. I like this ext because it is convenient for us to run any code file. Now I disable it ,and not ganna use it untill encode issue fixed.

**Comment by 1095553554** [comment]
set "code-runner.runInTerminal": true in setting.json just right on that issue,hah

**Comment by pcgeek86** [comment]
+1 I can confirm that setting `runInTerminal` to `true` works. However, the bug still exists in the Output window.

**Comment by pcgeek86** [comment]
Related to #379 and #365
