### ISSUE TITLE
How about Clojure support?

### ISSUE THREAD

**Issue by dur41d** [formulahendry/vscode-code-runner#57]

**Comment by formulahendry** [comment]
Hi @dur41d , I have added support for Clojure in latest release, please have a try. I am not familiar with Clojure. After some investigation, I use `lein exec`. Let me know whether it works for you.

**Comment by dur41d** [comment]
I tested it and it works. However, it requires installing leiningen and the [lein-exec](https://github.com/kumarshantanu/lein-exec) plugin. Maybe it's better to try to run it directly from java using:

java -cp /path/to/the/clojure.jar clojure.main /path/to/your/code.clj

Checkout this documentation: http://dev.clojure.org/display/doc/FAQ

**Comment by formulahendry** [comment]
Sure. Thanks @dur41d for your suggestion. I will refine document about this.
