### ISSUE TITLE
[Bug] Code runner shorcut to stop running doesnt work

### ISSUE THREAD

**Issue by ikassim9** [formulahendry/vscode-code-runner#578]
- VS Code Version:
- OS Version: Windows 

- Code Runner Version: 0.9.15
**Describe the bug**
Description of what the bug is.
The shortcut ctrl + alt + m to stop the code doesn't work. I tried running infinite loop and see if I can the stop the code but it doesn't stop. I am forced to closed the entire thing and re open it again. 
**To Reproduce**

1. Run infinite loop
2. Try the shortcut to see it if you can stop the code

**Actual behavior**
The shortcut doesn't work and gives me an error.

**Expected behavior**
I expected the code to stop running with the shortcut.

**Screenshots**
![Screenshot (1)](https://user-images.githubusercontent.com/56459089/71933803-9a1a5c00-3168-11ea-8022-9c7034fd945a.png)

**Comment by Infinitay** [comment]
The exact same thing happens to me and has been happening for a while now.

The workaround is to open up the command pallet (F1 or CTRL+SHIFT+P) and type `Stop Code Run`. Though, it's tedious.

**Comment by Entomogant** [comment]
I have the same issue @ikassim9 mentions, although i am not able to stop the run with F1 and then typing "stop code run". 
I can use the command CTRL+ALT+M regurlarly if not using code runner, so I assume I dont have double bound shortcuts or something like that.

**Comment by ShrimpDuck** [comment]
> i am not able to stop the run with F1 and then typing "stop code run";

Hey man do you still have this issue? I'm stuck on it now as well and can't figure out the issue
