### ISSUE TITLE
code runner not work[Bug]

### ISSUE THREAD

**Issue by devendra32784** [formulahendry/vscode-code-runner#601]
- VS Code Version:
- OS Version:
- Code Runner Version:

**Describe the bug**
Description of what the bug is.

**To Reproduce**

1. 
2. 

**Actual behavior**
Description of what happened actually.

**Expected behavior**
Description of what you expected to happen.

**Screenshots**

**Comment by devendra32784** [comment]
![IMG_20200416_211613871~2](https://user-images.githubusercontent.com/63801977/79526650-62825080-8083-11ea-8adf-f5022486f62f.jpg)

**Comment by teslayder** [comment]
i have the same problem
