### ISSUE TITLE
Change how to fetch `pythonPath` as we're deprecating `python.pythonPath` setting soon

### ISSUE THREAD

**Issue by karrtikr** [formulahendry/vscode-code-runner#604]
Hi Python extension dev here👋

We will soon be deprecating `python.pythonPath` settings which you guys use here https://github.com/formulahendry/vscode-code-runner/blob/master/src/codeManager.ts#L363.

We're moving it out of settings to a VSCode storage. So you'll have to change the code to fetch interpreter path from a API we provide instead of fetching using `settings.json`, in a way that it's backwards compatible. The initial design of the API is listed here https://github.com/microsoft/vscode-python/issues/11294

**Comment by karrtikr** [comment]
The details of the API are listed here https://github.com/microsoft/vscode-python/issues/11294

**Comment by karrtikr** [comment]
We've to make sure all these 4 cases work,
1. Old version of Code Runner + Old version of the extension -> already works
2. New version of Code Runner + Old version of the extension
3. New version of Code Runner + New version of the extension
4. Old version of Code Runner + New version of the extension

I'll leave further details after discussion with the team.

### Proposed changes

**Code runner**

 In the new version of code runner,
- We would check if user is using the old or the new python extension using the new setting. (Check if flag `usingNewInterpreterStorage` in `package.json` of the extension in present or not)
- If he is using the old one, we would look for the settings in the old way
- If he is using the old one, we would look for the settings in the new way using the API

If new version of code runner is being used, the above proposed changes work fine for cases 2 & 3.

**Python extension**


_Solution:_
- Check if we are using the old version of intellicode or the new one.
- If using the old one,
    - Show a prompt asking user to upgrade Intellicode to new version to keep using it.

**Comment by formulahendry** [comment]
Thanks @karrtikr for your proposed changes. It looks great!
It seems the API is still in [PR review](https://github.com/microsoft/vscode-python/pull/11295).
Please let me know once it is ready, so that I could start to integrate the API in Code Runner.
It would also be helpful if you could kindly provide a simple code sample/snippet of calling the new API. 😄

**Comment by formulahendry** [comment]
For the flag, I plan to use below name in Code Runner:
```json
"featureFlags": {
    "usingNewPythonInterpreterPathApi": "true"
}
```

**Comment by karrtikr** [comment]
Hey @formulahendry 👋

Here's a [sample code](https://github.com/microsoft/vscode-azurefunctions/blob/868f3a237a85b167e111e6a4405326932d4e8885/src/debug/PythonDebugProvider.ts) using `debug` portion of our API. So the following should work for you:

```typescript
const extension = vscode.extensions.getExtension('ms-python.python')!;
const pythonPath = extension.exports.settings.getInterpreterPath(resource);
```

Also I realized that we should not put quotes around boolean `true` in feature flags, so you can use this instead
```json
"featureFlags": {
    "usingNewPythonInterpreterPathApi": true
}
```

I've updated the **Proposed changes** comment to reflect these details as well. We're having a discussion on the design of the API, I'll let you know when we finalize it, cheers!

**Comment by karrtikr** [comment]
Hey @formulahendry 👋

Here's a [sample code](https://github.com/microsoft/vscode-azurefunctions/blob/868f3a237a85b167e111e6a4405326932d4e8885/src/debug/PythonDebugProvider.ts) using `debug` portion of our API. Also we need to make sure the extension is activated first before calling the API. So you can use the code below:

```typescript
const extension = vscode.extensions.getExtension('ms-python.python')!;
if (!extension.isActive) {
    await extension.activate();
}
const pythonPath = extension.exports.settings.getInterpreterPath(resource);
```

Also I realized that we should not put quotes around boolean `true` in feature flags, so you can use this instead
```json
"featureFlags": {
    "usingNewPythonInterpreterPathApi": true
}
```

I've updated the **Proposed changes** comment to reflect these details as well. We're having a discussion on the design of the API, I'll let you know when we finalize it, cheers!

**Comment by karrtikr** [comment]
> Check if we are using the old version of Code runner or the new one. If using the old one, show a prompt asking user to upgrade Code runner to new version to keep using it.

For case 4, to reduce the number of users that get this prompt. Can we only show the prompt to those who have the setting in code runner to use `python.pythonPath`?

It would be helpful if you could provide a code snippet of how to accomplish that.

**Comment by karrtikr** [comment]
We finalized the API, it's detailed in the issue description https://github.com/microsoft/vscode-python/issues/11294. Please let me know if you've any questions.

**Comment by formulahendry** [comment]
Hi @karrtikr 
Here is the code snippet:
```javascript
const pythonExecutor = vscode.workspace.getConfiguration("code-runner", resource).get<string>("executorMap.python");
const isUsingPythonPath: boolean = pythonExecutor.includes("$pythonPath");
```

**Comment by formulahendry** [comment]
I see the [PR](https://github.com/microsoft/vscode-python/pull/11295) is merged.
I remember the Python extension has Insider version. Pleased kindly let me know when it is available in Insider, then I could start working on the new API.

**Comment by karrtikr** [comment]
Thanks for the snippet, will let you know.

**Comment by karrtikr** [comment]
It's available in the Insiders now.

**Comment by karrtikr** [comment]
@formulahendry Please let me know after you're able to make the release with the changes, after which I can merge https://github.com/microsoft/vscode-python/pull/11395.

**Comment by formulahendry** [comment]
Sure! I will work on this and let you know!

**Comment by formulahendry** [comment]
Hi @karrtikr , I have just [committed the changes](https://github.com/formulahendry/vscode-code-runner/commit/437456d2c5d9139951adc402d06612e1d76fd6e6).
Would you please have a try on the attached vsix file and see whether everything is expected from your side?
[code-runner-0.9.18-py.zip](https://github.com/formulahendry/vscode-code-runner/files/4564607/code-runner-0.9.18-py.zip)

If the changes are OK for you, I will publish a new release.

**Comment by karrtikr** [comment]
Yep, all good from my side. I have a comment regarding your change https://github.com/formulahendry/vscode-code-runner/commit/437456d2c5d9139951adc402d06612e1d76fd6e6#r38877025

**Comment by formulahendry** [comment]
Hi @karrtikr , I have just published a new release. You could continue your work now. 😄 
Closing this issue.
