### ISSUE TITLE
[REQUEST] Add common options in the context menu of the code output

### ISSUE THREAD

**Issue by ElektroStudios** [formulahendry/vscode-code-runner#62]
I will suggest some basic and needed options that I consider should be added in the context menu of the CODE output window:

![CODE Window](http://i.imgur.com/SCsJdQa.png)

   - Select All (Ctrl+A)             
    (same hotkey used by vs-code)

   - Clear Output (Ctrl+D)       
    (just a suggested hotkey, where "D" would mean DELETE or "R" would mean REMOVE)

Plus optionally this option that I consider it is less important than the others but could be very useful too when the output has a big amount of lines:

   - Find (Ctrl+F)                     
     (same hotkey used by vs-code)

Note: I know that we can still use the Ctrl+A and Ctrl+F hotkeys in the CODE window and also we can clear the output clicking on a button on top-right of the CODE window, however in my personal opinnion if the author adds these options in the context menu shown then it will improve a lot the user experience when using this extension because it is easier/more intuitive to show a menu and select an option than to remember a couple of built-in hotkeys...

Thanks for read!

**Comment by formulahendry** [comment]
This may be useful for users, but these options in context menu are generic (The Output window is not just used by `Code Runner`) and should be added in another extension or somewhere instead of adding them in `Code Runner` extension.
