### ISSUE TITLE
运行 typescript时 输出乱码

### ISSUE THREAD

**Issue by qiushisnail** [formulahendry/vscode-code-runner#632]
版本是最新版的vscode 64位
enum Gender{
  BOY,
  GIRL
}
[Done] exited with code=0 in 0.176 seconds

[Running] ts-node "f:\0000-2020-myproject\05-react\02ts+react\01mystudy\1.ts"
'ts-node' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���

[Done] exited with code=1 in 0.07 seconds；

如果在setting.json 中配置
`{
    "code-runner.runInTerminal": true
}`
则会出现下面问题
![image](https://user-images.githubusercontent.com/16640830/84842995-3f6f1f80-b079-11ea-88c7-8bd509ad9c43.png)

**Comment by qiushisnail** [comment]
1. 全局安装 typescript 和 ts-node
 npm i -g typescript ts-node
2. 使用命令获取 npm config get prefix 获取 ts-node安装地方 C:\Users\xxx\AppData\Roaming\npm
3. 将2获得的路径添加到环境变量path中
4. 重启电脑即可

**Comment by ALshas** [comment]
哈 你可是看的珠峰视频 我也正好遇到了这个问题

**Comment by iceCokelulu** [comment]
非常感谢，已经得到解决！

**Comment by ALshas** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by Hannahfall** [comment]
同珠峰视频来的。。。我也遇上了哈哈哈（嗯？怎么我还在看四年前的视频

**Comment by ALshas** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
