### ISSUE TITLE
Don't clear previous run output.

### ISSUE THREAD

**Issue by PankajBaliyan** [formulahendry/vscode-code-runner#634]
Issue Type: <b>Bug</b>

Extension name: code runner 
Error/Bug: when we run program it does not clear previous run output. The auto clear previous output feature don't work . After marked in all setting of code runner extension.

Extension version: 0.10.0
VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:20.174Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (3.79GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by jiacheng-0** [comment]
Same problem, Code Runner only seems to clear output from October 2018 version of VSCode for Python Files.

**Comment by Pankajbaliyan** [comment]
Anyone give me solution for this.

**Comment by dummy26** [comment]
search 'code runner Clear Previous Output' in settings and set it to false
