### ISSUE TITLE
Update the API usage to fetch interpreter path

### ISSUE THREAD

**Issue by karrtikr** [formulahendry/vscode-code-runner#635]
@formulahendry Apologies, It turns out we are updating the API again (https://github.com/microsoft/vscode-python/issues/12596). You'll have to change the usage accordingly,

- Introduce a flag in your package.json file so we can ask users to upgrade code runner (https://github.com/microsoft/vscode-python/pull/12765#issuecomment-654320227)
- Add yet another condition which introspect what APIs we expose and choose which one to use. IOW do a hasattr check.

The PR is in review at the moment https://github.com/microsoft/vscode-python/issues/12596

I'll let you know when it's finalized after which you need to publish the code runner extension.

**Comment by karrtikr** [comment]
Hey there, API is finalized. Thanks for cooperating and do let me know if there's something I need to clarify.

**Comment by formulahendry** [comment]
Is the new API in insider now? Then I will start the work to integrate with it.
For thenew flag, I would call it 'usingNewPythonInterpreterPathApiV2' (https://github.com/formulahendry/vscode-code-runner/blob/master/package.json#L7). Is that OK?

**Comment by karrtikr** [comment]
Yes it is. New flag name works for me, but please don't replace the old flag, just add a new one.

**Comment by formulahendry** [comment]
> Yes it is. New flag name works for me, but please don't replace the old flag, just add a new one.

Sure!

**Comment by formulahendry** [comment]
Hi @karrtikr , I have just [committed the changes](https://github.com/formulahendry/vscode-code-runner/commit/e63a4a7b1bb9ec4e66d404e80daec67dc36dd63e).
Would you please have a try on the attached vsix file and see whether everything is expected from your side?
[code-runner-0.11.0-py.zip](https://github.com/formulahendry/vscode-code-runner/files/4870122/code-runner-0.11.0-py.zip)


If the changes are OK for you, I will publish a new release.

**Comment by karrtikr** [comment]
Looks good to me👍 please proceed.

**Comment by formulahendry** [comment]
Hi @karrtikr , I have just published a new release.
