### ISSUE TITLE
[Bug] Unable to run .cpp file with name having white spaces

### ISSUE THREAD

**Issue by chauhannaman98** [formulahendry/vscode-code-runner#667]
- VS Code Version: 1.48.2
- OS Version: Ubuntu 20.4
- Code Runner Version: 0.11.0

**Describe the bug**
I tried running my C++ file name `day 1 - duplicate in an array.cpp` using the extension. It is not rendering the complete file name and extension directly copies the filename without the quotes. Thus, the terminal reads only the first word and executes the command right after the whitespace.

**To Reproduce**

1. Create a C++ file with any name having white spaces in between. For example: `example file name here.cpp`
2. Execute the program using the extension now and read the output in the terminal.

**Actual behavior**
The filename was`day 1 duplicate in an array.cpp`.
The output in the terminal was:
```bash
cd "/home/username/Desktop/SDE/" && g++ day 1 duplicate in an array.cpp -o day 1 duplicate in an array && "/home/username/Desktop/SDE/"day 1 duplicate in an array
g++: error: day: No such file or directory
g++: error: 1: No such file or directory
g++: error: duplicate: No such file or directory
g++: error: in: No such file or directory
g++: error: an: No such file or directory
g++: error: array.cpp: No such file or directory
g++: error: 1: No such file or directory
g++: error: duplicate: No such file or directory
g++: error: in: No such file or directory
g++: error: an: No such file or directory
g++: error: array: No such file or directory
g++: fatal error: no input files
compilation terminated.
```

**Expected behavior**
I manually edited the command executed in the terminal and again executed after adding quotes.
```bash
cd "/home/username/Desktop/SDE/" && g++ "day 1 duplicate in an array.cpp" -o "day 1 duplicate in an array" && "/home/username/Desktop/SDE/day 1 duplicate in an array"
Hello World
```
So, this one actually worked totally as expected.

**Screenshots**
1. Error:
![Screenshot 2020-08-27 19:18:57](https://user-images.githubusercontent.com/29328764/91451464-13eb8b00-e89b-11ea-91cb-6700f5c26d9d.png)

2. Expected behavior:
![Screenshot 2020-08-27 19:19:55](https://user-images.githubusercontent.com/29328764/91451569-2f569600-e89b-11ea-9f92-394a26630517.png)

**Comment by anjishnum** [comment]
- Go to ```File -> Preferences -> Settings```
- Type "code-runner" in the search bar
- Scroll down to the ```Code-runner: Executor Map``` section and click the ```Edit in settings.json```
- In the **settings.json** file, navigate to the line 
```"cpp": "cd $dir && g++ $fileName -o $fileNameWithoutExt && $dir$fileNameWithoutExt",``` 
and change it to: 
```"cpp": "cd $dir && g++ \"$fileName\" -o \"$fileNameWithoutExt\" && \"$dir$fileNameWithoutExt\"",```
- Save the **settings.json** file and you're good to go

**Comment by chauhannaman98** [comment]
> * "cpp": "cd $dir && g++ \"$fileName\" -o \"$fileNameWithoutExt\" && \"$dir$fileNameWithoutExt\"",

I have applied the settings and tries it again but it didn't work.

**Output:**
```bash
cd "/home/techmirtz/Desktop/placement/SDE practice/" && g++ "day1 duplicate in an array copy.cpp" -o "day1 duplicate in an array copy" && ""/home/techmirtz/Desktop/placement/SDE practice/"day1 duplicate in an array copy"
bash: /home/techmirtz/Desktop/placement/SDE: No such file or directory
```
Well, it seems like `$dir` already gives output inside quotes. When this is being used in the expression `\"$dir$fileNameWithoutExt\""`, the value of `$dir` in quotes in concatenated within quotes of `\"$dir$fileNameWithoutExt\""`, and thus, the issue occurs.
Do you have any other solution to this?

**Comment by anjishnum** [comment]
The problem is being caused due to there being a space in the folder named ```SDE practice```.
Change the previous code to the following:
```"cpp": "cd $dir && g++ \"$fileName\" -o \"$fileNameWithoutExt\" && $dir\"$fileNameWithoutExt\"",```

It's generally a good practice not to keep spaces in file and folder names. Just a tip!

**Comment by chauhannaman98** [comment]
Well, that works. Thanks!

> It's generally a good practice not to keep spaces in file and folder names. You could use underscores or camelcase for word separation. Just a tip!
I have been using camelcase and underscores for naming the files and folders. But, I was just curious about the working of the extension with filenames having whitespaces.
