### ISSUE TITLE
Problems running python programs

### ISSUE THREAD

**Issue by EduardoPessanha** [formulahendry/vscode-code-runner#677]
- VS Code Version: 1.49.2
- OS Version: Linux Mint x64 5.4.0-48
- Code Runner Version: v0.11.0

Code Runner does not recognize the new Python "f strings" configuration, which is defined in PEP498. 

    print(f'Eu vou comer {comida}')
                                 ^
SyntaxError: invalid syntax

![Captura de tela de 2020-09-26 12-03-37](https://user-images.githubusercontent.com/68357896/94343790-130c5d00-fff1-11ea-9a81-f9d830199257.png)

**Comment by anjishnum** [comment]
Go to ```File -> Preferences -> Settings```. In the search bar, type in ```code-runner```.

Now scroll down to the part where it says <pre>Code-runner: <b>Executor Map</b></pre> and click on ```Edit in settings.json```.

Within the ```"code-runner.executorMap"```, go to ```"python": "python -u"``` and change it to ```"python": "python3 -u"```.

You should be good to go now.

**Comment by EduardoPessanha** [comment]
Thanks for the tip!!!

I did exactly as indicated and now it's working perfectly. !!!!
