### ISSUE TITLE
[Bug] Multiple run buttons causing confusing user experience

### ISSUE THREAD

**Issue by sana-ajani** [formulahendry/vscode-code-runner#691]
Hi there! I'm on the VS Code team, and recently, we did some user studies where users ended up with multiple run buttons on a file, from multiple extensions contributing this action. In this case, the users had Code Runner and the Java extension installed.
To avoid this confusion for users, we encourage extensions to contribute editor title actions for specific files by using appropriate context keys and not for every file. 

![image](https://user-images.githubusercontent.com/9721254/98739028-a10c8f00-2376-11eb-9de3-41b12d89fab1.png)

More details outlined here: https://github.com/microsoft/vscode/issues/92269#issuecomment-650034660 It would be a better user experience if this was added to Code Runner. Thanks!

**Comment by formulahendry** [comment]
It is improved now: https://github.com/formulahendry/vscode-code-runner/pull/748
