### ISSUE TITLE
Color Running and [Done]

### ISSUE THREAD

**Issue by rickmed** [formulahendry/vscode-code-runner#7]
or add more characters to clearly separate the script runs...?

**Comment by formulahendry** [comment]
Will investigate the colorizer. Or what more characters do you expect?

**Comment by rickmed** [comment]
Not sure (maybe some dashes? :neutral_face: ), just a solution to clearly separate the the script runs.

Also, specify the file being ran (as opposed to only showing the extension). Maybe the complete path + filename?

**Comment by rickmed** [comment]
@formulahendry This is a similat atom package I like. So, maybe something like it?
when running:

![image](https://cloud.githubusercontent.com/assets/7104786/17458542/2f67b48e-5be2-11e6-8d2c-ad928f326a02.png)

when done:

![image](https://cloud.githubusercontent.com/assets/7104786/17458544/3bd98a30-5be2-11e6-895e-c578a01aeadb.png)

**Comment by formulahendry** [comment]
Cool! Will take a look.

**Comment by formulahendry** [comment]
Please try the latest version 0.2.0. Let me know if it is working well.

**Comment by rickmed** [comment]
It's cool! I would only show the file name instead of the complete path, but that is just a bit nitpicking. Your call :)
