### ISSUE TITLE
"Live" output

### ISSUE THREAD

**Issue by N2ITN** [formulahendry/vscode-code-runner#70]
I noticed this app only shows the output of code after it's 100% finished running.
When I'm running data / time intensive tasks, it's nice to have a live output as the task computes, similar to a terminal.
Is there a way to enable this currently without using the integrated terminal? If not, it would be an excellent addition.

**Comment by formulahendry** [comment]
Hi @N2ITN , are you running Python or other languages? I meet with this issue with Python, while JS and other languages is working normally with 'live' output.
As workaround, you could go to `File` > `Preferences` -> `User Settings` to add setting as below:
``` json
{
    "code-runner.runInTerminal": true
}
```
It will let you run code in built-in terminal with 'live' output.

**Comment by formulahendry** [comment]
Seems like you already try using integrated terminal. 😄  Not sure whether you are run Python or others.

**Comment by N2ITN** [comment]
Yes, you're right about me using Python. However, in some scenarios (ex:
using Keras) the output streams normal, but for others, no text is
displayed until the end (ex: calling a script to convert a folder of
files). Any thoughts on why this happens? Thanks!

**Comment by richardcooper** [comment]
This can be fixed for Python by adding:
```
 "code-runner.executorMap.python": "python -u"
```

to your settings.json file. Other executors might have similar settings.

By default `python` will buffer stdout unless it detects that it is attached to a terminal. The `-u` flag forces  stdin,  stdout  and stderr to be unbuffered regardless of what it is attached to.

I think using "python -u" should probably be the default in vscode-code-runner

**Comment by formulahendry** [comment]
Hi all, I just publish a new release. Now, "python -u" is the default setting. Thank you all!
