### ISSUE TITLE
Codes with any form of input do not run on code runner

### ISSUE THREAD

**Issue by thebigJ007** [formulahendry/vscode-code-runner#72]
Hi there. If I try to run my code using code runner and if there is any sort of input. For eg : cin in c++ then the output window just freezes and cannot accept any inputs. I then have to manually stop the code runner. I need some ideas to fix this.

**Comment by formulahendry** [comment]
Hi @thebigJ007 , you could go to `File` > `Preferences` -> `User Settings` to add setting as below:
``` json
{
    "code-runner.runInTerminal": true
}
```
Then you could run C++ in built-in terminal with input support

**Comment by shenhui28** [comment]
What is built-in terminal? I can only see output window when running code through code runner...

**Comment by formulahendry** [comment]
@shenhui28 It is the built-in terminal: https://code.visualstudio.com/docs/editor/integrated-terminal
If you set `"code-runner.runInTerminal"`, the code will run in built-in terminal. But if the file is untitled or running code snippet of selection, it is still in Output Window.

**Comment by peterchaula** [comment]
For those using the GUI. Press Ctrl + Shift + P, type "User Settings" and select "User settings". Search for "Run in terminal" and check the checkbox for the code runner setting. I strongly believe that this setting should be on by default. Ah, well. I guess the devs know what they are doing

**Comment by daudias** [comment]
> For those using the GUI. Press Ctrl + Shift + P, type "User Settings" and select "User settings". Search for "Run in terminal" and check the checkbox for the code runner setting. I strongly believe that this setting should be on by default. Ah, well. I guess the devs know what they are doing

Thanks a lot!

**Comment by theking17082000** [comment]
@peterchaula i cant find "run in terminal"

**Comment by peterchaula** [comment]
@theking17082000 I found in VSC v-1.38. You should scroll down one screen to find it

![image](https://user-images.githubusercontent.com/13304490/65069427-f45d9a00-d98a-11e9-968f-b01927085d96.png)

**Comment by theking17082000** [comment]
@peterchaula thanks for your effort but it is different for me. can u tell me a way to disable 
g
![Screenshot (5)](https://user-images.githubusercontent.com/43314821/65169653-97361700-da64-11e9-8db3-f6b723fa5c2e.png)
ui mode

**Comment by AzharInamdar** [comment]
Thanks a lot Guys ! It worked 💯

**Comment by JayaramKrovvidi** [comment]
how can I take an input of my cpp program from a file like "input.txt" rather than giving it in terminal. Does code runner support this?

**Comment by Gustavo2022003** [comment]
Thank you guys, i was having this problem for weeks

**Comment by YaduAhuja** [comment]
> I wrote a simple program to print hello World. It runs in the output window and the external terminal but fails to do so in the integrated one even though I have enabled  Run in  Terminal Option , but it stops here :
> ` cd "c:\Users\KIIT\Desktop\CPP\" ; if ($?) { g++ pattern.cpp -o pattern } ; if ($?) { .\pattern }`

Change the default shell from powershell to command prompt and then check the issue if it is resolved or not

**Comment by Srivardhan11** [comment]
> > I wrote a simple program to print hello World. It runs in the output window and the external terminal but fails to do so in the integrated one even though I have enabled  Run in  Terminal Option , but it stops here :
> > ` cd "c:\Users\KIIT\Desktop\CPP\" ; if ($?) { g++ pattern.cpp -o pattern } ; if ($?) { .\pattern }`
> 
> Change the default shell from powershell to command prompt and then check the issue if it is resolved or not

I use Bash as default so I tried changing to PowerShell and then Command prompt too but  it did not help.

**Comment by Srivardhan11** [comment]
> > > I wrote a simple program to print hello World. It runs in the output window and the external terminal but fails to do so in the integrated one even though I have enabled  Run in  Terminal Option , but it stops here :
> > > ` cd "c:\Users\KIIT\Desktop\CPP\" ; if ($?) { g++ pattern.cpp -o pattern } ; if ($?) { .\pattern }`
> > 
> > 
> > Change the default shell from powershell to command prompt and then check the issue if it is resolved or not
> 
> I use Bash as default so I tried changing to PowerShell and then Command prompt too but it did not help.

It started working in powershell all of a sudden, I don't know how. Now how to switch to bash?

**Comment by Amitbis99e** [comment]
> > I wrote a simple program to print hello World. It runs in the output window and the external terminal but fails to do so in the integrated one even though I have enabled  Run in  Terminal Option , but it stops here :
> > ` cd "c:\Users\KIIT\Desktop\CPP\" ; if ($?) { g++ pattern.cpp -o pattern } ; if ($?) { .\pattern }`
> 
> Change the default shell from powershell to command prompt and then check the issue if it is resolved or not

No  its still not working.....

**Comment by Mehul773** [comment]
> 

Thanks work for me

**Comment by AceBazzz** [comment]
I fixed it, this is my charity :)
![image](https://github.com/formulahendry/vscode-code-runner/assets/65260700/78d7721d-ffd5-42e3-bd11-dd2c3deb9f15)

**Comment by myaasiinh** [comment]
> Hi @thebigJ007 , you could go to `File` > `Preferences` -> `User Settings` to add setting as below:
> 
> ```json
> {
>     "code-runner.runInTerminal": true
> }
> ```
> 
> Then you could run C++ in built-in terminal with input support

thanks helpfully me, set in config run in terminal :)
