### ISSUE TITLE
Feature request: Filter selected text through an external command

### ISSUE THREAD

**Issue by pfmoore** [formulahendry/vscode-code-runner#74]
I'm not sure whether this fits with the purpose of this extension, but what I'd like to be able to do is:

1. Select some text in my file.
2. Run a command that prompts me for a shell command.
3. Executes that shell command with the selected text as standard input.
4. Replaces the selected text with the standard output of the command.

For step (2), the command would be input by the user, not configured in settings. This is the equivalent of Vim's ```:!``` command, or Emacs' ```shell-command-on-region```.

**Comment by formulahendry** [comment]
Thanks @pfmoore for your feedback. 😃 However, this request would not much fit the scope of this extension.

**Comment by pfmoore** [comment]
OK, I suspected as much. Thanks for confirming that. Maybe I'll look at writing my own extension for this :smile:

**Comment by pfmoore** [comment]
Actually, I just found https://marketplace.visualstudio.com/items?itemName=yhirose.FilterText which does exactly what I want. Mentioning it here in case others come across this request.
