### ISSUE TITLE
Code Runner not using 64Bit PowerShell

### ISSUE THREAD

**Issue by mpearon** [formulahendry/vscode-code-runner#75]
Jun,
     I verified that my terminal.integrated.shell.windows is "C:\\WINDOWS\\Sysnative\\WindowsPowerShell\\v1.0\\powershell.exe".  In the integrated terminal, [System.Environment]::Is64BitProcess returns $true, but if I execute the same code with Code Runner, it is returning $false:

```
[Running] powershell -ExecutionPolicy ByPass -File "s:\PowerShell\temp-tqrjmicsjb.ps1"
False

[Done] exited with code=0 in 0.188 seconds
```
So, I think that Code Runner is calling the x86 version of PowerShell.

>  
> Matthew Pearon  
> Thursdsay    
> Great extension!
> Is there any way to ensure that the PowerShell instance that is used is 64bit? It seems to be 32bit.
> [System.Environment]::Is64BitProcess
> $false 
>  
> Jun Han 
> Thursday
> Thanks for using it! Actually, the PowerShell instance is controlled by VS Code itself. My [System.Environment]::Is64BitProcess is ‘True’. Could you please check your "terminal.integrated.shell.windows" in User Settings to see if it is "C:\\windows\\Sysnative\\WindowsPowerShell\\v1.0\\powershell.exe"? If not, you could config by yourself. 
>

**Comment by formulahendry** [comment]
Previously, I assume you have set `"code-runner.runInTerminal": true`. In that case, the powershell (vscode 1.9) is 64bit.  If you have not set that, the extension will use the system powershell. It seems that the system powershell in Windows is using 32bit powershell.
![image](https://cloud.githubusercontent.com/assets/1050213/22858941/e1a91f60-f107-11e6-96e9-083452ba69c9.png)
To use 64bit powershell, there are two options:
1. change the system powershell to use 64bit (I have not tried, maybe just change the PATH enviromnent variables?)
2. specify the powershell path in `code-runner.executorMap`, go to `File` > `Preferences` -> `Settings` to add setting as below:
``` json
{
    "code-runner.executorMap": {
        "powershell": "\"C:\\WINDOWS\\Sysnative\\WindowsPowerShell\\v1.0\\powershell.exe\" -ExecutionPolicy ByPass -File"
    }
}
```
