### ISSUE TITLE
Cannot Run the C program keeps on loading

### ISSUE THREAD

**Issue by prajjwallive** [formulahendry/vscode-code-runner#756]
- VS Code Version: 1.52.1
- OS Version: windows 10
- Code Runner Version: v 0.11.3

**Describe the bug**
Description of what the bug is.
It keeps on showing that Code is running for a very long period of time and doesn't execute the program too. It run Smoothly when the program is written to print the hello world or any printing stuffs and doesn't even display  the error

**To Reproduce**

1. Run vs code 
2. code // program to calculate the area of an rectangle//
#include<stdio.h>
int main(){
    int a,b;
    printf("Enter the Length and breadth of an rectangle \n");
    scanf("%d%d",&a,&b);
    int area = a*b ;
    printf("The area of Rectangle is %d",area);
    return 0;
}
3. see the output terminal section

**Actual behavior**
Description of what happened actually.
I wanted to practice my C programming in Visual Code but it doesn't Execute the code or compile the code though it was correct and 100% working in other compiler
**Expected behavior**
Description of what you expected to happen.
I expected to run the program like this
![image](https://user-images.githubusercontent.com/76769901/112428337-1e9fcd00-8d63-11eb-8dd9-49bf34af3589.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/76769901/112427538-da5ffd00-8d61-11eb-9966-baa4e2ea7fb6.png)

**Comment by formulahendry** [comment]
Please refer to https://github.com/formulahendry/vscode-code-runner/issues/91
