### ISSUE TITLE
ExecutionMessage flash blinded my Titanium eyes...

### ISSUE THREAD

**Issue by Mohanson** [formulahendry/vscode-code-runner#76]
![OhhhhMyEyes](http://lavender.b0.upaiyun.com/3ff2f1bbf2dc721e2344dca45ed8857a.png)

Can do some simple?  Or give a switch to just use one color?

:)

**Comment by formulahendry** [comment]
The colour of execution message varies from different theme. To take care of your Titanium eyes, you could turn off the execution message: `"code-runner.showExecutionMessage": false`  :)
