### ISSUE TITLE
Code-runner just slowed down with latest release

### ISSUE THREAD

**Issue by ANTGOMEZ** [formulahendry/vscode-code-runner#78]
Hi,

Just updated coderunner to v0.6.10 and it got much slower that it used to be in VSCode. I hit ctrl-alt-N and it takes 10 secs to run a function that used to be almost instant. Also Debugging now takes about 5 secs to initialize when prior to update it was immediate. All I've done is UPDATE not other setting or config changes.

Thanks

**Comment by formulahendry** [comment]
Hi @ANTGOMEZ , v0.6.10 is working normally in my three machines. And v0.6.10 just has minor change which should not have impact on perf. Do you have any other change on your machine? Could you please install v0.6.9 [code-runner-0.6.9.vsix](https://github.com/formulahendry/vscode-code-runner/releases/download/0.6.9/code-runner-0.6.9.vsix) and try again?

**Comment by ANTGOMEZ** [comment]
Rebooted and the issue wen away.

Thanks.
