### ISSUE TITLE
C/C++ doesn't include libraries defined in c_cpp_properties.json

### ISSUE THREAD

**Issue by amrahman96** [formulahendry/vscode-code-runner#81]
I'm not sure how possible this would be to do, but it would be really nice.

Thanks!

**Comment by formulahendry** [comment]
Seems like c_cpp_properties.json is specific in C/C++ extension for code completion and navigation https://code.visualstudio.com/docs/languages/cpp#_getting-started. This is a not standard for C/C++. So will not support that.
