### ISSUE TITLE
[Bug]The Error In Running C# File

### ISSUE THREAD

**Issue by liuzhijun-source** [formulahendry/vscode-code-runner#830]
- VS Code Version: 1.57.1(user steup)
- OS Version: Windows11 22000.51
- Code Runner Version: v0.11.4

**Describe the bug**
After I ran the "dotnet new console" in terminal, I open the "Program.cs". Then I click the run button of code runner. The error will be reported at run time. The contents of the error report are as follows: 
scriptcs : 无法将“scriptcs”项识别为 cmdlet、函数、脚本文件或可运行程序的名称。请检查名称的拼写，如果包括路径，请确    
保路径正确，然后再试一次。
But in the "settings.json", If I change the "csharp": "scriptcs" in the "code-runner.executorMap" to "csharp": "dotnet run", It will work. "dotnet run" is the command to run the .exe file of .Net. If the "Program.cs" doesn't compile to the .exe file yet. It will compile the file first.
![屏幕截图 2021-07-08 150736](https://user-images.githubusercontent.com/69884931/124878202-6db1fb00-dffe-11eb-915a-4f2e83842d4a.png)
![屏幕截图 2021-07-08 150826](https://user-images.githubusercontent.com/69884931/124878277-802c3480-dffe-11eb-8f67-a4f381066c92.png)

**To Reproduce**
I don't know how to write it.
1. 
2. 

**Actual behavior**
I don't know how to write it

**Expected behavior**
I don't know how to write it.

**Screenshots**

**Comment by Someone-Of-Liu** [comment]
Dotnet new console is designed to create a console application

**Comment by ICHx** [comment]
https://github.com/formulahendry/vscode-code-runner/issues/672
