### ISSUE TITLE
After selecting the default shell as bash (wsl) why code runner still running code in powershell please tell me how to fix it[Bug]

### ISSUE THREAD

**Issue by SouvikH2002** [formulahendry/vscode-code-runner#857]
- VS Code Version:
- OS Version:
- Code Runner Version:

**Describe the bug**
Description of what the bug is.

**To Reproduce**

1. 
2. 

**Actual behavior**
Description of what happened actually.

**Expected behavior**
Description of what you expected to happen.

**Screenshots**

**Comment by formulahendry** [comment]
Duplicated with: https://github.com/formulahendry/vscode-code-runner/issues/858
