### ISSUE TITLE
Running C++ file not working in Powershell 7.2.0 preview 9 [Bug]

### ISSUE THREAD

**Issue by namitgpta** [formulahendry/vscode-code-runner#860]
- VS Code Version: 1.60.0
- OS Version: Windows 11 Pro x64
- Code Runner Version: v0.11.5

**Describe the bug**
Some days ago, all was working fine. But now when trying to run any cpp file, it shows this error in powershell integrated terminal:
![image](https://user-images.githubusercontent.com/60420298/132136430-de40f449-8d81-4734-b6c9-35ac16422f19.png)

This command when copied in cmd, runs fine.

**To Reproduce**

1. Run any cpp file with default configs of Code Runner extension.
2. Run in powershell integrated terminal of vscode because I unable to change it to default cmd for code runner.

**Actual behavior**
Description of what happened actually.

**Expected behavior**
Description of what you expected to happen.

**Screenshots**
![image](https://user-images.githubusercontent.com/60420298/132136454-1d1537de-c65c-41fc-b228-e759cdd070a8.png)

**Comment by YaduAhuja** [comment]
This Issue is also related to #858. Check that Discussion for help.
