### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by himanshured0** [formulahendry/vscode-code-runner#862]
After this new update of VS Codes, I am unable to successfully run a simple c  & c++ code. Here is the snapshot. 
![image](https://user-images.githubusercontent.com/45516142/132510487-df03cb79-4945-4928-a4c4-51e959f285d1.png)

**Comment by formulahendry** [comment]
Duplicated with https://github.com/formulahendry/vscode-code-runner/issues/858
