### ISSUE TITLE
The code runner extension cannot work properly while running code of C program files in case of tking input from the users that is scanf()[Bug]

### ISSUE THREAD

**Issue by Dorna1111** [formulahendry/vscode-code-runner#865]
- VS Code Version:
- OS Version:
- Code Runner Version:

**Describe the bug**
Description of what the bug is.

**To Reproduce**

1. 
2. 

**Actual behavior**
Description of what happened actually.

**Expected behavior**
Description of what you expected to happen.

**Screensho
![Screenshot (10)](https://user-images.githubusercontent.com/89678521/132860174-cc6db492-3170-4f57-9974-a48c2fd83cfe.png)
ts**
``

**Comment by YaduAhuja** [comment]
To give Input to Program, use the  `Run In Terminal` Option from Code Runner's Settings.

**Comment by Dorna1111** [comment]
Ok Thank you for your response

**Comment by Vishal973** [comment]
> To give Input to Program, use the `Run In Terminal` Option from Code Runner's Settings.

Thank you YaduAhuja. I did what you suggested in comment and now my **Code Runner** extension is running smoothly.
