### ISSUE TITLE
After an F# program fails, you can't fix it and run again

### ISSUE THREAD

**Issue by gbritton1** [formulahendry/vscode-code-runner#87]
I am learning F#.  Trying to use CodeRunner in VSCode to test it.  I coped a simple example program and tried to run it.  got the F# error:

> agents.fs(2,1): error FS0222: Files in libraries or multiple-file applications must begin with a namespace or module declaration, e.g. 'namespace SomeNamespace.SubNamespace' or 'module SomeNamespace.SomeModule'
> > 

which is fine, since I'm learning F# and I expect lots of mistakes. however, after fixing the error, I cannot run the program again.  I get the error from VSCode: 

"Code is already running!" 

Which it isn't as far as I can see.

Whether is *is* running or not, I cannot see anyway to stop it or restart it other than restarting vscode

**Comment by formulahendry** [comment]
Hi @gbritton1 , as mentioned in README, to stop the running code, there are there wasys:
* use shortcut `Ctrl+Alt+M`
* or press `F1` and then select/type `Stop Code Run`
* or right click the Output Channel and then click `Stop Code Run` in context menu

Then, you would see something like `[Done] exited with ...`
![image](https://cloud.githubusercontent.com/assets/1050213/23444489/6a8fbd50-fe70-11e6-8456-f816b09e2361.png)

Let me know if it works for you!

**Comment by gbritton1** [comment]
got it.
