### ISSUE TITLE
Run file through context menu of file explorer

### ISSUE THREAD

**Issue by look997** [formulahendry/vscode-code-runner#88]
Please add "Run all commands from file" in context menu of file in sidebar.

**Comment by formulahendry** [comment]
Hi @look997 , what do mean of "Run all commands from file"? The "Run Code" command and put it into context menu of the file explorer in sidebar?

**Comment by look997** [comment]
Yes. Exactly that.

**Comment by look997** [comment]
Not exactly.
The "Run Code" command runs the selected commands in a visible file.
I want to run commands from all lines of the file. Not from selected text.
But yes, put it into context menu of the file explorer in sidebar.

**Comment by formulahendry** [comment]
Got it.
Could you please share more details about you use case? Do you want to always run a single file (e.g. main.cpp) without switching to that single file in VS Code?

**Comment by look997** [comment]
Eg. I want to run the make file:
"
#!/bin/sh
make
"
or a single library:
"
#!/bin/sh
make lib1.o
"
Or another project add-ons for Firefox:
" xpi file
#!/bin/sh
jpm xpi
"
or post file
"
#!/bin/sh
jpm post --post-url http://localhost:8888/
"
or watchpost file
"
#!/bin/sh
jpm watchpost --post-url http://localhost:8888/
"

The idea is to not have to enter commands manually. Just do two clicks on a file, and it is run.
Like this as you can go to the project folder and run the file but it is more convenient to do it in the IDE.
You can also add additional action eg. Mouse Middle Click on file to run this file. Less clicks.

**Comment by formulahendry** [comment]
Got it. Currently, it has some technical blocker to implement 'Run Code' in file explorer. I will take a look whether it is possible to make that. In short term, you could set custom command as below, then use shortcut `Ctrl+Alt+K` to trigger. The limitation is that you could only config one custom command per workspace:
```
{
    "code-runner.customCommand": "make lib1.o"
}
```

**Comment by look997** [comment]
Ok, but I prefer the method of cliques and not shortcut.

**Comment by formulahendry** [comment]
cliques --> clicks ?

**Comment by look997** [comment]
Yes. :)

**Comment by look997** [comment]
But in context menu of the file explorer in sidebar is possible?

**Comment by formulahendry** [comment]
No, currently, it has some technical blocker.

**Comment by formulahendry** [comment]
Checking `openTextDocument` API

**Comment by formulahendry** [comment]
Hi @look997 , this function is added. Please have a try.

**Comment by look997** [comment]
@formulahendry I checked. Looks ok. Works.
Thanks.
