### ISSUE TITLE
[Feature request] vscode: Allow user input in the "output" panel

### ISSUE THREAD

**Issue by lmjaedentai** [formulahendry/vscode-code-runner#899]
`input` in python can let us to input the value we want to the program in **terminal**.

But in code runner when my program is running in **output** panel 
I can't input anything in **output** panel although the cursor is there.

<img width="347" alt="image" src="https://user-images.githubusercontent.com/63090071/145698047-ca677352-d4f5-4ddf-b06b-d5510a27a3e1.png">

I'm not sure this is the problem of vscode output panel or the problem of extension.
I would appreciate for every help.

**Comment by klevvit** [comment]
In Code-runner settings you can select "Run In Terminal", this should solve your problem
