### ISSUE TITLE
Python彩色输出

### ISSUE THREAD

**Issue by anson2416** [formulahendry/vscode-code-runner#90]
请问你是怎样实现运行Python的时候，输入是彩色的？

**Comment by formulahendry** [comment]
先定义mimetypes为text/x-code-output的language：
https://github.com/formulahendry/vscode-code-runner/blob/master/package.json#L205
然后再写textmate language grammar:
https://github.com/formulahendry/vscode-code-runner/blob/master/syntaxes/code-runner-output.tmLanguage
