### ISSUE TITLE
How to input after running?

### ISSUE THREAD

**Issue by livc** [formulahendry/vscode-code-runner#91]
for example in c++, 
```cpp
cin >> t;
```
How can I input?

**Comment by formulahendry** [comment]
For input support, please use below setting (`File`->`Preference`->`Settings`) to run code in Integrated Terminal:
```json
{
    "code-runner.runInTerminal": true
}
```

**Comment by pranshuchittora** [comment]
The current issue with the extension is that , if I run a program which includes a stdin the output window waits for the input and the only way to terminate it is close the application . Under default settings.

## Ideal solution would be include some way to terminate it and also include some GUI button to run the program in terminal .

**Comment by JPGITHUB1519** [comment]
This is nice, thanks!

**Comment by BlueSky7** [comment]
> 
> 
> for example in c++,
> 
> ```c++
> cin >> t;
> ```
> 
> How can I input?
Two ways:
(1) In setting.json file => add this line- 
{
    "code-runner.runInTerminal": true
//    Other lines...
}
You are done!!
Or
(2) Follow these steps-
Step1. Go to File > Preference > Setting.
Step2. Then on the left panel, scroll and find 'Run Code Configuration'. 
Step3. Under that option: keep cursor on "code-runner.runInTerminal" and click on edit icon.
Step4: You will see two true & false option. Make it true. 
Step5: You are done!!

**Comment by aalliikk** [comment]
> ```json
> "code-runner.runInTerminal": true
> ```

👏🏻👏🏻👏🏻

**Comment by vishalgautam** [comment]
not working in mac.

**Comment by hwax0r** [comment]
> not working in mac.

it works well on mine mbp

**Comment by agoeden12** [comment]
In case you run into issues with a bash error like "bash: cd: too many arguments" then I found this to be a solution in the visual studio code settings for code runner:
 `"code-runner.executorMap": {
        "cpp": "g++ $fileName -o $fileNameWithoutExt.exe && './$fileNameWithoutExt.exe'"
    }`

**Comment by JcsnP** [comment]
> > for example in c++,
> > ```c++
> > cin >> t;
> > ```
> > 
> > 
> > How can I input?
> > Two ways:
> > (1) In setting.json file => add this line-
> > {
> > "code-runner.runInTerminal": true
> > //    Other lines...
> > }
> > You are done!!
> > Or
> > (2) Follow these steps-
> > Step1. Go to File > Preference > Setting.
> > Step2. Then on the left panel, scroll and find 'Run Code Configuration'.
> > Step3. Under that option: keep cursor on "code-runner.runInTerminal" and click on edit icon.
> > Step4: You will see two true & false option. Make it true.
> > Step5: You are done!!

Thanks Dude ^_^

**Comment by Igaurav31** [comment]
> For input support, please use below setting (`File`->`Preference`->`Settings`) to run code in Integrated Terminal:
> ```json
> {
>     "code-runner.runInTerminal": true
> }
> ```

Thank you so much I had started using dev c++ due to this issue l. Thanks again🙏.

**Comment by Marines1775** [comment]
> > For input support, please use below setting (`File`->`Preference`->`Settings`) to run code in Integrated Terminal:
> > ```json
> > {
> >     "code-runner.runInTerminal": true
> > }
> > ```
> 
> Thank you so much I had started using dev c++ due to this issue. Thanks again🙏.

So this will work for any language?   I'm using Python and looking for a way to run my code but with out all the file path added garbage.
TIA

**Comment by letpadjoin** [comment]
> 

Did you find any solution?
I have the same problem using Python I want to clear output.

**Comment by letpadjoin** [comment]
> > > For input support, please use below setting (`File`->`Preference`->`Settings`) to run code in Integrated Terminal:
> > > ```json
> > > {
> > >     "code-runner.runInTerminal": true
> > > }
> > > ```
> > 
> > 
> > Thank you so much I had started using dev c++ due to this issue. Thanks again🙏.
> 
> So this will work for any language? I'm using Python and looking for a way to run my code but with out all the file path added garbage. TIA

Did you find any solution?
I have the same problem using Python I want to clear output.

**Comment by Marines1775** [comment]
This is the latest I have [received](https://stackoverflow.com/questions/63758560/how-to-hide-the-file-path-displaying-in-visual-studio-codes-terminal/70914653?noredirect=1#comment125520371_70914653).

**Comment by deepakchandra4** [comment]
i found the json file but it's on read only mode i can't edit it. can someone tell me how to make that changes.

**Comment by Marines1775** [comment]
I came across this yesterday that maybe of assistance.

https://ehmatthes.github.io/pcc_3e/setup_instructions/configuring_vs_code/

**Comment by technoadnan** [comment]
> i found the json file but it's on read only mode i can't edit it. can someone tell me how to make that changes.

- Click the tab(left click) of the setting.json 
![image](https://github.com/user-attachments/assets/e9e5cbc3-daee-4522-bcba-e8dc971b4c1a)
- open in file explorer
![image](https://github.com/user-attachments/assets/601a7746-77b4-4350-9de2-1d2cea7d4747)
- finally open in notepad and you can edit.
