### ISSUE TITLE
Focus on terminal while/after run

### ISSUE THREAD

**Issue by ghKelo** [formulahendry/vscode-code-runner#93]
I know there was a similar issue(#32).

I usually have to input some data after running, so focusing on code window is very inconvenient for me that I have to move my mouse to terminal and click it...

Could you please add an option to control it?

**Comment by formulahendry** [comment]
Thanks for your feedback. Will add option to control it.

**Comment by formulahendry** [comment]
Hi @ghKelo , this option has been addded. To let terminal take focus, use below settings:
```json
{
    "code-runner.preserveFocus": false
}
```
Please try the latest release

**Comment by ghKelo** [comment]
thanks
