### ISSUE TITLE
[Bug][typescript] environment path not included in vscode with customized terminal settings

### ISSUE THREAD

**Issue by dimaslanjaka** [formulahendry/vscode-code-runner#938]
- VS Code Version: latest
- OS Version: windows 10
- Code Runner Version: nodejs 16.x

**`PATH` from terminal vscode**
```shell
D:\Repositories\gh-pages>echo %PATH%
D:\Repositories\gh-pages\node_modules\.bin;D:\Repositories\gh-pages\bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Users\dimas\AppData\Local\Microsoft\WindowsApps;D:\bin\node\windows;C:\Users\dimas\AppData\Local\GitHubDesktop\bin;D:\ProgramData\Microsoft VS Code\bin;C:\Users\dimas\AppData\Local\GitHubDesktop\app-2.9.12\resources\app\git\cmd;D:\xampp\mysql\bin;D:\xampp\php
```
![image](https://user-images.githubusercontent.com/12471057/161589892-a5c3beb3-83a7-4c15-9c05-839a6d8e1af5.png)

**ts-node location**
```shell
D:\Repositories\gh-pages>where ts-node
D:\Repositories\gh-pages\node_modules\.bin\ts-node
D:\Repositories\gh-pages\node_modules\.bin\ts-node.cmd
```
![image](https://user-images.githubusercontent.com/12471057/161590437-b40681ed-ebe0-4885-bdb0-a20a0937078b.png)

**Workspace settings.json**
```jsonc
{
  "terminal.integrated.env.linux": {
    "PATH": "${workspaceFolder}/node_modules/.bin:${workspaceFolder}/bin:${env:PATH}"
  },
  "terminal.integrated.env.windows": {
    "PATH": "${workspaceFolder}\\node_modules\\.bin;${workspaceFolder}\\bin;${env:PATH}"
  },
  "npm.enableRunFromFolder": true,
  "files.autoSave": "onWindowChange",
  "files.autoSaveDelay": 30000,
  "typescript.tsc.autoDetect": "on",
  "editor.fontFamily": "Consolas, 'Courier New', monospace",
  "editor.fontLigatures": true,
  "editor.fontSize": 13,
  "emmet.includeLanguages": {
    "ejs": "html",
  },
  "editor.wordWrap": "on",
  "editor.bracketPairColorization.enabled": true,
  "javascript.suggestionActions.enabled": false,
  "typescript.suggestionActions.enabled": true,
  "editor.codeActionsOnSave": {
    "source.fixAll.eslint": true // let ESLint take formating and linting
  },
  "[ejs]": {
    "editor.formatOnSave": false,
    "editor.defaultFormatter": "vscode.html-language-features"
  },
  "[json]": {
    "editor.formatOnSave": true, // enable json formating with default vscode formatter
    "editor.defaultFormatter": "vscode.json-language-features"
  },
  "[markdown]": {
    "editor.formatOnSave": false,
    "editor.defaultFormatter": "yzhang.markdown-all-in-one"
  },
  "[jsonc]": {
    "editor.formatOnSave": true,
    "editor.defaultFormatter": "vscode.json-language-features"
  },
  "[typescript]": {
    "editor.formatOnSave": false,
    "editor.defaultFormatter": "vscode.typescript-language-features"
  },
  "[javascript]": {
    "editor.formatOnSave": false,
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "editor.formatOnSave": false,
  "editor.tabSize": 2,
  "files.eol": "\n",
  "files.exclude": {
    "**/node_modules": true,
    "**/vendor": true
  },
  "typescript.tsdk": "./node_modules/typescript/lib",
  "typescript.format.enable": true,
  "typescript.tsserver.enableTracing": false,
  "typescript.tsserver.log": "off",
  "typescript.tsserver.trace": "off",
  "editor.autoClosingBrackets": "always",
  "editor.matchBrackets": "always",
  "prettier.enableDebugLogs": true,
  "prettier.prettierPath": "./node_modules/prettier",
  "prettier.printWidth": 180,
  "npm.packageManager": "npm"
}
```

**Describe the bug**
```log
[Running] ts-node "d:\Repositories\gh-pages\src\__test__\generate.ts"
'ts-node' is not recognized as an internal or external command,
operable program or batch file.

[Done] exited with code=1 in 0.073 seconds
```

**To Reproduce**

1. create file.ts
2. run directly from context menu (right click)

**Actual behavior**
i dont know to fill this

**Expected behavior**
i dont know to fill this

**Screenshots**
- step to run
![image](https://user-images.githubusercontent.com/12471057/161589604-fa6af068-4716-41c4-9962-b4581c6521fb.png)
- error
![image](https://user-images.githubusercontent.com/12471057/161589697-9d747aab-26ce-4cf3-a6a2-42f59f775276.png)

**Comment by dimaslanjaka** [comment]
for now working configuration is:
```jsonc
"code-runner.executorMap": {
    "typescript": "node -r ts-node/register --project ${workspaceFolder}/tsconfig.json",
}
```
i hope next update automated for typescript binary path (integrated with customized settings.json)

**Comment by zq0904** [comment]
> 现在工作配置是：
> 
> ```js
> "code-runner.executorMap": {
>     "typescript": "node -r ts-node/register",
> }
> ```
> 
> 我希望下次自动更新打字稿二进制路径（与定制的 settings.json 集成）



> for now working configuration is:
> 
> ```js
> "code-runner.executorMap": {
>     "typescript": "node -r ts-node/register",
> }
> ```
> 
> i hope next update automated for typescript binary path (integrated with customized settings.json)

However, there is still no support for TS-Node that is not installed in the project root such as monorepo project
My expectation is that NPX ts-Node will look for the address in the executable file directory

I didn't find any configuration to play
Be able to do this in the directory of the execution file

**Comment by dimaslanjaka** [comment]
## FIXED
with custom setting called `shebang`:
```jsonc
{
  "code-runner.respectShebang": true
}
```

full settings:
```jsonc
{
  "code-runner.executorMap": {
    "javascript": "node",
    "typescript": "node -r ts-node/register",
    "coffeescript": "coffee",
    "sass": "sass --style expanded",
    "scss": "scss --style expanded",
    "less": "cd $dir && lessc $fileName $fileNameWithoutExt.css"
  },
  "code-runner.runInTerminal": true,
  "code-runner.cwd": "${workspaceFolder}",
  "code-runner.saveAllFilesBeforeRun": true,
  "code-runner.clearPreviousOutput": true,
  "code-runner.respectShebang": true,
}
```

**Comment by zq0904** [comment]
> ## FIXED
> with custom setting called `shebang`:
> 
> ```js
> {
>   "code-runner.respectShebang": true
> }
> ```
> 
> full settings:
> 
> ```js
> {
>   "code-runner.executorMap": {
>     "javascript": "node",
>     "typescript": "node -r ts-node/register",
>     "coffeescript": "coffee",
>     "sass": "sass --style expanded",
>     "scss": "scss --style expanded",
>     "less": "cd $dir && lessc $fileName $fileNameWithoutExt.css"
>   },
>   "code-runner.runInTerminal": true,
>   "code-runner.cwd": "${workspaceFolder}",
>   "code-runner.saveAllFilesBeforeRun": true,
>   "code-runner.clearPreviousOutput": true,
>   "code-runner.respectShebang": true,
> }
> ```

Thank you for sharing
Under the Monorepo project, this applies to me
```ts
  "code-runner.fileDirectoryAsCwd": true, // Set it up
  // Don't set code-runner.cwd
```
