### ISSUE TITLE
It doesn't seem to support running it multiple times

### ISSUE THREAD

**Issue by nikitavoloboev** [formulahendry/vscode-code-runner#94]
For example, running it for the first time works, however if you do run it again on a changed file, there is no output : 

![2017-03-14 at 00 15](https://cloud.githubusercontent.com/assets/6391776/23879109/65e91ba4-084b-11e7-8258-04e2bb5011c9.png)

It's the same with go files too however python code works well and I can run the same file multiple times and actually get results.

**Comment by formulahendry** [comment]
I remember another user has the similar issue (using Go) but I could not find the issue in the issue list.
Does the same issue happen if you do not run it in terminal?

**Comment by nikitavoloboev** [comment]
Hey @formulahendry, that issue was also raised by me :)

I just checked and it actually runs the file correctly from the command line. I can run node on the file as many times as I want.

**Comment by formulahendry** [comment]
How about setting `"code-runner.runInTerminal": false`?

**Comment by nikitavoloboev** [comment]
Thank you so much, this works well.
