### ISSUE TITLE
Consider on-boarding to VS Code Sponsorship

### ISSUE THREAD

**Issue by isidorn** [formulahendry/vscode-code-runner#948]
Hi VS Code PM here 👋 

Consider on-boarding to VS Code sponsorship. It is as easy as adding:
```json
"sponsor": {
  "url": "https://www.patreon.com/junhan/creators"
}
```

to your `package.json`

More details here
https://github.com/microsoft/vscode-discussions/discussions/14

**Comment by formulahendry** [comment]
Adopted. Thanks a lot! ❤️ 
![image](https://user-images.githubusercontent.com/1050213/173195202-f8fdd1f6-e072-4e0f-b2e9-1a3b07573577.png)

**Comment by isidorn** [comment]
Awesome thanks!
