### ISSUE TITLE
我在跑八皇后问题时出了点问题

### ISSUE THREAD

**Issue by taibai233** [formulahendry/vscode-code-runner#95]
跑到第83个解时，就输出了一段乱码然后不再输出了，切程序没有停止运行。我用终端跑是没有问题的

这是怎么一回事呢

**Comment by formulahendry** [comment]
This is a one-time issue or always failing?

**Comment by taibai233** [comment]
always failing

**Comment by formulahendry** [comment]
Could you try below settings to run code in terminal? Go to `File` > `Preferences` -> `Settings` to add setting as below:
``` json
{
    "code-runner.runInTerminal": true
}
```

**Comment by taibai233** [comment]
fine, it works
