### ISSUE TITLE
Is there a way to customize the content of terminal running program

### ISSUE THREAD

**Issue by ydmykr** [formulahendry/vscode-code-runner#953]
Before that, I made some queries. I think this should be related to "code runner. CustomCommand", but I didn't find the relevant example. 

If I want to convert the command from "python test.py" to "python test.py -i", how should I set it?

**Comment by SaarthakTuli** [comment]
So you can locally fix that in your extension setting...

1. Select your extension and open Extension Settings
2. Then scroll down to Code Runner: Executor Map and click on Edit in settings.json
3. Find and edit the value for "python" key as given in the photo
![Screenshot 2022-09-08 at 11 08 54 PM](https://user-images.githubusercontent.com/89101837/189189904-71d6f98c-7341-4d4d-ad94-3f396814d913.jpg)
4. Change the value from "python -u" to "python -u -i"

Hopefully this will help you.

**Comment by ydmykr** [comment]
@SaarthakTuli Thanks a lot！
