### ISSUE TITLE
collision with another popular vscode plugin

### ISSUE THREAD

**Issue by symisz** [formulahendry/vscode-code-runner#994]
I found a "bug", its easily avoided, but it took me by surprise and I finally found what caused Code Runner to stop running properly.

Writing `#!` on the first line will prevent Code Runner from running. `#!` is used to write comments and specifically its used to highlight comments with the plugin: https://github.com/aaron-bond/better-comments

While writing in PowerShell, I highlighted an comment on the first line with `#!`, this caused an error with Code Runner:
To reproduce this error, write a powershell file with the following
(installing the plugin https://github.com/aaron-bond/better-comments is probably optional)
```pwsh
#! ThisIsAComment

$test = "test"
Write-Host $test
```
> 'ThisIsAComment' is not recognized as an internal or external command,
operable program or batch file.

The "bug" is easily avoided, so might call this low prio

**Comment by lokesh-kurre** [comment]
`#!` this keyword is generally used to run a script as shell script. It's not a comment.
When any file is started with a #! (shebang), this extension treat that file as script, not a regular source code file.
FYI the word after shebang, is treated as executable, in your case `ThisIsAComment` treated as executable, and extension tried to find it in path.
